# 검증 캠페인 주간 판정 리포트

- 생성: 2026-07-31 15:47:52  (분석 창 28일, 캠페인 시작 2026-07-05)
- 합격선: `config/settings.py:VALIDATION_CAMPAIGN` (사전 등록 — 변경 금지)
- 근거: `docs/260705_OFFENSE_READINESS_AUDIT_AND_NEXT_PHASE.md` §3

| 채널 | 판정 | 핵심 수치 |
|---|---|---|
| [0] 표본 기아 경보 | 🚨 STARVED | 주간진입=9건(하한 10) 4주투영=36건 |
| [1] Triple-Barrier | ❌ FAIL | 합격 호라이즌 0개 (기준 2개) |
| [2] Meta-Gate | ❌ FAIL | 상위EV=-0.1827 분리도=-0.044 (필요 0.1457) |
| [3] 분위 회귀 | ✅ PASS | 커버리지=0.8091 (밴드 [0.72, 0.88]) 상관=0.3275 |
| [4] 신호소멸청산 | ❌ FAIL | 누적 saved=-2.0516pt (n=10, 보류 0) |
| [5] 레짐 ATR 배수 | ⏳ INSUFFICIENT | mean-revert: n=35 EV=-11,389원 / neutral: n=24 EV=20,359원 / trend: n=14 EV=-273,180원 |
| [6] Hurst 게이트 counterfactual | ❌ FAIL | 누적 hyp=37.7244pt 승률=69.9% (n=236, 보류 0) |
| [7] JointGateBlock counterfactual | ✅ PASS | 누적 hyp=-13.1632pt 승률=69.8% (n=116, 보류 0) |
| [8] KellyAdvisedSkip×C등급 | ⏳ INSUFFICIENT | 누적 순PnL=-375,636원 승률=33.3% (n=6) |
| [9] OPEN_VOLATILE 시가이격 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=-15.8299pt 승률=61.1% (n=18, 보류 0) |
| [10] TP2 홀드 counterfactual (qty=2 재배분 A/B) | ⏳ INSUFFICIENT | 누적 hyp=0.0pt 승률=0.0% (n=0, 보류 0) TP3=0건 트레일=0건 강제청산=0건 |
| [11] qty=1 손실1차 조기청산 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=13.1383pt 승률=81.8% (n=11, 보류 0) |
| [12] qty=1 TP1 이후 트레일 폭 counterfactual | ✅ PASS | 누적 hyp=-6.6461pt 승률=45.0% (n=20, 보류 0) 트레일스톱=20건 강제청산=0건 |
| [13] 등급별 순EV 역전 감시 | ⏳ INSUFFICIENT | A=-71,185원(n=56, 최대손실=-3,192,244원) C=14,813원(n=17) |
| [14] Tier1 잔여계약 2단계 조기청산 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=0.0pt 승률=0.0% (n=0, 보류 0) |
| [15] 급행 풀스톱(TP1 미도달) 관찰 | 👁 OBSERVE | 급행하드스톱=16건 중 TP1미도달=15건 (A: n=12 누적=-1,195,728원) |
| [16] chase+foreign 조합 관찰 | 👁 OBSERVE | 동시실패=11건 누적=167,462원 (매칭=70건) |
| [17] 청산 체결 슬리피지 관찰 | 👁 OBSERVE | n=10 평균=0.009pt (가정 0.02pt) |
| [18] RegimeExhaustionGate(탈진반전) | ⏳ INSUFFICIENT | 발동=16건 누적hyp=-13.3659pt (STOP=6/TP1=10/NEITHER=0) |
| [19] ToxicityGate block counterfactual | ⏳ INSUFFICIENT | 누적 hyp=2.8836pt 승률=100.0% (n=2, 보류 0) |
| [20] BAR_ONLY_RELAX 수용/롤백 | ⏳ INSUFFICIENT | 완화후 collapse=— (기준선 44.8%, 목표 20%±7%p) 계측일 전1/후2 |
| [21] 방향별 순EV (SYSTEM_AUTO) | ✅ PASS | LONG: n=25 평균=16,138원 최대손실=-351,370원 / SHORT: n=30 평균=12,690원 최대손실=-359,308원 |
| [22] MFE 캡처율 관찰 | 👁 OBSERVE | 풀링캡처 보유내=11.1% 종가까지=1.8% / 평균잔여 22.316 pt (진입 55건) |

## [0] 캠페인 표본 기아 경보 + 완화 사다리 (§3-8)

- 주간(7일) 진입 체결: **9건** (하한 10건) → 4주 투영 36건
- **표본 미달 위험 KPI**: Meta-Gate(§3-2, 분위당 30건×3 필요) / 레짐 ATR 배수(§3-5②, 버킷당 20건×2 필요)
- **완화 사다리 상태**: 1단계 관찰 기간(5거래일) 경과 후에도 기아 지속 — 2단계(MetaGate take_ceil 0.570→0.52) 검토 권고 (사용자 결정 필요)

| 단계 | 조치 | 상태 |
|---|---|---|
| 1 | 관찰만 — FQAdj 배선 수정(297차)의 자연 회복 효과 확인 |  |
| 2 | 구형 MetaGate take_ceil(C등급) 완화: 0.570 → 0.52 | **← 현재** |
| 3 | Hurst 횡보 차단 임계값 완화 (최후 수단): 0.45 → 0.40 |  |

> 사다리 적용은 항상 사용자 수동 결정 — 자동 변경 없음. 적용 시 `dev_memory/DECISION_LOG.md`에 기록할 것.

## [1] Triple-Barrier — OOS replay IC vs 3클래스 IC

| 호라이즌 | 판정 | IC_TB | IC_3class | OOS n | 비고 |
|---|---|---|---|---|---|
| 1m | FAIL | -0.0266 | 0.0108 | 1756 |  |
| 3m | INSUFFICIENT | — | — | 581 | OOS 표본 부족 (581 < 800) — 첫 판정 대기 |
| 5m | INSUFFICIENT | — | — | 345 | OOS 표본 부족 (345 < 800) — 첫 판정 대기 |
| 10m | INSUFFICIENT | — | — | 169 | OOS 표본 부족 (169 < 800) — 첫 판정 대기 |
| 15m | INSUFFICIENT | — | — | 108 | OOS 표본 부족 (108 < 800) — 첫 판정 대기 |
| 30m | INSUFFICIENT | — | — | 49 | OOS 표본 부족 (49 < 800) — 첫 판정 대기 |

> [357차 해석 확정] 1m은 앙상블 가중치 영구 0 퇴역(331차 후속2) 상태 —
> 1m이 IC 기준을 합격해도 "1m 앙상블 복귀"가 아니라 1m 활용방안 A·C
> (331차 후속3, 섀도우 경로)의 근거로만 사용한다. **실질 승격 검토 대상은
> 3m/5m로 한정** (30m은 296차 퇴역). 합격선 자체는 불변 — 해석만 확정
> (시계 리셋 불요).
> [384차] 383차가 규명한 구조결함(평가창이 매주 재학습으로 리셋돼 5m~30m이
> min_samples_hz 영구 미달) 해법 적용 — 이제 호라이즌별 실제 OOS n이
> min_samples_hz에 도달한 주에만 신선하게 판정하고, 그 아래 주는 `tb_verdict_log`의
> 최근 판정을 그대로 유지(위 표의 "(유지, YYYY-MM-DD 판정)")한다. 10m/15m/30m은
> 판정 주기 자체가 몇 주~십수 주 단위로 길 뿐 표본은 끊기지 않고 계속 누적된다.

## [2] Meta-Gate — entry_quality_prob 3분위 순EV (왕복비용 0.0729 pt 차감)

| 분위 | 순EV(pt) | n |
|---|---|---|
| 상위 33% | -0.1827 | 399 |
| 중위 33% | -0.105 | — |
| 하위 33% | -0.1387 | 399 |

## [3] 분위 회귀 — 캘리브레이션

- 표본: 3593건 / 커버리지 0.8091 (합격 밴드 0.72~0.88) / 불확실성-실현폭 상관 0.3275 (하한 0.15)

## [4] 신호소멸청산 counterfactual (§3-5 롤백 기준 ①)

- 이번 실행 resolve: 0건 / 누적 판정 10건 (미판정 0건)
- counterfactual 분포: STOP 2 / TP1 8 / NEITHER 0
- 누적 saved_pts(아낀 pt − 놓친 pt): **-2.0516 pt**
- **권고**: conf 임계를 zone_mc+0.05로 강화 후 2주 재관찰, 재음수 시 OFF

## [5] 레짐 조건부 ATR 배수 (§3-5 롤백 기준 ②)

| 버킷 | n | 평균 순EV(원) | 누적(원) | 승률 |
|---|---|---|---|---|
| mean-revert | 35 | -11,389 | -398,612 | 45.7% |
| neutral | 24 | 20,359 | 488,608 | 54.2% |
| trend | 14 | -273,180 | -3,824,513 | 50.0% |

- 버킷별 표본 부족 (trend/neutral 각 20건 필요)

## [6] Hurst 게이트 counterfactual (§3-6, P1-4)

- 이번 실행 resolve: 10건 / 누적 판정 236건 (미판정 0건)
- counterfactual 분포: STOP 71 / TP1 165 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **37.7244 pt** / 승률 69.9% (기준선 49.3%)
- **권고**: Hurst 하드차단 → 사이징 ×0.5로 완화 권고 (즉시 언블록 금지, §3-6)

## [7] JointGateBlock counterfactual (§3-7, 327차)

- 이번 실행 resolve: 29건 / 누적 판정 116건 (미판정 0건)
- counterfactual 분포: STOP 35 / TP1 81 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-13.1632 pt** / 승률 69.8% (기준선 49.3%)
- meta_size 구간별(tox_size 상수 구조 검증용):
  - high(meta≥0.55): n=22 hyp=-7.9457pt 승률=68.2%
  - low(meta<0.55): n=94 hyp=-5.2175pt 승률=70.2%

## [8] KellyAdvisedSkip × C등급 누적 성과 (341차 신설)

- C등급+KellySkip 체결 n=6 | 누적 순PnL=-375,636원 | 평균=-62,606원 | 승률=33.3%
- 비교(C등급, KellySkip 아님) n=11 | 평균=57,041원 | 승률=54.5%
- 등급별(KellySkip=1 전체, 참고용):
  - A급: n=8 누적PnL=566,553원 승률=75.0%
  - C급: n=6 누적PnL=-375,636원 승률=33.3%
- C등급+KellySkip 표본 부족 (6 < 20) — 판정 보류

## [9] OPEN_VOLATILE 시가이격 counterfactual (§14, 354차)

- 이번 실행 resolve: 0건 / 누적 판정 18건 (미판정 0건)
- counterfactual 분포: STOP 7 / TP1 11 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-15.8299 pt** / 승률 61.1% (기준선 49.3%)
- 평균 gap_pt=25.71 / 평균 atr_at_block=3.25 (기준점 재설계 시 캘리브레이션 근거)
- 차단 표본 부족 (18 < 20) — 판정 보류

## [11] qty=1 손실1차(Loss Tier1) 조기청산 counterfactual (363차)

- 이번 실행 resolve: 1건 / 누적 판정 11건 (미판정 0건)
- 누적 hyp_pnl_pts(tier1가 조기청산 vs 실제 실현 pt 차이): **13.1383 pt** / 승률 81.8%
- tier1 터치 표본 부족 (11 < 20) — 판정 보류
- [제안3 편입, 참고용] edge_ratio(=|기대엣지|/불확실성, n=11, 평균=0.0388) vs 실현 pt 스피어만 상관: **-0.3455** (게이트 아님 — 등급/사이징 강화 여부는 표본이 더 쌓인 뒤 별도 검토)

## [12] qty=1 TP1 이후 트레일 폭 counterfactual (363차 후속, 0721 제안4 편입)

- 이번 실행 resolve: 1건 / 누적 판정 20건 (미판정 0건)
- counterfactual 분포: TRAIL_STOP 20 / FORCE_EXIT 0
- 누적 hyp_pnl_pts(4단계 트레일링 지속 vs 실제 static lock 실현 pt 차이): **-6.6461 pt** / 승률 45.0%

## [13] 등급별 순EV 역전 감시 (366차, 0722 정기점검 딥다이브)

| 등급 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| A | 56 | -71,185 | -3,986,335 | 50.0% | -3,192,244 | 551,265 |
| C | 17 | 14,813 | 251,818 | 47.1% | -444,576 | 249,551 |

> [367차, 제안4 편입] 최대손실·표준편차 보강 — 평균만으로는 "등급 전체가
> 고르게 나쁨"과 "소수 초대형 손실(fat-tail)이 평균을 끌어내림"을 구분할
> 수 없다. 0722 딥다이브: A등급 4주 누적손실의 84%가 [15]에서 관찰하는
> "TP1 도달 전 급행 풀스톱" 9건에 집중돼 있었음 — 표준편차가 크고
> 최대손실이 평균의 여러 배면 이 fat-tail 구조를 의심할 것.
- 등급별 표본 부족 (A=56, C=17, 각각 20 필요) — 판정 보류

## [14] Tier1 잔여계약 2단계 조기청산 counterfactual (367차)

- 이번 실행 resolve: 0건 / 누적 판정 0건 (미판정 0건)
- 누적 hyp_pnl_pts(tier2가 조기청산 vs 실제 잔여계약 실현 pt 차이): **0.0 pt** / 승률 0.0%
- tier2 터치 표본 부족 (0 < 20) — 판정 보류

## [15] 급행 풀스톱(TP1 미도달) 관찰 (367차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: 하드스톱 청산 + 보유시간 ≤ 150초 + 진입~청산 구간에 TP1 관련 로그 없음
- 급행 하드스톱 16건 중 TP1 미도달 15건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 12 | -1,195,728 | 10 |
| C | 3 | -641,029 | 3 |
- 이 채널은 PASS/FAIL을 판정하지 않는다 — 이 패턴 자체를 차단할 정책이
  아직 없어 판정이 무의미하다. GradeEVGuard·loss_tier1_qty1_shadow·
  loss_tier2_remainder_shadow가 다루는 문제의 선행지표로만 참고할 것.

## [16] chase+foreign 조합 관찰 (368차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: [진입체크] 로그에서 `10_chase`·`6_foreign` 두 항목만 동시 실패 (나머지 항목 무관)
- 로그-DB 매칭 70건 중 동시실패 11건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 11 | 167,462 | 6 |
- CHASE_FOREIGN_COMBO_GUARD_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용. P4(CVD+OFI, 268차)와 동일 계열 논리이나 표본이
  작아(368차 등록 시점 n=5) 즉시 정책화하지 않는다 — §9 사전등록 원칙.

## [17] 청산 체결 슬리피지 관찰 (369차, 0723 정기점검, 관찰 전용 — 정책 게이트 아님)

- 관찰 대상: 모든 청산 주문의 의도가(price_hint) vs 실체결가(fill_price)
  (exit_fill_slippage 테이블, main.py::_ts_record_exit_fill_slippage())
- 표본 n=10, 평균 슬리피지 0.009 pt, 최대 0.22 pt (캠페인 가정 0.02 pt/편도)

| 청산사유 | n | 평균 슬리피지(pt) |
|---|---|---|
| 하드스톱(틱) | 6 | 0.0683 |
| TP2(전량) | 4 | -0.08 |
- 계기: 0723 유일 거래에서 TP1 ATR보호전환(+0.35pt 확정 예정)이 체결
  슬리피지로 순손실(-0.02pt)로 뒤집힘. slippage_ticks_per_side(현재 1.0,
  0.02pt)는 캠페인 전 채널의 왕복비용 계산에 쓰이는 공통 가정이므로,
  이 채널의 실측치가 그 가정과 다르더라도 즉시 자동 재보정하지 않는다
  — 바꾸려면 §3 사전등록 원칙에 따라 검증 시계를 리셋해야 한다.

## [18] RegimeExhaustionGate 탈진 반전 counterfactual (379차, 관찰 전용 — 정책 게이트 아님)

- 발동 조건: hurst<0.45(평균회귀) AND 60분 느린 연장폭(price_extension_atr_60m) |값|>1.5ATR AND (10_chase 또는 11_countertrend 소프트 실패)
- 계기: 0723 정기점검 딥다이브 — 진입 직후 반복 반전 패턴 3항. 10_chase(10분 룩백)는 여러 다리에 걸친 느린 탈진을 놓친다는 게 핵심 발견(0723 11:41 SHORT — 직전 10분은 안정, 이전 90분간 -35pt).
- 해석: hyp_pnl_pts는 **신호 방향(추격 방향)대로 갔을 때의 결과** — 다른 섀도 채널과 부호 해석이 반대다. 음수 우세면 탈진 반전 가설 지지.
- 표본: 해결=16건 대기중=0건, 누적 hyp_pnl_pts=-13.3659pt (STOP=6 / TP1=10 / NEITHER=0)
- 평균 60분 연장폭=-3.601pt(ATR배수) 평균 hurst=0.391 (chase실패=16건 / countertrend실패=0건)
- 표본 부족 (16 < 20) — 판정 보류
- REGIME_EXHAUSTION_GATE_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용(목표 min_samples=20, hurst_gate_shadow·open_gap_shadow와 동일 기준) — §9 사전등록 원칙, 즉시 자동 전환 없음.

## [19] ToxicityGate block counterfactual (신설)

- 이번 실행 resolve: 2건 / 누적 판정 2건 (미판정 0건)
- counterfactual 분포: STOP 0 / TP1 2 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **2.8836 pt** / 승률 100.0% (기준선 49.3%)
- 평균 toxicity_score=0.3605 / 평균 toxicity_score_ma=0.3509 (block_threshold 재검토 시 캘리브레이션 근거)
- 차단 표본 부족 (2 < 20) — 판정 보류
- action="reduce"는 실제 축소 체결로 trades에 남으므로 이 채널 대상 아님 — action="block"만 계측(open_gap_shadow와 동일 원칙).

## [20] BAR_ONLY_RELAX 수용/롤백 감시 (402차 후속, 관찰 전용 — 자동 롤백 아님)

- 발효일 **2026-07-30** (401차 커밋이 2026-07-29 장 마감 후라 다음 세션부터 적용)
- 계측일: 완화 전 1일 / 완화 후 2일
- collapse 비율: 기준선 44.8% → 완화 후 — (목표 20%±7%p)

| 일자 | 계측 분봉 | collapse% | 3m 적중 | 5m 적중 | 구분 |
|---|---|---|---|---|---|
| 2026-07-29 | 324 | 44.8% | 33.0% | 25.8% | 완화전 |
| 2026-07-30 | 370 | 24.9% | 37.5% | 30.8% | 완화후 |
| 2026-07-31 | 367 | 22.6% | 45.9% | 29.5% | 완화후 |

- 완화 후 계측일 2일 < 최소 3일 — 판정 보류 (발효 2026-07-30)

> `weight_collapsed`는 398차(2026-07-28 저녁) 배포분부터 기록된다 — 그 이전
> 일자는 컬럼이 NULL이라 "collapse 0건"이 아니라 "미계측"이므로 집계에서
> 제외한다. 완화 전 기준선이 사실상 2026-07-29 단일일이라는 뜻이므로,
> min_days(기본 3거래일) 미만에서는 판정을 보류한다(313차 원칙).
> 롤백은 `config/settings.py:BAR_ONLY_RELAX_ENABLED = False` 1줄로 즉시 가역.
> 일 단위 확인은 `scripts/weight_collapse_monitor.py`.

## [21] 방향별 순EV 감시 (402차 후속5, [13]의 방향 축 미러)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 55건(원본 57행, 부분청산 병합)

| 방향 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| LONG | 25 | 16,138 | 403,461 | 48.0% | -351,370 | 228,868 |
| SHORT | 30 | 12,690 | 380,705 | 50.0% | -359,308 | 207,594 |

> **[13]과 필터가 다르다(의도적)**. [13]은 `grade IN ('A','B','C')`이라
> 구버전 `entry_source=NULL`·`OPERATOR_MANUAL` 행이 포함되지만, 이 채널은
> `SYSTEM_AUTO` 한정이다 — 방향 편향은 시스템 판단의 문제이므로 수동·레거시
> 진입을 섞으면 안 된다. 두 채널의 표본 수가 다른 것은 결함이 아니다.
> 또한 부분청산 행 중복을 진입 1건 단위로 병합한다 — 그대로 세면 TP1/TP2
> 부분청산이 각각 '승리'로 집계돼 승률이 부풀려진다(402차 실제 오류 사례).

## [22] MFE 캡처율 관찰 (402차 후속5, 관찰 전용 — 판정 없음)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 55건(원본 57행 병합)
- 평균 실현 0.397 pt / 보유구간 MFE 3.568 pt / 15:10까지 MFE 22.713 pt
- **풀링 캡처율**(ΣRealized/ΣMFE) 보유구간 11.1% (n=55) / 15:10까지 1.8% (n=55)
- **승리 거래만** 15:10까지 풀링 캡처율 15.8% (n=27)
- **평균 미실현 잔여**(MFE−실현) 보유구간 3.171 pt / 15:10까지 22.316 pt

가장 많이 흘린 5건 (15:10 MFE − 실현):

| 진입 | 방향 | 실현pt | 보유MFE | 15:10MFE | 잔여pt |
|---|---|---|---|---|---|
| 2026-07-29 10:35:38 | SHORT | 9.24 | 12.22 | 120.6 | 111.36 |
| 2026-07-22 09:32:58 | SHORT | -3.6 | 0.84 | 52.76 | 56.36 |
| 2026-07-22 10:04:58 | SHORT | -4.1 | 0.06 | 51.58 | 55.68 |
| 2026-07-22 09:53:58 | SHORT | -3.84 | 2.38 | 47.66 | 51.50 |
| 2026-07-22 09:47:57 | SHORT | -3.18 | 0.86 | 47.2 | 50.38 |

> 이 채널은 **판정하지 않는다**(verdict 항상 OBSERVE). 여기서 나올 결정
> ("청산을 더 늦춰라")은 이미 [12] tp1_trail_shadow가 판정 중이므로, 이
> 수치는 그 판정을 해석할 맥락("캡처율이 이렇게 낮은데도 트레일링이 안
> 낫다"가 성립하는지)만 제공한다. 단일일 극단 사례로 결론 내지 말 것
> (2026-07-29 캡처율 7.7%는 -15.6% 폭락일 1건이다 — 313차 원칙).

---

> 이 리포트는 권고만 출력한다. 정책 적용/롤백은 주간 회의에서 수동 결정하고
> `dev_memory/DECISION_LOG.md`에 기록할 것 (§2 사전등록 원칙, §9 계엄령).