# 검증 캠페인 주간 판정 리포트

- 생성: 2026-08-01 18:30:41  (분석 창 28일, 캠페인 시작 2026-07-05)
- 합격선: `config/settings.py:VALIDATION_CAMPAIGN` (사전 등록 — 변경 금지)
- 근거: `docs/260705_OFFENSE_READINESS_AUDIT_AND_NEXT_PHASE.md` §3
- **운영 모드: 상시(standing)** — 2026-08-01 전환. 4주 기한 없이 계속 생성하며, 채널별로 min_samples 도달 시점에 개별 판정한다. **합격선·판정문은 무변경**(§9-4 — 상시 전환은 거버넌스 결정이지 판정 기준 변경이 아니다).
- 📌 표시가 붙은 채널은 **주간회의에서 확정된 결정이 있다** — 하단 "확정 결정 레지스트리" 참조. 판정(verdict)과 결정은 별개다.

| 채널 | 판정 | 핵심 수치 |
|---|---|---|
| [0] 표본 기아 경보 | ✅ OK | 주간진입=13건(하한 10) 4주투영=52건 |
| [1] Triple-Barrier | ⏳ INSUFFICIENT | 합격 호라이즌 0개 (기준 2개) |
| [2] Meta-Gate | ❌ FAIL | 상위EV=-0.0499 분리도=-0.0809 (필요 0.1457)  📌 **탈락 확정 — 승격 포기** (2026-08-01) |
| [3] 분위 회귀 | ✅ PASS | 커버리지=0.8101 (밴드 [0.72, 0.88]) 상관=0.3274 |
| [3-A] q50 방향 적중률 (관찰) | 👁 OBSERVE | 적중=51.0% (n=3551) 상위30%=50.5% q50양수비율=47.9% |
| [3-B] 분위회귀 TP1 거리 A/B | ❌ FAIL | 현행 초과 대안: q_raw (진입 36건/9일)  📌 **FAIL이지만 미적용 — MW0601 교차확인 선행** (2026-08-01) |
| [4] 신호소멸청산 | ✅ PASS | 누적 saved=12.9656pt (n=13, 보류 0) |
| [5] 레짐 ATR 배수 | ⏳ INSUFFICIENT | mean-revert: n=32 EV=-22,096원 / neutral: n=28 EV=85,917원 / trend: n=17 EV=-16,985원 |
| [6] Hurst 게이트 counterfactual | ❌ FAIL | 누적 hyp=37.3158pt 승률=72.2% (n=173, 보류 0)  📌 **추가 조치 없음 — 권고는 2026-07-15에 이미 이행됨** (2026-08-01) |
| [7] JointGateBlock counterfactual | ✅ PASS | 누적 hyp=-48.4179pt 승률=62.8% (n=78, 보류 0) |
| [8] KellyAdvisedSkip×C등급 | ⏳ INSUFFICIENT | 누적 순PnL=-135,738원 승률=75.0% (n=4) |
| [9] OPEN_VOLATILE 시가이격 counterfactual | ✅ PASS | 누적 hyp=-4.1599pt 승률=66.7% (n=21, 보류 0) |
| [10] TP2 홀드 counterfactual (qty=2 재배분 A/B) | ⏳ INSUFFICIENT | 누적 hyp=0.0pt 승률=0.0% (n=0, 보류 0) TP3=0건 트레일=0건 강제청산=0건 |
| [11] qty=1 손실1차 조기청산 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=7.768pt 승률=66.7% (n=6, 보류 0) |
| [12] qty=1 TP1 이후 트레일 폭 counterfactual | ✅ PASS | 누적 hyp=-3.8309pt 승률=52.9% (n=17, 보류 0) 트레일스톱=17건 강제청산=0건 |
| [13] 등급별 순EV 역전 감시 | ❌ FAIL | A=-9,208원(n=53, 최대손실=-638,449원) C=55,671원(n=21)  📌 **부결 — GradeEVGuard 활성화하지 않음** (2026-08-01) |
| [14] Tier1 잔여계약 2단계 조기청산 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=0.0pt 승률=0.0% (n=0, 보류 0) |
| [15] 급행 풀스톱(TP1 미도달) 관찰 | 👁 OBSERVE | 급행하드스톱=19건 중 TP1미도달=12건 (A: n=11 누적=-1,060,617원) |
| [16] chase+foreign 조합 관찰 | 👁 OBSERVE | 동시실패=11건 누적=2,233,083원 (매칭=74건) |
| [17] 청산 체결 슬리피지 관찰 | 👁 OBSERVE | n=14 평균=0.0379pt (가정 0.02pt) |
| [18] RegimeExhaustionGate(탈진반전) | 🔶 SUPPORTS_GATE | 발동=28건 누적hyp=-1.7521pt (STOP=8/TP1=20/NEITHER=0) |
| [19] ToxicityGate block counterfactual | ⏳ INSUFFICIENT | 누적 hyp=-1.5491pt 승률=75.0% (n=4, 보류 0) |
| [20] BAR_ONLY_RELAX 수용/롤백 | ⏳ INSUFFICIENT | 완화후 collapse=— (기준선 45.0%, 목표 20%±7%p) 계측일 전1/후2 |
| [21] 방향별 순EV (SYSTEM_AUTO) | ⏳ INSUFFICIENT | LONG: n=18 평균=-52,786원 최대손실=-473,373원 / SHORT: n=42 평균=53,745원 최대손실=-523,099원 |
| [22] MFE 캡처율 관찰 | 👁 OBSERVE | 풀링캡처 보유내=18.7% 종가까지=2.6% / 평균잔여 17.329 pt (진입 60건) |
| [23] EOD 모델가드 판정 괴리 | ⏳ INSUFFICIENT | missed_upgrade=— (n=—/—, 1일) |
| [23-B] TP1/손절 초기 기하 A/B | ❌ FAIL | 현행 초과 대안: stop_1.0, sym_1.0_1.0 (진입 60건/12일)  📌 **FAIL이지만 미적용 — 현행 유지** (2026-08-01) |
| [24] TP1 보호전환 반납 관찰 | 👁 OBSERVE | 중앙값 반납=1.0 pt (반납 15 / 달림 8, n=23) |
| [25] TP1 보호전환 offset A/B | ❌ FAIL | 현행 초과 대안: atr_lock_0.75, bar_range (전환 23건/8일)  📌 **FAIL이지만 미적용 — 현행 유지** (2026-08-01) |
| [26] 거래불능(가격상한 고착) 구간 | 👁 OBSERVE | 고착 29분봉 / 1일  · MFE오염 없음 |
| [27] counterfactual 도달불가 목표가 | 👁 OBSERVE | 해당 5건 (hurst_gate_shadow=1, joint_gate_shadow=1, regime_exhaustion_shadow=3) · hyp합 -13.3346 pt — 판정 미반영, 민감도만 |

## [0] 캠페인 표본 기아 경보 + 완화 사다리 (§3-8)

- 주간(7일) 진입 체결: **13건** (하한 10건) → 4주 투영 52건
- **표본 미달 위험 KPI**: Meta-Gate(§3-2, 분위당 30건×3 필요)
- **완화 사다리 상태**: 정상 — 사다리 미적용 상태 유지

| 단계 | 조치 | 상태 |
|---|---|---|
| 1 | 관찰만 — FQAdj 배선 수정(297차)의 자연 회복 효과 확인 |  |
| 2 | 구형 MetaGate take_ceil(C등급) 완화: 0.570 → 0.52 |  |
| 3 | Hurst 횡보 차단 임계값 완화 (최후 수단): 0.45 → 0.40 |  |

> 사다리 적용은 항상 사용자 수동 결정 — 자동 변경 없음. 적용 시 `dev_memory/DECISION_LOG.md`에 기록할 것.

## [1] Triple-Barrier — OOS replay IC vs 3클래스 IC

| 호라이즌 | 판정 | IC_TB | IC_3class | OOS n | 비고 |
|---|---|---|---|---|---|
| 1m | INSUFFICIENT | — | — | — | OOS 표본 0건 (모델 mtime 이후 데이터 대기) |
| 3m | INSUFFICIENT | — | — | 584 | OOS 표본 부족 (584 < 800) — 첫 판정 대기 |
| 5m | INSUFFICIENT | — | — | 346 | OOS 표본 부족 (346 < 800) — 첫 판정 대기 |
| 10m | INSUFFICIENT | — | — | 170 | OOS 표본 부족 (170 < 800) — 첫 판정 대기 |
| 15m | INSUFFICIENT | — | — | 107 | OOS 표본 부족 (107 < 800) — 첫 판정 대기 |
| 30m | INSUFFICIENT | — | — | 50 | OOS 표본 부족 (50 < 800) — 첫 판정 대기 |

> [357차 해석 확정] 1m은 앙상블 가중치 영구 0 퇴역(331차 후속2) 상태 —
> 1m이 IC 기준을 합격해도 "1m 앙상블 복귀"가 아니라 1m 활용방안 A·C
> (331차 후속3, 섀도우 경로)의 근거로만 사용한다. **실질 승격 검토 대상은
> 3m/5m로 한정** (30m은 296차 퇴역). 합격선 자체는 불변 — 해석만 확정
> (시계 리셋 불요).
> [384차] 383차가 규명한 구조결함(평가창이 매주 재학습으로 리셋돼 5m~30m이
> min_samples_hz 영구 미달) 해법 적용 — 이제 호라이즌별 실제 OOS n이
> min_samples_hz에 도달한 주에만 신선하게 판정하고, 그 아래 주는 `tb_verdict_log`의
> 최근 판정을 그대로 유지(위 표의 "(유지, YYYY-MM-DD 판정)")한다. 10m/15m/30m은
> 판정 주기 자체가 몇 주~십수 주 단위로 길 뿐 표본은 끊기지 않고 계속 누적된다.

## [2] Meta-Gate — entry_quality_prob 3분위 순EV (왕복비용 0.0729 pt 차감)

| 분위 | 순EV(pt) | n |
|---|---|---|
| 상위 33% | -0.0499 | 402 |
| 중위 33% | -0.1339 | — |
| 하위 33% | 0.031 | 402 |

## [3] 분위 회귀 — 캘리브레이션

- 표본: 3601건 / 커버리지 0.8101 (합격 밴드 0.72~0.88) / 불확실성-실현폭 상관 0.3274 (하한 0.15)

### [3-A] q50 방향 적중률 (404차 후속10, 관찰 전용 — 판정 없음)

| 구분 | n | 방향 적중률 |
|---|---|---|
| 전체 | 3551 | 51.0% |
| \|q50\| 상위 30% | 1065 | 50.5% |

- q50 > 0 비율: **47.9%** (50%에서 크게 벗어나면 방향 편향)

> **판정하지 않는다**(§3 합격선 무변경). 감사 §3-3은 분위회귀 KPI를 **3종**으로
> 정의했으나(① q50 방향 적중률 ② 폭-실현 상관 ③ 커버리지) 합격선은 ②③만
> 채택했다 — ①은 **사전등록돼 있었는데 한 번도 렌더링되지 않았다**. 그 탓에
> [3] PASS가 "방향을 맞춘다"로 오독될 여지가 있었다. 실제 의미는
> "**불확실성 폭**을 잘 맞춘다"뿐이다.
> 이 표의 목적은 승격 근거가 아니라 그 오독을 차단하는 것이다 — 적중률이
> 50% 근처면 **q50을 방향·사이징에 쓰지 말라**는 뜻이고, [2] Meta-Gate가
> 확신도-성과 역상관으로 탈락한 것과 같은 실패를 예방한다.
> `|q50| 상위 30%` 적중률이 전체와 비슷하면 q50의 **크기**에도 정보가 없다는 뜻.

## [3-B] 분위회귀 기반 TP1 거리 A/B (404차 후속10 신설)

- 진입 후보 60건 → 시뮬 36건 / 거래일 9일
- 제외: 분위결측 24건(2026-07-20 이전 미적재) / ATR결측 0 / 이익방향분위 부호반대 0 / TP과협 0 / 시뮬불가 0

| 변형 | n | TP1 | STOP | 승률 | 누적pt | 현행 대비 | drop-max | 건별 우세 |
|---|---|---|---|---|---|---|---|---|
| current | 36 | 28 | 8 | 77.8% | +6.03 | +0.00 | — | 0/36 |
| q_raw | 36 | 26 | 10 | 72.2% | +15.39 | +9.36 | +7.76 | 25/36 |
| q_x0.7 | 36 | 26 | 10 | 72.2% | -2.10 | -8.13 | -9.07 | 15/36 |
| q_blend | 36 | 26 | 10 | 72.2% | +5.68 | -0.35 | -1.15 | 25/36 |

- **판정: FAIL** — 현행 초과 대안: q_raw

> **이 채널의 판정은 [3] 본채널 verdict에 반영하지 않는다**(§9-4 판정기준 사후
> 변경 금지). [3]의 합격선은 커버리지·불확실성상관 두 개 그대로다.
> 묻는 것: 현행 TP1은 `ATR × 배수`로 **신호 내용과 무관**한데, 분위회귀가 매 분봉
> 계산해 두고도 쓰지 않는 "이익 방향 꼬리까지의 거리"를 쓰면 나은가.
> LONG은 q90, SHORT는 |q10| — 방향별 favorable quantile을 쓴다(SHORT에 q90을
> 쓰면 손실 방향 꼬리를 TP로 삼는 꼴).
> **스톱은 전 변형 고정**(현행 ATR×1.5×hurst) — [23-B] `sym_1.0_1.0`이 TP·스톱을
> 동시에 바꿔 기여 분해가 불가능했던 교란을 제거했다.
> ⚠ 절대값은 실현손익이 아니다(qty=1 보호전환을 'TP1 전량청산'으로 단순화).
> **변형 간 상대비교 전용.**
> ⚠ FAIL이 떠도 즉시 적용 금지 — `drop-max`(최대기여 1건 제거 후 델타)와
> `건별 우세`를 함께 볼 것. [25]는 drop-max에서 부호가 역전돼 무너졌다(372차).
> ⚠ **MW0601 교차확인 필수** — [23-B]가 같은 코드·같은 기간에도 PC간 부호
> 역전을 냈다(tp1_x2: +32.78 vs −19.04). n≈40으로는 기하를 확정할 수 없다(313차).
> ⚠ 변형 간 결과가 **단조롭지 않으면**(예: 0.7배가 1.0배보다 나쁨) 폭 자체보다
> "몇 건이 TP1↔STOP으로 뒤집혔나"가 결과를 지배한다는 뜻이다 — 표의 TP1/STOP
> 건수를 함께 읽을 것.

## [4] 신호소멸청산 counterfactual (§3-5 롤백 기준 ①)

- 이번 실행 resolve: 0건 / 누적 판정 13건 (미판정 0건)
- counterfactual 분포: STOP 6 / TP1 7 / NEITHER 0
- 누적 saved_pts(아낀 pt − 놓친 pt): **12.9656 pt**

## [5] 레짐 조건부 ATR 배수 (§3-5 롤백 기준 ②)

| 버킷 | n | 평균 순EV(원) | 누적(원) | 승률 |
|---|---|---|---|---|
| mean-revert | 32 | -22,096 | -707,058 | 53.1% |
| neutral | 28 | 85,917 | 2,405,682 | 75.0% |
| trend | 17 | -16,985 | -288,738 | 58.8% |

- 버킷별 표본 부족 (trend/neutral 각 20건 필요)

## [6] Hurst 게이트 counterfactual (§3-6, P1-4)

- 이번 실행 resolve: 0건 / 누적 판정 173건 (미판정 0건)
- counterfactual 분포: STOP 48 / TP1 125 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **37.3158 pt** / 승률 72.2% (기준선 62.3%)
- **권고**: Hurst 하드차단 → 사이징 ×0.5로 완화 권고 (즉시 언블록 금지, §3-6)

## [7] JointGateBlock counterfactual (§3-7, 327차)

- 이번 실행 resolve: 0건 / 누적 판정 78건 (미판정 0건)
- counterfactual 분포: STOP 29 / TP1 49 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-48.4179 pt** / 승률 62.8% (기준선 62.3%)
- meta_size 구간별(tox_size 상수 구조 검증용):
  - high(meta≥0.55): n=28 hyp=-20.9093pt 승률=57.1%
  - low(meta<0.55): n=50 hyp=-27.5086pt 승률=66.0%

### MFE 병기 — counterfactual이 얼마나 과소평가하는가 (P1-D)

- 30분 창 MFE 평균 **6.6303 pt**(중앙값 5.35) · MAE 평균 **8.9551 pt** (n=78)
- **MFE>MAE 33건 vs MAE≥MFE 45건** (ΣMFE 517.16 / ΣMAE 698.5 pt)
- counterfactual 포착률 Σhyp/ΣMFE = -9.4% (음수 = TP1 가정의 순손익이 마이너스라는 뜻이지 '비율'로 읽지 말 것)
- 추세형 과소평가 건수(MFE≥5pt 이면서 hyp<MFE의 30%): **40건**

| 시각 | 방향 | MFE(30분) | MAE(30분) | TP1 기준 hyp | cf |
|---|---|---|---|---|---|
| 07-29 10:44 | SHORT | **+38.8** | −1.16 | 3.74 | TP1 |
| 07-27 09:49 | SHORT | **+23.96** | −9.1 | -5.7 | STOP |
| 07-16 10:56 | SHORT | **+17.86** | −0.08 | 2.43 | TP1 |
| 07-31 13:16 | LONG | **+17.72** | −0.12 | 1.01 | TP1 |
| 07-16 10:53 | SHORT | **+15.38** | −6.1 | -5.41 | STOP |

> **계측이지 처방이 아니다.** `hyp_pnl_pts`는 차단 신호를 현행 TP1
> (ATR×0.3~0.5)로 청산했다고 가정하는데, 그 TP1이 너무 좁다는 것이 0731
> 리포트 §2-C의 결론이다 — 즉 counterfactual이 자기 편향적이라 추세일의
> 차단 비용을 구조적으로 과소평가한다. 포착률이 낮을수록 위 "차단이
> 이득" 판정이 TP1 가정에 크게 기대고 있다는 뜻이다.
>
> ⚠ 이 수치로 **TP를 넓히자는 결론을 내면 안 된다** — §2-E가 차단 19건에
> 대칭 TP(1:1)를 직접 적용해 −9.87pt(현행 +4.92pt)로 **이미 기각**했다.
> 이기는 거래가 더 버는 만큼 지는 거래도 커진다. MFE는 "차단 판정이
> 어떤 가정 위에 서 있는지"를 드러낼 뿐이다.
>
> ⚠ **MFE만 보면 정반대로 읽힌다 — MAE를 반드시 함께 볼 것.** 이 표본에서
> MAE 평균이 MFE 평균보다 **크다**. 차단된 신호들은 유리하게 간 폭보다
> 불리하게 간 폭이 더 컸다는 뜻이고, 그건 차단이 옳았던 쪽 증거다.
> "추세일 차단 비용 과소평가"는 개별 추세 건에서는 사실이지만 표본
> 전체로는 반대 방향 증거가 더 크다.
>
> ⚠ **MFE/MAE는 순서를 모른다.** 위 07-27 09:49 SHORT처럼 MFE +23.96인데
> cf=STOP인 건은, 스톱이 먼저 맞은 뒤에 유리하게 갔다는 뜻일 수 있다.
> "이만큼 벌 수 있었다"의 상한이지 실현 가능한 값이 아니다.

## [8] KellyAdvisedSkip × C등급 누적 성과 (341차 신설)

- C등급+KellySkip 체결 n=4 | 누적 순PnL=-135,738원 | 평균=-33,934원 | 승률=75.0%
- 비교(C등급, KellySkip 아님) n=17 | 평균=76,755원 | 승률=76.5%
- 등급별(KellySkip=1 전체, 참고용):
  - A급: n=2 누적PnL=59,597원 승률=50.0%
  - C급: n=4 누적PnL=-135,738원 승률=75.0%
- C등급+KellySkip 표본 부족 (4 < 20) — 판정 보류

## [9] OPEN_VOLATILE 시가이격 counterfactual (§14, 354차)

- 이번 실행 resolve: 0건 / 누적 판정 21건 (미판정 0건)
- counterfactual 분포: STOP 7 / TP1 14 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-4.1599 pt** / 승률 66.7% (기준선 62.3%)
- 평균 gap_pt=26.56 / 평균 atr_at_block=3.2 (기준점 재설계 시 캘리브레이션 근거)

## [11] qty=1 손실1차(Loss Tier1) 조기청산 counterfactual (363차)

- 이번 실행 resolve: 0건 / 누적 판정 6건 (미판정 0건)
- 누적 hyp_pnl_pts(tier1가 조기청산 vs 실제 실현 pt 차이): **7.768 pt** / 승률 66.7%
- tier1 터치 표본 부족 (6 < 20) — 판정 보류
- [제안3 편입] edge_ratio 표본 6건 — 상관 계산 최소치(10건) 미달, 축적 대기

## [12] qty=1 TP1 이후 트레일 폭 counterfactual (363차 후속, 0721 제안4 편입)

- 이번 실행 resolve: 0건 / 누적 판정 17건 (미판정 0건)
- counterfactual 분포: TRAIL_STOP 17 / FORCE_EXIT 0
- 누적 hyp_pnl_pts(4단계 트레일링 지속 vs 실제 static lock 실현 pt 차이): **-3.8309 pt** / 승률 52.9%

## [13] 등급별 순EV 역전 감시 (366차, 0722 정기점검 딥다이브)

| 등급 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| A | 53 | -9,208 | -488,009 | 56.6% | -638,449 | 242,075 |
| C | 21 | 55,671 | 1,169,099 | 76.2% | -210,640 | 162,283 |

> [367차, 제안4 편입] 최대손실·표준편차 보강 — 평균만으로는 "등급 전체가
> 고르게 나쁨"과 "소수 초대형 손실(fat-tail)이 평균을 끌어내림"을 구분할
> 수 없다. 0722 딥다이브: A등급 4주 누적손실의 84%가 [15]에서 관찰하는
> "TP1 도달 전 급행 풀스톱" 9건에 집중돼 있었음 — 표준편차가 크고
> 최대손실이 평균의 여러 배면 이 fat-tail 구조를 의심할 것.
- **권고**: A등급 누적 순EV 음수 확정(C등급은 양수) — GradeEVGuard (config.settings.GRADE_EV_GUARD_ENABLED) 활성화를 주간회의에서 검토 (§9 사전등록 원칙에 따라 적용은 수동 결정)

## [14] Tier1 잔여계약 2단계 조기청산 counterfactual (367차)

- 이번 실행 resolve: 0건 / 누적 판정 0건 (미판정 0건)
- 누적 hyp_pnl_pts(tier2가 조기청산 vs 실제 잔여계약 실현 pt 차이): **0.0 pt** / 승률 0.0%
- tier2 터치 표본 부족 (0 < 20) — 판정 보류

## [15] 급행 풀스톱(TP1 미도달) 관찰 (367차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: 하드스톱 청산 + 보유시간 ≤ 150초 + 진입~청산 구간에 TP1 관련 로그 없음
- 급행 하드스톱 19건 중 TP1 미도달 12건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 11 | -1,060,617 | 8 |
| C | 1 | -210,640 | 1 |
- 이 채널은 PASS/FAIL을 판정하지 않는다 — 이 패턴 자체를 차단할 정책이
  아직 없어 판정이 무의미하다. GradeEVGuard·loss_tier1_qty1_shadow·
  loss_tier2_remainder_shadow가 다루는 문제의 선행지표로만 참고할 것.

## [16] chase+foreign 조합 관찰 (368차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: [진입체크] 로그에서 `10_chase`·`6_foreign` 두 항목만 동시 실패 (나머지 항목 무관)
- 로그-DB 매칭 74건 중 동시실패 11건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 10 | 1,975,686 | 2 |
| C | 1 | 257,397 | 0 |
- CHASE_FOREIGN_COMBO_GUARD_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용. P4(CVD+OFI, 268차)와 동일 계열 논리이나 표본이
  작아(368차 등록 시점 n=5) 즉시 정책화하지 않는다 — §9 사전등록 원칙.

## [17] 청산 체결 슬리피지 관찰 (369차, 0723 정기점검, 관찰 전용 — 정책 게이트 아님)

- 관찰 대상: 모든 청산 주문의 의도가(price_hint) vs 실체결가(fill_price)
  (exit_fill_slippage 테이블, main.py::_ts_record_exit_fill_slippage())
- 표본 n=14, 평균 슬리피지 0.0379 pt, 최대 0.42 pt (캠페인 가정 0.02 pt/편도)

| 청산사유 | n | 평균 슬리피지(pt) |
|---|---|---|
| 하드스톱(틱) | 9 | 0.0856 |
| TP2(전량) | 4 | -0.1 |
| TP1 부분청산 33% | 1 | 0.16 |
- 계기: 0723 유일 거래에서 TP1 ATR보호전환(+0.35pt 확정 예정)이 체결
  슬리피지로 순손실(-0.02pt)로 뒤집힘. slippage_ticks_per_side(현재 1.0,
  0.02pt)는 캠페인 전 채널의 왕복비용 계산에 쓰이는 공통 가정이므로,
  이 채널의 실측치가 그 가정과 다르더라도 즉시 자동 재보정하지 않는다
  — 바꾸려면 §3 사전등록 원칙에 따라 검증 시계를 리셋해야 한다.

## [18] RegimeExhaustionGate 탈진 반전 counterfactual (379차, 관찰 전용 — 정책 게이트 아님)

- 발동 조건: hurst<0.45(평균회귀) AND 60분 느린 연장폭(price_extension_atr_60m) |값|>1.5ATR AND (10_chase 또는 11_countertrend 소프트 실패)
- 계기: 0723 정기점검 딥다이브 — 진입 직후 반복 반전 패턴 3항. 10_chase(10분 룩백)는 여러 다리에 걸친 느린 탈진을 놓친다는 게 핵심 발견(0723 11:41 SHORT — 직전 10분은 안정, 이전 90분간 -35pt).
- 해석: hyp_pnl_pts는 **신호 방향(추격 방향)대로 갔을 때의 결과** — 다른 섀도 채널과 부호 해석이 반대다. 음수 우세면 탈진 반전 가설 지지.
- 표본: 해결=28건 대기중=0건, 누적 hyp_pnl_pts=-1.7521pt (STOP=8 / TP1=20 / NEITHER=0)
- 평균 60분 연장폭=1.838pt(ATR배수) 평균 hurst=0.424 (chase실패=28건 / countertrend실패=0건)
- **탈진 반전 가설 지지 — REGIME_EXHAUSTION_GATE_ENABLED 전환(등급 강등) 또는 반대방향 신규 진입 시그널(3-2 제안) 개발을 주간회의에서 검토 (§9 사전등록 원칙 — 즉시 자동 전환 금지)**
- REGIME_EXHAUSTION_GATE_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용(목표 min_samples=20, hurst_gate_shadow·open_gap_shadow와 동일 기준) — §9 사전등록 원칙, 즉시 자동 전환 없음.

## [19] ToxicityGate block counterfactual (신설)

- 이번 실행 resolve: 0건 / 누적 판정 4건 (미판정 0건)
- counterfactual 분포: STOP 1 / TP1 3 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-1.5491 pt** / 승률 75.0% (기준선 62.3%)
- 평균 toxicity_score=0.374 / 평균 toxicity_score_ma=0.4581 (block_threshold 재검토 시 캘리브레이션 근거)
- 차단 표본 부족 (4 < 20) — 판정 보류
- action="reduce"는 실제 축소 체결로 trades에 남으므로 이 채널 대상 아님 — action="block"만 계측(open_gap_shadow와 동일 원칙).

## [20] BAR_ONLY_RELAX 수용/롤백 감시 (402차 후속, 관찰 전용 — 자동 롤백 아님)

- 발효일 **2026-07-30** (401차 커밋이 2026-07-29 장 마감 후라 다음 세션부터 적용)
- 계측일: 완화 전 1일 / 완화 후 2일
- collapse 비율: 기준선 45.0% → 완화 후 — (목표 20%±7%p)

| 일자 | 계측 분봉 | collapse% | 3m 적중 | 5m 적중 | 구분 |
|---|---|---|---|---|---|
| 2026-07-29 | 329 | 45.0% | 41.1% | 33.3% | 완화전 |
| 2026-07-30 | 370 | 21.1% | 30.2% | 27.4% | 완화후 |
| 2026-07-31 | 367 | 21.5% | 44.6% | 33.8% | 완화후 |

- 완화 후 계측일 2일 < 최소 3일 — 판정 보류 (발효 2026-07-30)

> `weight_collapsed`는 398차(2026-07-28 저녁) 배포분부터 기록된다 — 그 이전
> 일자는 컬럼이 NULL이라 "collapse 0건"이 아니라 "미계측"이므로 집계에서
> 제외한다. 완화 전 기준선이 사실상 2026-07-29 단일일이라는 뜻이므로,
> min_days(기본 3거래일) 미만에서는 판정을 보류한다(313차 원칙).
> 롤백은 `config/settings.py:BAR_ONLY_RELAX_ENABLED = False` 1줄로 즉시 가역.
> 일 단위 확인은 `scripts/weight_collapse_monitor.py`.

## [21] 방향별 순EV 감시 (402차 후속5, [13]의 방향 축 미러)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 60건(원본 65행, 부분청산 병합)

| 방향 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| LONG | 18 | -52,786 | -950,143 | 55.6% | -473,373 | 173,738 |
| SHORT | 42 | 53,745 | 2,257,300 | 66.7% | -523,099 | 236,797 |

- 방향별 표본 부족 (LONG 18 / SHORT 42, 각 20 필요) — 판정 보류

> **[13]과 필터가 다르다(의도적)**. [13]은 `grade IN ('A','B','C')`이라
> 구버전 `entry_source=NULL`·`OPERATOR_MANUAL` 행이 포함되지만, 이 채널은
> `SYSTEM_AUTO` 한정이다 — 방향 편향은 시스템 판단의 문제이므로 수동·레거시
> 진입을 섞으면 안 된다. 두 채널의 표본 수가 다른 것은 결함이 아니다.
> 또한 부분청산 행 중복을 진입 1건 단위로 병합한다 — 그대로 세면 TP1/TP2
> 부분청산이 각각 '승리'로 집계돼 승률이 부풀려진다(402차 실제 오류 사례).

## [22] MFE 캡처율 관찰 (402차 후속5, 관찰 전용 — 판정 없음)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 60건(원본 65행 병합)
- 평균 실현 0.456 pt / 보유구간 MFE 3.449 pt / 15:10까지 MFE 17.786 pt
- **풀링 캡처율**(ΣRealized/ΣMFE) 보유구간 18.7% (n=58) / 15:10까지 2.6% (n=60)
- **승리 거래만** 15:10까지 풀링 캡처율 12.3% (n=38)
- **평균 미실현 잔여**(MFE−실현) 보유구간 2.899 pt / 15:10까지 17.329 pt

가장 많이 흘린 5건 (15:10 MFE − 실현):

| 진입 | 방향 | 실현pt | 보유MFE | 15:10MFE | 잔여pt |
|---|---|---|---|---|---|
| 2026-07-29 10:38:46 | SHORT | 9.36 | 12.34 | 120.72 | 111.36 |
| 2026-07-29 10:46:45 | SHORT | 12.18 | 12.96 | 98.46 | 86.28 |
| 2026-07-22 11:19:57 | SHORT | 0.24 | 1.64 | 54.86 | 54.62 |
| 2026-07-22 11:30:56 | SHORT | -2.78 | 1.62 | 51.78 | 54.56 |
| 2026-07-22 10:41:56 | SHORT | 0.0 | 3.2 | 51.56 | 51.56 |

> 이 채널은 **판정하지 않는다**(verdict 항상 OBSERVE). 여기서 나올 결정
> ("청산을 더 늦춰라")은 이미 [12] tp1_trail_shadow가 판정 중이므로, 이
> 수치는 그 판정을 해석할 맥락("캡처율이 이렇게 낮은데도 트레일링이 안
> 낫다"가 성립하는지)만 제공한다. 단일일 극단 사례로 결론 내지 말 것
> (2026-07-29 캡처율 7.7%는 -15.6% 폭락일 1건이다 — 313차 원칙).

## [23] EOD 모델가드 판정 괴리 감시 (404차 신설)

- 표본 부족 (6건/1일 < 18건/3일)

> **판정 기준**(관측 전 고정, §9): missed_upgrade_rate ≥ 30% → FAIL(판정기준을 old_acc_live로 교체할지 주간회의 검토), 미만 → PASS(acc.txt 유지).
> 07-31 최초 라이브 관측(6개 호라이즌 중 3개 불일치)이 이 채널을 만든 계기이나,
> 임계값은 그 단일일 관측치에 맞추지 않고 독립적으로 고정했다 — 이 리포트가
> 그 계기가 된 날의 데이터를 포함하더라도 임계값 자체는 사후 조정이 아니다.
> (근거: `dev_memory/DECISION_LOG.md` 404차 항목, 313차·§9 원칙)

### [23-부속] intraday 계측 CV 관찰 (404차 후속, 관찰 전용 — 판정 없음)

- 표본 12건 / 1거래일

| 호라이즌 | n | 평균 cv_acc | σ(cv_acc) | 평균 왜곡 | fair_would_hold |
|---|---|---|---|---|---|
| 10m | 2 | 0.3733 | 0.0184 | -0.0822 | 100% |
| 15m | 2 | 0.3549 | 0.0621 | -0.1745 | 100% |
| 1m | 2 | 0.3412 | 0.0060 | -0.1611 | 100% |
| 30m | 2 | 0.4719 | 0.0681 | -0.2882 | 100% |
| 3m | 2 | 0.4027 | 0.0135 | -0.0802 | 100% |
| 5m | 2 | 0.3434 | 0.0235 | -0.0757 | 100% |

> **판정하지 않는다**(verdict 항상 OBSERVE). 실측(404차 후속 §1): 동일 데이터·
> 시드만 다른 재현 분산이 5m 기준 8.83%p로 EOD 가드 허용폭(2.5%p)의 3.5배 —
> 이 표의 σ(cv_acc)가 크게 나오는 것은 결함이 아니라 그 잡음이 실측되는 것이다.
> `fair_would_hold`가 높다고 즉시 intraday 가드를 도입하지 말 것 — 표본이
> 충분히(수 주) 쌓여 잡음이 아닌 추세인지 확인한 뒤 사람이 판단한다(§9).

## [23-B] TP1/손절 초기 기하 A/B (403차 P1-6, 404차 후속3 리포트 편입)

- 진입 60건 (ATR 결측 제외 0건) / 거래일 12일

| 변형 | n | TP1 | STOP | 승률 | 누적pt | 현행 대비 |
|---|---|---|---|---|---|---|
| current | 60 | 44 | 16 | 73.3% | +3.64 | +0.00 |
| stop_1.0 | 60 | 39 | 21 | 65.0% | +4.17 | +0.53 |
| tp1_x2 | 60 | 24 | 36 | 40.0% | -15.40 | -19.04 |
| sym_1.0_1.0 | 60 | 33 | 27 | 55.0% | +5.02 | +1.38 |

- **판정: FAIL** — 현행 초과 대안: stop_1.0, sym_1.0_1.0

> 종전에는 `scripts/tp1_geometry_shadow.py`를 따로 실행해야만 보여 주간회의에
> 노출되지 않았다(403차 신설 이후). 404차 후속3에서 계산부를 `compute()`/
> `summarize()`로 추출해 이 리포트가 직접 호출한다 — 판정 기준·로직 무변경.
> ⚠ `current`의 절대값은 실현손익이 아니다(qty=1 보호전환을 'TP1 전량청산'으로
> 단순화). **변형 간 상대비교 전용.**
> ⚠ 이 채널은 MW0601에서 `tp1_x2` **+32.78pt**(현행 초과=FAIL 방향)가 나왔으나
> MW0602에서는 **−19.04pt**(PASS 방향)로 **부호가 뒤집힌다.** 두 PC의 거래집합이
> 달라서이며(protect mode 무관 — 이 시뮬은 protect mode를 쓰지 않는다), n≈60·12일
> 로는 기하를 결정할 수 없다는 뜻이다(313차).

## [24] TP1 보호전환 반납 관찰 (404차 후속3, 관찰 전용 — 판정 없음)

- 보호전환 23건 / 8거래일 (모드 분포: atr_profit=23)
- **반납 15건 / 더 달림 8건**
- TP1 장부이익 평균 2.6365 pt / 중앙값 2.24 pt   |   평균 보호폭 0.6164 pt
- **반납 중앙값 1.0 pt** (평균 0.2113 pt) → 중앙값 기준 반납률 45%
- 보호폭 vs 반납 상관계수 **-0.295** (음수 = 좁은 보호폭일수록 더 반납)

> **판정하지 않는다**(verdict 항상 OBSERVE). 처방(offset을 얼마로 할지)은 [25]가 맡는다.
> **평균이 아니라 중앙값을 볼 것** — 0729 폭락일 2건이 평균을 5배 끌어올려
> 평균 반납은 무해해 보이는데 중앙값은 그 몇 배다. 두 수치가 정반대 인상을
> 주는 전형적 사례이므로 평균만 인용하지 말 것(372차 원칙).
> 소스(`synthetic_partial_exits`)는 339차부터 쌓였으나 404차 후속3까지 **캠페인
> 소비처가 없어 방치**돼 있었다 — 402차 후속3 `toxicity_block_shadow`와 같은 계열.

## [26] 거래불능(가격상한 고착) 구간 (404차 후속5, 관찰 전용 — 판정 없음)

- 고착 **29분봉** / 1일 (세션 분봉 6886개 중)

| 일자 | 방향 | 가격 | 고착분봉 | 구간 | 결측분봉 | 극단 유동터치 | 최대 유동vol |
|---|---|---|---|---|---|---|---|
| 2026-07-31 | UP | 1036.28 | 29 | 14:21~15:06 | 17 | **13** | 642 |

> **핵심 열은 '극단 유동터치'다.** 이 값이 0보다 크면 그 극단을 유동 분봉이
> 이미 만들었다는 뜻이고, 고착 분봉을 전부 지워도 **MFE는 변하지 않는다**
> (max 연산이라 중복 무해). 0731 리포트 §1-C 이상점 3이 제기한 "MFE·캡처율
> 오염" 가설은 이 지표로 **기각**된다 — 07-31 고착 29분봉이 있었지만 1036.28을
> 유동 분봉 13개(최대 vol 642)가 이미 터치했고, 리포트 전문 before/after diff에서
> 실제로 단 한 글자도 바뀌지 않았다.
>
> 이 값이 **0인 날이 나오면 그때는 진짜 오염**이다(갭 상한가 직행 등).
> 진짜 오염은 목표가 쪽이며 [27]이 계측한다.

## [27] counterfactual 도달불가 목표가 (404차 후속5, 관찰 전용 — 판정 없음)

- 해당 행 **5건** (hurst_gate_shadow=1, joint_gate_shadow=1, regime_exhaustion_shadow=3) · 합계 -13.3346 pt

| 테이블 | 시각 | 방향 | 진입가 | 목표가 | 그날 상한 | 결과 | hyp pnl |
|---|---|---|---|---|---|---|---|
| hurst_gate_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |
| joint_gate_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |
| regime_exhaustion_shadow | 10:05 | LONG | 1036.26 | 1037.4020175 | 1036.28 | STOP | -3.4261 |
| regime_exhaustion_shadow | 10:09 | LONG | 1035.98 | 1036.9168275 | 1036.28 | STOP | -2.8105 |
| regime_exhaustion_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |

**민감도 — 이 행들을 뺐다면 (참고용, 실제 판정에는 미반영):**

| 채널 | n | 제외 | 현행 누적 hyp | 제외 시 | 차이 |
|---|---|---|---|---|---|
| hurst_gate_shadow | 173 | 1 | 37.3158 | 39.6818 | +2.3660 |
| joint_gate_shadow | 78 | 1 | -48.4179 | -46.0519 | +2.3660 |
| regime_exhaustion_shadow | 28 | 3 | -1.7521 | 6.8505 | +8.6026 |

> **이 채널은 판정을 바꾸지 않는다.** 초안에서는 "이길 수 없는 가상거래"로 보고
> 자동 제외하도록 짰다가 되돌렸다 — 전제가 틀렸다. 07-31 14:17 시장은 유동적이었고
> (vol 109) 실제로 진입했다면 체결됐을 것이며, TP1이 상한 밖이라 정말로 스톱만
> 맞았을 것이다. counterfactual은 모델링 결함이 아니라 **나쁜 거래를 충실히
> 시뮬레이션**한 것이고, 게이트의 손실 회피는 진짜다.
>
> 남는 질문은 측정 오류가 아니라 **공로의 출처**다 — 게이트가 자기 로직으로 막은
> 것인지, 신호가 우연히 가격상한에서 나와 구조적으로 질 수밖에 없었던 것인지.
> "옳았지만 이유는 달랐다"는 해석 문제라 판정을 조용히 바꾸지 않고 민감도만
> 병기해 주간회의에 올린다(§9).
>
> ⚠ **[18] RegimeExhaustionGate는 3건에 판정이 뒤집힌다**(SUPPORTS→REJECTS,
> 누적 hyp −1.75 → +6.85). 표본 3건이 권고를 뒤집는다는 사실 자체가 그 채널
> 결론의 근거가 얼마나 얇은지를 보여준다(372차 이상치 분해와 같은 교훈).

## [25] TP1 보호전환 offset A/B (404차 후속3 신설)

- 보호전환 23건 (제외 0건) / 거래일 8일

| 변형 | n | STOP | TP2 | 승률 | 누적pt | 중앙값 | 현행 대비 | 건별 우세 |
|---|---|---|---|---|---|---|---|---|
| current | 23 | 8 | 15 | 100.0% | +64.19 | +1.948 | +0.00 | 0/23 |
| breakeven | 23 | 8 | 15 | 65.2% | +60.35 | +1.948 | -3.84 | 0/23 |
| breakeven_plus | 23 | 8 | 15 | 100.0% | +61.95 | +1.948 | -2.24 | 0/23 |
| atr_lock_0.50 | 23 | 12 | 11 | 100.0% | +61.89 | +1.274 | -2.30 | 8/23 |
| atr_lock_0.75 | 23 | 13 | 10 | 100.0% | +65.11 | +1.679 | +0.92 | 8/23 |
| bar_range | 23 | 12 | 11 | 100.0% | +65.01 | +1.366 | +0.81 | 7/23 |

- **판정: FAIL** — 현행 초과 대안: atr_lock_0.75, bar_range

> ⚠ **사전등록 정직성 고지**: `breakeven` 변형은 이 채널 신설 **전에** 404차
> 후속3 조사에서 이미 1회 측정됐다(현행이 22/23 우세) — 재확인용이지 사전등록된
> 검증이 아니다. 사전등록 가치는 `atr_lock_0.50/0.75`·`bar_range`에 있다.
> ⚠ **FAIL이 떠도 즉시 적용 금지** — 372차 이상치 분해상 현행 초과 대안들은
> **최대 기여 1건만 빼면 부호가 역전**된다(atr_lock_0.75 +0.92→−1.33pt,
> bar_range +0.81→−0.29pt). 건별 우세도 8/23·7/23으로 소수이고 중앙값 차이는
> 0.000pt다. 표본이 더 쌓일 때까지 **현행 유지가 합리적**이다.
> ⚠ [12] tp1_trail_shadow가 기각한 "TP1 **이후** 트레일 폭"과 다른 질문이다
> — 이건 TP1 **시점**의 초기 보호 offset이다.

---

## 확정 결정 레지스트리 (주간회의 수동 결정 이력)

### `grade_ev_inversion` — 부결 — GradeEVGuard 활성화하지 않음 *(2026-08-01)*

A등급 누적 −488,009원에서 [15] 급행 풀스톱(TP1 미도달·보유 ≤150초) 11건 −1,060,617원을 제외하면 나머지 42건은 +572,608원(평균 +13,633원)이다. 부분집합 관계는 [15] C등급 1건 −210,640원이 [13] C등급 최대손실과 정확히 일치하는 것으로 확인된다. 즉 등급 문제가 아니라 급행 풀스톱이라는 별개 실패 모드이며, A등급 전체를 강등하는 GradeEVGuard는 대상 오조준이다.

### `hurst_gate_shadow` — 추가 조치 없음 — 권고는 2026-07-15에 이미 이행됨 *(2026-08-01)*

리포트가 찍는 '하드차단 → 사이징 ×0.5 완화' 권고는 333차 후속(2026-07-15)에 이미 배포돼 라이브 중이다(HURST_SOFT_BLOCK_ENABLED=True, main.py:7298). FAIL이 유지되는 것은 미조치가 아니라, 완화가 MINI_MIN_CONTRACTS=1 하한에서 실측 91%(45건 중 41건) no-op이기 때문이다. 사이징 축 처방은 더 추구하지 않고 청산 '거리' 축([3-A]·[3-B])으로 선회했다.

### `meta_gate` — 탈락 확정 — 승격 포기 *(2026-08-01)*

상위분위 순EV −0.0499pt < 하위분위 +0.031pt로 분리도 −0.0809(필요 +0.1457). 부호가 반대이고 분위당 n=402로 표본 핑계가 불가하다. 감사 §5 활성화 순서 2순위(Meta-gate 사이징)를 공식 삭제하고 entry_quality_prob 재설계로 이관한다.

### `quantile_tp_shadow` — FAIL이지만 미적용 — MW0601 교차확인 선행 *(2026-08-01)*

q_raw는 drop-max를 견딘 첫 대안이다(+9.36 → +7.76, 건별우세 25/36). 그러나 결과가 단조롭지 않다 — q_x0.7이 현행보다도 나쁘다. 폭 자체가 아니라 '몇 건이 TP1↔STOP으로 뒤집히나'가 결과를 지배하며 n=36에서 그 2건은 얇다. [23-B]의 PC간 부호 역전 전례가 있어 MW0601 교차확인 전에는 판단 보류.

### `tp1_geometry_shadow` — FAIL이지만 미적용 — 현행 유지 *(2026-08-01)*

MW0601에서 tp1_x2가 +32.78pt(현행 초과), MW0602에서 −19.04pt로 **PC간 부호가 역전**된다. 같은 코드·같은 기간인데 거래집합만 달라 결론이 뒤집히므로 n≈60·12일로는 기하를 결정할 수 없다(313차).

### `tp1_protect_offset_shadow` — FAIL이지만 미적용 — 현행 유지 *(2026-08-01)*

현행 초과 대안들이 **최대 기여 1건만 빼면 부호가 역전**된다(atr_lock_0.75 +0.92→−1.33pt, bar_range +0.81→−0.29pt). 건별 우세도 8/23·7/23으로 소수이고 중앙값 차이는 0.000pt다(372차 이상치 분해).

> **판정(verdict)과 결정은 별개다.** 판정은 사전등록 기준으로 매주 자동
> 재계산되므로, 사람이 "보고 나서 일부러 적용하지 않기로" 한 채널도 FAIL이
> 계속 뜬다. 그 FAIL을 미조치로 오독하지 말 것 — 위 표에 결정이 있으면 이미
> 검토가 끝난 것이고, 뒤집으려면 새 근거가 필요하다.
> 반대 방향의 사고도 실제로 있었다: [6] Hurst 완화 권고는 2026-07-15에 이미
> 배포됐는데 리포트가 3주째 같은 권고를 찍어, 0801 결산 초안이 그것을 신규
> 승인 안건으로 잘못 올렸다(코드 확인 후 철회). 이 레지스트리가 그 재발 방지책이다.
> 출처: `config/settings.py:VALIDATION_CAMPAIGN_DECISIONS`. 결정 변경 시
> 그쪽을 갱신하고 `dev_memory/DECISION_LOG.md`에도 기록할 것(§9).

---

> 이 리포트는 권고만 출력한다. 정책 적용/롤백은 주간 회의에서 수동 결정하고
> `dev_memory/DECISION_LOG.md`에 기록할 것 (§2 사전등록 원칙, §9 계엄령).