# 검증 캠페인 주간 판정 리포트

- 생성: 2026-08-07 17:15:21  (분석 창 28일, 캠페인 시작 2026-07-05)
- 합격선: `config/settings.py:VALIDATION_CAMPAIGN` (사전 등록 — 변경 금지)
- 근거: `docs/260705_OFFENSE_READINESS_AUDIT_AND_NEXT_PHASE.md` §3
- **운영 모드: 상시(standing)** — 2026-08-01 전환. 4주 기한 없이 계속 생성하며, 채널별로 min_samples 도달 시점에 개별 판정한다. **합격선·판정문은 무변경**(§9-4 — 상시 전환은 거버넌스 결정이지 판정 기준 변경이 아니다).
- 📌 표시가 붙은 채널은 **주간회의에서 확정된 결정이 있다** — 하단 "확정 결정 레지스트리" 참조. 판정(verdict)과 결정은 별개다.

> ⚠ **conf 스케일 불연속 — 2026-07-31 (앙상블 보정기 미적용(passthrough) 전환)**
> 이 창은 경계를 걸친다. `ensemble_decisions.confidence`의 **산출 경로가 달라졌으므로 경계를 넘는 수준 비교는 무효**다.
> 원인: 403차 축퇴 가드·도달불가 폴백 배포(827bd04·e594cee, 2026-07-31)
> 실측: 보정 미적용률 07-29 0.9% / 07-30 2.7% / 07-31 30.8% / 08-03 92.2% / 08-04 98.6%  ·  평균 conf 0.316→0.491(+55%)  ·  confidence_raw는 0.491→0.515로 거의 무변화
> raw conf의 1m 적중 순위 AUC=0.489(<0.5, 역방향)이므로 상승은 정보량 증가가 아니다. 427차 [39] REJECTS_HYP와 모순되지 않는다.
> 일자단위·층화 지표는 이 수준 이동에 면역이다 — **그쪽을 보라.**

| 채널 | 판정 | 핵심 수치 |
|---|---|---|
| [0] 표본 기아 경보 | ✅ OK | 주간진입=95건(하한 10) 4주투영=380건 |
| [1] Triple-Barrier | ❌ FAIL | 합격 호라이즌 0개 (기준 2개) |
| [2] Meta-Gate | ❌ FAIL | 상위EV=0.0003 분리도=0.0068 (필요 0.1421)  📌 **탈락 확정 — 승격 포기** (2026-08-01) |
| [3] 분위 회귀 | ✅ PASS | 커버리지=0.8064 (밴드 [0.72, 0.88]) 상관=0.3507 |
| [3-A] q50 방향 적중률 (관찰) | 👁 OBSERVE | 적중=50.9% (n=5383) 상위30%=50.9% q50양수비율=43.3% |
| [3-B] 분위회귀 TP1 거리 A/B | ⏸ SUSPENDED(계측 무효) | 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `FAIL`: 현행 초과 대안: q_raw (진입 125건/14일)  📌 **FAIL이지만 미적용 — MW0601 교차확인 선행** (2026-08-01) |
| [4] 신호소멸청산 | ✅ PASS | 누적 saved=10.9618pt (n=16, 보류 0)  📌 **판정보류 — PC간 부호 역전 (어느 쪽도 단일 근거 불가)** (2026-08-02) |
| [5] 레짐 ATR 배수 | ✅ PASS | mean-revert: n=91 EV=-25,100원 / neutral: n=52 EV=40,728원 / trend: n=29 EV=36,297원 |
| [6] Hurst 게이트 counterfactual | ✅ PASS | 누적 hyp=-1.8072pt 승률=70.3% (n=286, 보류 0)  📌 **추가 조치 없음 — 권고는 2026-07-15에 이미 이행됨** (2026-08-01) `[1계약·TP1상한·미실현 시뮬]` |
| [7] JointGateBlock counterfactual | ✅ PASS | 누적 hyp=-24.4284pt 승률=70.0% (n=80, 보류 0) · ⚠증거없음(t=-0.762) · 단일일취약 `[1계약·TP1상한·미실현 시뮬]` |
| [8] KellyAdvisedSkip×C등급 | ❌ FAIL | 누적 순PnL=-878,357원 승률=63.3% (n=30) |
| [9] OPEN_VOLATILE 시가이격 counterfactual | ✅ PASS | 누적 hyp=-11.6572pt 승률=65.5% (n=29, 보류 0) `[1계약·TP1상한·미실현 시뮬]` |
| [10] TP2 홀드 counterfactual (qty=2 재배분 A/B) | ⏳ INSUFFICIENT | 누적 hyp=0.0pt 승률=0.0% (n=0, 보류 0) TP3=0건 트레일=0건 강제청산=0건 `[1계약·TP1상한·미실현 시뮬]` |
| [11] qty=1 손실1차 조기청산 counterfactual | ✅ PASS | 누적 hyp=5.8248pt 승률=67.4% (n=43/8일, 보류 0) 일자 p=0.2891 `[1계약·TP1상한·미실현 시뮬]` |
| [12] qty=1 TP1 이후 트레일 폭 counterfactual | ✅ PASS | 누적 hyp=-16.3033pt 승률=58.3% (n=72, 보류 0) 트레일스톱=72건 강제청산=0건 `[1계약·TP1상한·미실현 시뮬]` |
| [13] 등급별 순EV 역전 감시 | ❌ FAIL | A=-1,397원(n=102, 최대손실=-638,449원) C=5,456원(n=55)  📌 **부결 — GradeEVGuard 활성화하지 않음** (2026-08-01) |
| [14] Tier1 잔여계약 2단계 조기청산 counterfactual | ⏳ INSUFFICIENT | 누적 hyp=0.5212pt 승률=100.0% (n=1, 보류 0) `[1계약·TP1상한·미실현 시뮬]` |
| [15] 급행 풀스톱(TP1 미도달) 관찰 | 👁 OBSERVE | 급행하드스톱=76건 중 TP1미도달=28건 (A: n=20 누적=-2,748,079원) |
| [16] chase+foreign 조합 관찰 | 👁 OBSERVE | 동시실패=30건 누적=2,119,485원 (매칭=160건) |
| [17] 청산 체결 슬리피지 관찰 | 👁 OBSERVE | n=109 평균=-0.1816pt (가정 0.02pt) |
| [18] RegimeExhaustionGate(탈진반전) | 🔶 SUPPORTS_GATE | 발동=69건 누적hyp=-23.1523pt (STOP=23/TP1=46/NEITHER=0) `[1계약·TP1상한·미실현 시뮬]` |
| [19] ToxicityGate block counterfactual | ⏳ INSUFFICIENT | 누적 hyp=-0.8151pt 승률=80.0% (n=5, 보류 0) `[1계약·TP1상한·미실현 시뮬]` |
| [20] BAR_ONLY_RELAX 수용/롤백 | ⏳ INSUFFICIENT | 완화후 collapse=21.2% (기준선 45.0%, 목표 20%±7%p) 계측일 전1/후7 |
| [21] 방향별 순EV (SYSTEM_AUTO) | ❌ FAIL | LONG: n=25 평균=-33,958원 최대손실=-473,373원 / SHORT: n=124 평균=13,166원 최대손실=-523,099원  📌 **판정보류 — LONG 방향만 PC간 부호 역전** (2026-08-02) |
| [22] MFE 캡처율 관찰 | 👁 OBSERVE | 풀링캡처 보유내=8.4% 종가까지=0.7% / 평균잔여 12.282 pt (진입 149건) |
| [23] EOD 모델가드 판정 괴리 | ✅ PASS | missed_upgrade=8.3% (n=3/36, 6일) |
| **[47] 시뮬 재현충실도 게이트** | ⏸ SUSPEND(하위 정지) | 재현 실패 — 총합 부호 불일치 (시뮬 -26.80 vs 실제 +27.86 pt) (n=149/17일) → 하위 채널 판정 정지 |
| [48] 봉중 하드스톱 경로 건전성 | ⏳ INSUFFICIENT | 봉중 경로 표본 부족 (n=13<25 또는 거래일=3<8) |
| [49] 페이오프 기하 상시 감시 | ✅ PASS | edge_gap > 0 (원화 +3.62%p · 위험조정 +0.12%p) ⚠ 두 기준 격차 3.50%p > 3.0 — 결과가 소수 고변동일에 집중됐을 가능성 · 포지션 149건/17일 (레그 160건) |
| [23-B] TP1/손절 초기 기하 A/B | ⏸ SUSPENDED(계측 무효) | 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `PASS`: 모든 대안이 현행 이하 (진입 149건/17일)  📌 **FAIL이지만 미적용 — 현행 유지** (2026-08-01) |
| [24] TP1 보호전환 반납 관찰 | 👁 OBSERVE | 중앙값 반납=0.42 pt (반납 53 / 달림 25, n=78) ⚠ **모드 혼재**: atr_profit 76/breakeven 2 — 모드별 값은 상세 참조 |
| [25] TP1 보호전환 offset A/B | ⏸ SUSPENDED(계측 무효) | 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `FAIL`: 현행 초과 대안: atr_lock_0.50, atr_lock_0.75, bar_range (전환 76건/13일) ⚠클램프 atr_lock_0.75 54건, bar_range 27건, atr_lock_0.50 9건  📌 **FAIL이지만 미적용 — 현행 유지 (근거 교체됨: drop-max 제동 소멸 → 계측 결함 + 일자단위 미유의로 대체)** (2026-08-05) |
| [25-B] TP2 거리 A/B | ❌ FAIL | 현행 초과 대안: tp2_2.00 (전환 76건/13일) |
| [26] 거래불능(가격상한 고착) 구간 | 👁 OBSERVE | 고착 29분봉 / 1일  · MFE오염 없음 |
| [27] counterfactual 도달불가 목표가 | 👁 OBSERVE | 해당 5건 (hurst_gate_shadow=1, joint_gate_shadow=1, regime_exhaustion_shadow=3) · hyp합 -13.3346 pt — 판정 미반영, 민감도만 |
| [28] 사이징 역예측 감시 ⚠구조적판정불가 | ⏳ INSUFFICIENT | 구간 표본 부족 (qty1=137, qty3+=1, 각각 20 필요) — 판정 보류 ⚠ **구조적 판정불가** |
| [29] mean-revert 레짐 사이즈 | ✅ PASS | mean_revert: n=89 승률=59.6% 평균=-25,664원 / neutral_trend: n=68 승률=70.6% 평균=35,907원 |
| [30] toxicity 재보정 밴드분포 | ✅ PASS | pass=40.7% reduce=58.1% block=1.1% · cancel포화=0.3% (n=1923분봉) |
| [31] tox reduce 연속배수 섀도 | ✅ PASS | 수량 상이 7.7% < 20% — 양자화에 흡수돼 실적용 실익 없음(현행 상수 유지) |
| [34] meta size0 무시 | ⏳ INSUFFICIENT | 표본 부족 (매칭 29/20건, 거래일 4/5) — 판정 보류 |
| [35] 유령 하드스톱 결함/알파 ⚠구조적판정불가 | ⏳ INSUFFICIENT | 유령 청산 표본 0건 — ⚠ **구조적 판정불가** (적재 정상, 미러 15건/3일 병기) |
| [36] 체크리스트 승격 경로 | ⏳ INSUFFICIENT | 경로 표본 부족 (X→A=9, C→A=47, 각각 20 필요) — 판정 보류. 0803 P2 "X 승격 조이기" 제안은 그때까지 보류다 |
| [37] mean-revert 일자단위 재검정 | ✅ PASS | MR 89건 누적 -2,284,103원 · 짝지은 10일 평균차 -1.27pt · p=0.3438 (⚠ [29]와 모집단 동일 — 판독규칙 상세 참조) |
| [38] ProfitGuard-L1 피크 트레일링 | 👁 OBSERVE | 구속 발동 1건 / 1거래일 (필요 5건 / 5일) — 관찰 단계. 실측 발동빈도로는 약 4개월 스케일이다 |
| [39] confidence 판별력 | 🔷 REJECTS_HYP | 모델축 +0.45%p(n=17394, 일자 p=0.3075) · 앙상블축 +0.0096(d=0.16, 승101/패56) · 매칭 157/157 |
| [40] 방향 선택의 가치 | 🔷 REJECTS_HYP | 실제 -30.41pt vs 무작위중앙 +16.89pt (n=157/19일) · 단측 p=0.8703 · 일자 10/19일 |
| [41] 청산 측 학습기 게이지 | 👁 OBSERVE | EPV 3.53 < 10 (포지션 150/425, 275건 부족) · 거래일 19/20 — **학습 거부**. 이 표본으로 학습하면 학습이 아니라 암기다 |
| [42] 타점의 가치 | 🔶 SUPPORTS_HYP | 타점 기여(B-C) +13.69pt · B>C 58.2% · 짝지은 p=0.001128 (A -30.41 / B +20.68 / C +6.99) |
| [43] 변동성 추정량 교체 | 🔷 REJECTS_HYP | ATR 통제 후 부분상관 +0.0403 (t=0.445) · 공선성 0.954 · 실현레인지 상관 ATR +0.667 / q90-q10 +0.645 · qty경계통과 75건 |
| [44] DynMC 붕괴행 잠식 | ⏳ INSUFFICIENT | 표본 부족 — 6거래일(필요 10) / 2215행(필요 2000). ⚠ base_mc는 10일 롤링이라 07-31 전환분이 다 채워지기 전 수치로 판정하면 과도구간을 정상으로 오인한다. |
| [45] 축퇴 가드 플래핑 (게이지) | 👁 OBSERVE | 보정 미적용 76.1% · 전환 13.17회/일(경보 4.0) · 전환 시 conf 점프 중앙값 0.3392(경보 0.10) |
| [46] Hurst 임계 위치 A/B | ⏸ SUSPENDED(계측 무효) | 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `INSUFFICIENT`: OOS 표본 부족 (n=40<40 또는 거래일=2<10). 전체표본 결과는 가설 수립 기간의 in-sample이라 판정 근거가 아니다 (OOS 40건/2일, 전체 159건/19일) |

> `[1계약·TP1상한·미실현 시뮬]` 배지가 붙은 채널의 `hyp=…pt`는 **실현손익이 아니다** — 계약수를 곱하지 않은 1계약 기준이고, TP1에서 끊는 가상 청산이며, 실제로는 일어나지 않은 거래다. 배지 없는 원(₩) 단위 채널([13]·[21]·[5]·[8])과 직접 더하거나 비교하지 말 것. 채널별 진입시점 계약수 분포는 각 채널 상세 절 참조.
## [0] 캠페인 표본 기아 경보 + 완화 사다리 (§3-8)

- 주간(7일) 진입 체결: **95건** (하한 10건) → 4주 투영 380건
- **완화 사다리 상태**: 정상 — 사다리 미적용 상태 유지

| 단계 | 조치 | 상태 |
|---|---|---|
| 1 | 관찰만 — FQAdj 배선 수정(297차)의 자연 회복 효과 확인 |  |
| 2 | 구형 MetaGate take_ceil(C등급) 완화: 0.570 → 0.52 |  |
| 3 | Hurst 횡보 차단 임계값 완화 (최후 수단): 0.45 → 0.40 |  |

> 사다리 적용은 항상 사용자 수동 결정 — 자동 변경 없음. 적용 시 `dev_memory/DECISION_LOG.md`에 기록할 것.

## [1] Triple-Barrier — OOS replay IC vs 3클래스 IC

| 호라이즌 | 판정 | IC_TB | IC_3class | OOS n | 비고 |
|---|---|---|---|---|---|
| 1m | FAIL (유지, 2026-08-07 판정) | 0.0004 | 0.0495 | 0 | OOS 표본 0건 (모델 mtime 이후 데이터 대기) — 최근 판정 유지: FAIL (2026-08-07 판정, n=1844) |
| 3m | FAIL (유지, 2026-08-07 판정) | -0.0087 | 0.0001 | 0 | OOS 표본 0건 (모델 mtime 이후 데이터 대기) — 최근 판정 유지: FAIL (2026-08-07 판정, n=1194) |
| 5m | INSUFFICIENT | — | — | 709 | OOS 표본 부족 (709 < 800) — 첫 판정 대기 |
| 10m | INSUFFICIENT | — | — | 348 | OOS 표본 부족 (348 < 800) — 첫 판정 대기 |
| 15m | INSUFFICIENT | — | — | 222 | OOS 표본 부족 (222 < 800) — 첫 판정 대기 |
| 30m | INSUFFICIENT | — | — | 105 | OOS 표본 부족 (105 < 800) — 첫 판정 대기 |

> [357차 해석 확정] 1m은 앙상블 가중치 영구 0 퇴역(331차 후속2) 상태 —
> 1m이 IC 기준을 합격해도 "1m 앙상블 복귀"가 아니라 1m 활용방안 A·C
> (331차 후속3, 섀도우 경로)의 근거로만 사용한다. **실질 승격 검토 대상은
> 3m/5m로 한정** (30m은 296차 퇴역). 합격선 자체는 불변 — 해석만 확정
> (시계 리셋 불요).
> [384차] 383차가 규명한 구조결함(평가창이 매주 재학습으로 리셋돼 5m~30m이
> min_samples_hz 영구 미달) 해법 적용 — 이제 호라이즌별 실제 OOS n이
> min_samples_hz에 도달한 주에만 신선하게 판정하고, 그 아래 주는 `tb_verdict_log`의
> 최근 판정을 그대로 유지(위 표의 "(유지, YYYY-MM-DD 판정)")한다. 10m/15m/30m은
> 판정 주기 자체가 몇 주~십수 주 단위로 길 뿐 표본은 끊기지 않고 계속 누적된다.

## [2] Meta-Gate — entry_quality_prob 3분위 순EV (왕복비용 0.071 pt 차감)

| 분위 | 순EV(pt) | n |
|---|---|---|
| 상위 33% | 0.0003 | 726 |
| 중위 33% | -0.14 | — |
| 하위 33% | -0.0065 | 726 |

## [3] 분위 회귀 — 캘리브레이션

- 표본: 5443건 / 커버리지 0.8064 (합격 밴드 0.72~0.88) / 불확실성-실현폭 상관 0.3507 (하한 0.15)

### [3-A] q50 방향 적중률 (404차 후속10, 관찰 전용 — 판정 없음)

| 구분 | n | 방향 적중률 |
|---|---|---|
| 전체 | 5383 | 50.9% |
| \|q50\| 상위 30% | 1614 | 50.9% |

- q50 > 0 비율: **43.3%** (50%에서 크게 벗어나면 방향 편향)

> **판정하지 않는다**(§3 합격선 무변경). 감사 §3-3은 분위회귀 KPI를 **3종**으로
> 정의했으나(① q50 방향 적중률 ② 폭-실현 상관 ③ 커버리지) 합격선은 ②③만
> 채택했다 — ①은 **사전등록돼 있었는데 한 번도 렌더링되지 않았다**. 그 탓에
> [3] PASS가 "방향을 맞춘다"로 오독될 여지가 있었다. 실제 의미는
> "**불확실성 폭**을 잘 맞춘다"뿐이다.
> 이 표의 목적은 승격 근거가 아니라 그 오독을 차단하는 것이다 — 적중률이
> 50% 근처면 **q50을 방향·사이징에 쓰지 말라**는 뜻이고, [2] Meta-Gate가
> 확신도-성과 역상관으로 탈락한 것과 같은 실패를 예방한다.
> `|q50| 상위 30%` 적중률이 전체와 비슷하면 q50의 **크기**에도 정보가 없다는 뜻.

## [3-B] 분위회귀 기반 TP1 거리 A/B (404차 후속10 신설)

- 진입 후보 149건 → 시뮬 125건 / 거래일 14일
- 제외: 분위결측 24건(2026-07-20 이전 미적재) / ATR결측 0 / 이익방향분위 부호반대 0 / TP과협 0 / 시뮬불가 0

| 변형 | n | TP1 | STOP | 승률 | 누적pt | 현행 대비 | drop-max | 건별 우세 |
|---|---|---|---|---|---|---|---|---|
| current | 125 | 89 | 36 | 71.2% | -24.40 | +0.00 | — | 0/125 |
| q_raw | 125 | 76 | 49 | 60.8% | -16.20 | +8.20 | +6.48 | 74/125 |
| q_x0.7 | 125 | 79 | 46 | 63.2% | -50.82 | -26.42 | -27.35 | 59/125 |
| q_blend | 125 | 79 | 46 | 63.2% | -35.12 | -10.72 | -11.58 | 77/125 |

- **판정: SUSPENDED** — 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `FAIL`: 현행 초과 대안: q_raw

> **이 채널의 판정은 [3] 본채널 verdict에 반영하지 않는다**(§9-4 판정기준 사후
> 변경 금지). [3]의 합격선은 커버리지·불확실성상관 두 개 그대로다.
> 묻는 것: 현행 TP1은 `ATR × 배수`로 **신호 내용과 무관**한데, 분위회귀가 매 분봉
> 계산해 두고도 쓰지 않는 "이익 방향 꼬리까지의 거리"를 쓰면 나은가.
> LONG은 q90, SHORT는 |q10| — 방향별 favorable quantile을 쓴다(SHORT에 q90을
> 쓰면 손실 방향 꼬리를 TP로 삼는 꼴).
> **스톱은 전 변형 고정**(현행 ATR×1.5×hurst) — [23-B] `sym_1.0_1.0`이 TP·스톱을
> 동시에 바꿔 기여 분해가 불가능했던 교란을 제거했다.
> ⚠ 절대값은 실현손익이 아니다(qty=1 보호전환을 'TP1 전량청산'으로 단순화).
> **변형 간 상대비교 전용.**
> ⚠ FAIL이 떠도 즉시 적용 금지 — `drop-max`(최대기여 1건 제거 후 델타)와
> `건별 우세`를 함께 볼 것. [25]는 drop-max에서 부호가 역전돼 무너졌다(372차).
> ⚠ **MW0601 교차확인 필수** — [23-B]가 같은 코드·같은 기간에도 PC간 부호
> 역전을 냈다(tp1_x2: +32.78 vs −19.04). n≈40으로는 기하를 확정할 수 없다(313차).
> ⚠ 변형 간 결과가 **단조롭지 않으면**(예: 0.7배가 1.0배보다 나쁨) 폭 자체보다
> "몇 건이 TP1↔STOP으로 뒤집혔나"가 결과를 지배한다는 뜻이다 — 표의 TP1/STOP
> 건수를 함께 읽을 것.

## [4] 신호소멸청산 counterfactual (§3-5 롤백 기준 ①)

- 이번 실행 resolve: 0건 / 누적 판정 16건 (미판정 0건)
- counterfactual 분포: STOP 7 / TP1 9 / NEITHER 0
- 누적 saved_pts(아낀 pt − 놓친 pt): **10.9618 pt**

## [5] 레짐 조건부 ATR 배수 (§3-5 롤백 기준 ②)

| 버킷 | n | 평균 순EV(원) | 누적(원) | 승률 |
|---|---|---|---|---|
| mean-revert | 91 | -25,100 | -2,284,103 | 58.2% |
| neutral | 52 | 40,728 | 2,117,871 | 69.2% |
| trend | 29 | 36,297 | 1,052,613 | 72.4% |

## [6] Hurst 게이트 counterfactual (§3-6, P1-4)

- 이번 실행 resolve: 0건 / 누적 판정 286건 (미판정 0건)
- counterfactual 분포: STOP 85 / TP1 201 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-1.8072 pt** / 승률 70.3% (기준선 63.9%)
- 진입시점 계약수 분포: 1계약×254, 2계약×24, 3계약×8 (매칭 286/286건)
  - **참고(판정 미반영)**: 비가중 -1.8072 pt → 사이저 제안 수량 가중 -16.0735 pt (8.89배). 판정은 비가중 1계약 기준을 그대로 쓴다 — 게이트 성능에 사이저 성능을 섞지 않기 위해서다(§9-4 합격선 무변경).

## [7] JointGateBlock counterfactual (§3-7, 327차)

- 이번 실행 resolve: 0건 / 누적 판정 80건 (미판정 0건)
- counterfactual 분포: STOP 24 / TP1 56 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-24.4284 pt** / 승률 70.0% (기준선 63.9%)
- meta_size 구간별(tox_size 상수 구조 검증용):
  - high(meta≥0.55): n=13 hyp=-1.775pt 승률=76.9%
  - low(meta<0.55): n=67 hyp=-22.6534pt 승률=68.7%

### tox 체제 분리 (419차 P0 반영)

- 경계: **2026-08-03** (`TOXICITY_CANCEL_CHURN_CEILING` 0.08→0.42 배포일)
- 구 체제(~경계 전): n=78 누적 hyp=-48.4179pt 승률=62.8%
- 신 체제(경계 이후): n=80 누적 hyp=-24.4284pt 승률=70.0%
- **판정 대상**: 419차 P0 재보정 **이후**(2026-08-03~) 표본으로 판정
- 행에 기록된 tox_ceiling: 구=미계측 / 신=[0.42]

> **구·신 체제를 합산하지 않는다.** JointGateBlock의 발동 전제가
> `tox_action=="reduce"`인데 419차 P0이 그 밴드 분포를 이동시켰다
> (block 23.3→8.6% / reduce 76.4→73.7% / pass 0.27→17.7%). 두 구간은
> 모집단이 달라 합치면 서로 다른 분포의 평균을 판정하게 된다.

### 에피소드 단위 재집계 + 증거강도

- 신호 80건 = **에피소드 40건** (평균 2.0신호/에피소드, 최대 연속 9분)
- 에피소드 첫신호 기준: 누적 hyp=**-11.5934pt** 승률=70.0%
- 건당 평균=-0.2898 sd=2.4044 → **t=-0.762** (임계 |t|≥2.0)
- **증거강도: NO_EVIDENCE**

> **verdict와 증거강도는 다른 축이다.** verdict PASS는 `누적 hyp ≤ 0`
> 이분법이라 -13pt와 -0.01pt가 같은 판정을 받는다 — "FAIL이 아니다"와
> "차단이 옳다"는 다른 말이다. 통계 단위를 에피소드로 잡는 이유는
> JointGateBlock이 조건 지속 중 **매 분봉 재차단**하기 때문이다
> (같은 사건을 여러 번 세면 유의성이 부풀려진다).

### 단일일 민감도 (jackknife)

- 거래일 5일 · 최대 기여일: 2026-08-07 (-13.6765pt)
- ⚠ **이 날 하루를 빼면 누적 부호가 뒤집힌다**:
  - 2026-08-07 제거 → 누적 -11.5934pt → **2.0831pt**
- → 판정이 단일 거래일에 걸려 있다. 조치 근거로 쓰지 말 것.

### 419차 P1(연속 배수) 실적용 시 차단 축 반사실

- 계측 n=80 · 평균 tox 섀도배수=0.7982 (현행 상수 0.70)
- 차단 **유지** 73건 (91.2%) / **해제** 7건
- 해제됐을 신호의 counterfactual: 누적 hyp=-4.7024pt 승률=71.4%

> **판정하지 않는다 — 세기만 한다.** `[31] toxicity_reduce_mult_shadow`는
> 실제로 **체결된** reduce 밴드 진입만 보므로 JointGateBlock으로 차단된
> 신호는 그 채널에 들어가지 않는다. 여기가 그 사각지대다. 연속 배수가
> 실적용되면 `joint_mult`이 바뀌어 차단 여부 자체가 뒤집힐 수 있으므로
> ([31] FAIL 시 함께 읽을 것), 차단 축 비용을 미리 계측해 둔다.
>
> ⚠ **한 방향만 본다.** 이 표는 "지금 차단된 신호"만 담는다
> (joint_gate_shadow는 차단 시점에만 기록된다). 연속 배수는 반대
> 방향으로도 판정을 뒤집는다 — 예: meta=0.75 × tox_shadow=0.36이면
> 현행 0.525로 통과하지만 섀도로는 0.357이라 **차단**이다. 그런 건은
> 실제로 체결됐으므로 여기 없고 `trades`에 있다. 따라서 위 "해제
> 7건"을 P1의 순 노출 증가로 읽으면 안 된다 — 반대편이 빠져 있다.

### meta falsy 폴백 분리 (419차 발견 ④)

- 폴백(`or 0.5` 발동 — 모델은 size 0을 지시): n=60 hyp=-24.8275pt 승률=66.7%
- 실학습값: n=20 hyp=0.3991pt 승률=80.0%

> 위 `meta_size 구간별(0.55)` 분할은 이 축과 섞여 있어 단독으로는
> 해석되지 않는다 — 구 체제 실측에서 low 버킷 94건 중 73건(78%)이
> 폴백이었다. **폴백은 모델이 "사이즈를 주지 말라"(size_mult=0.0)고
> 한 상태를 `or 0.5`가 밴드 중간값으로 승격시킨 것**이라 의미가 반대다.

### MFE 병기 — counterfactual이 얼마나 과소평가하는가 (P1-D)

- 30분 창 MFE 평균 **4.5745 pt**(중앙값 3.0) · MAE 평균 **8.637 pt** (n=80)
- **MFE>MAE 25건 vs MAE≥MFE 55건** (ΣMFE 365.96 / ΣMAE 690.96 pt)
- counterfactual 포착률 Σhyp/ΣMFE = -6.7% (음수 = TP1 가정의 순손익이 마이너스라는 뜻이지 '비율'로 읽지 말 것)
- 추세형 과소평가 건수(MFE≥5pt 이면서 hyp<MFE의 30%): **27건**

| 시각 | 방향 | MFE(30분) | MAE(30분) | TP1 기준 hyp | cf |
|---|---|---|---|---|---|
| 08-07 09:56 | SHORT | **+21.22** | −5.74 | -5.38 | STOP |
| 08-06 09:40 | SHORT | **+17.54** | −3.12 | 1.6 | TP1 |
| 08-06 09:38 | SHORT | **+15.8** | −4.86 | 1.71 | TP1 |
| 08-06 09:39 | SHORT | **+15.02** | −5.64 | -5.08 | STOP |
| 08-06 09:34 | SHORT | **+14.02** | −5.04 | 1.64 | TP1 |

> **계측이지 처방이 아니다.** `hyp_pnl_pts`는 차단 신호를 현행 TP1
> (ATR×0.3~0.5)로 청산했다고 가정하는데, 그 TP1이 너무 좁다는 것이 0731
> 리포트 §2-C의 결론이다 — 즉 counterfactual이 자기 편향적이라 추세일의
> 차단 비용을 구조적으로 과소평가한다. 포착률이 낮을수록 위 "차단이
> 이득" 판정이 TP1 가정에 크게 기대고 있다는 뜻이다.
>
> ⚠ 이 수치로 **TP를 넓히자는 결론을 내면 안 된다** — §2-E가 차단 19건에
> 대칭 TP(1:1)를 직접 적용해 −9.87pt(현행 +4.92pt)로 **이미 기각**했다.
> 이기는 거래가 더 버는 만큼 지는 거래도 커진다. MFE는 "차단 판정이
> 어떤 가정 위에 서 있는지"를 드러낼 뿐이다.
>
> ⚠ **MFE만 보면 정반대로 읽힌다 — MAE를 반드시 함께 볼 것.**
> 이 표본에서 MAE 평균이 MFE 평균보다 **크다**. 차단된 신호들은 유리하게
> 간 폭보다 불리하게 간 폭이 더 컸다는 뜻이고, 그건 차단이 옳았던 쪽
> 증거다. "추세일 차단 비용 과소평가"는 개별 추세 건에서는 사실이지만
> 표본 전체로는 반대 방향 증거가 더 크다.
>
> ⚠ **MFE/MAE는 순서를 모른다.** 위 07-27 09:49 SHORT처럼 MFE +23.96인데
> cf=STOP인 건은, 스톱이 먼저 맞은 뒤에 유리하게 갔다는 뜻일 수 있다.
> "이만큼 벌 수 있었다"의 상한이지 실현 가능한 값이 아니다.

- 진입시점 계약수 분포: 1계약×151, 2계약×5, 3계약×2 (매칭 158/158건)
  - **참고(판정 미반영)**: 비가중 -72.8463 pt → 사이저 제안 수량 가중 -87.8768 pt (1.21배). 판정은 비가중 1계약 기준을 그대로 쓴다 — 게이트 성능에 사이저 성능을 섞지 않기 위해서다(§9-4 합격선 무변경).

## [28] 사이징 역예측 감시 (MW0601 405차, P1-2)

> 계약수를 키울수록 실현 순EV가 나빠지는가. 0801 점검 §9-3에서 3계약 이상 16전 1승 -2,642만원(이항검정 p=5.07e-07)이 확인됐으나 이를 보는 채널이 하나도 없었다. **자동 조치 없음** — MAX_CONTRACTS 인하는 주간회의 수동 결정(§9).

- 포지션 157건 / 19일 (부분청산 병합, 시스템 자동진입 — `entry_source=SYSTEM_AUTO` ∪ 컬럼 신설 이전 NULL행)
  - 계약수 출처: `entry_qty` 기록값 157건 / 청산레그 합 폴백 0건 — 405차 `max` 집계는 409차 실측 반증으로 폐기(417차 ①)
  - **qty1**: n=137 승률 65.0% 평균 2,009원 누적 275,287원 (최대손실 -473,373원)
  - **qty2**: n=19 승률 57.9% 평균 -6,897원 누적 -131,042원 (최대손실 -638,449원)
  - **qty3plus**: n=1 승률 100.0% 평균 13,340원 누적 13,340원 (최대손실 13,340원)

- ⚠ **구조적 판정불가** — 최근 5거래일 qty≥3 **체결** 0건 (누적 1건). 원인은 사이징 자본이 아니라 **사이저 뒤의 곱셈 게이트 체인**이다 — 417차 로그 실측(2026-07-14~07-31)에서 `[Sizer]`는 379건 중 86건(22.7%)이 3계약 이상을 출력했고 최대 6계약까지 나왔으나, 진입까지 간 69건이 전부 meta·tox 등 배수에 눌려 1~2계약으로 체결됐다(qty≥3 체결 0건, 최빈 조합 meta≈0.50 × tox=0.70 ≈ 0.35). 따라서 이 버킷은 **기다린다고 채워지지 않지만**, ⑧ 해제로 base_risk가 오르거나 게이트 배수가 완화되면 즉시 표본이 생긴다 — 죽은 채널이 아니라 **눌려 잠든** 채널이다. CLAUDE.md ⑧이 이 채널의 누적 판정을 MAX_CONTRACTS 인하 근거로 지정하고 있으므로, 지금 판정이 필요하다면 과거 3계약+ 구간(2026-06-10~07-10) 포지션 단위 재분석을 별도 근거로 쓸 것.
  - 이것은 "표본이 모이는 중"이 **아니다**. 표시를 분리한 이유는 `toxicity_block_shadow`가 자기모순 조건으로 3개월간 0건인 채 방치됐던 402차 후속3과 같은 유형이기 때문이다.
- 계약수 상한별 부분합(그 초과 거래를 **아예 안 했다면**): 상한1=275,287원 / 상한2=144,245원 / 상한3=157,585원 / 전체 157,585원
  - ⚠ 진짜 counterfactual이 아니다 — 사이즈가 달랐으면 체결·청산 경로도 달랐을 것이므로 "상한 N이었다면"이 아니라 "그 거래들을 제외하면"으로 읽을 것.
- 구간 표본 부족 (qty1=137, qty3+=1, 각각 20 필요) — 판정 보류 ⚠ **구조적 판정불가**

## [29] mean-revert 레짐 사이즈 (MW0601 405차, P1-3)

> 0801 점검 §6-3의 313차 z검정 5개 세그먼트 중 **유일하게 Bonferroni 생존**한 축 (mean-revert 승률 45.7% vs 69.1%, z=-2.61 p=0.00911, n=35/152, 일자 분산 9일). n=35·최다일 40%로 경계선이라 누적 확인이 필요하다. **"진입 차단"이 아니라 사이즈/등급 축 처방 가설**이다(317차 FalseBlock 교훈).

- 포지션 157건 / 19일 (부분청산 병합, 시스템 자동진입 — `entry_source=SYSTEM_AUTO` ∪ 컬럼 신설 이전 NULL행)
  - **mean_revert**: n=89 승률 59.6% 평균 -25,664원 누적 -2,284,103원
  - **neutral_trend**: n=68 승률 70.6% 평균 35,907원 누적 2,441,688원

## [8] KellyAdvisedSkip × C등급 누적 성과 (341차 신설)

- C등급+KellySkip 체결 n=30 | 누적 순PnL=-878,357원 | 평균=-29,279원 | 승률=63.3%
- 비교(C등급, KellySkip 아님) n=26 | 평균=45,324원 | 승률=73.1%
- 등급별(KellySkip=1 전체, 참고용):
  - A급: n=20 누적PnL=-232,066원 승률=65.0%
  - C급: n=30 누적PnL=-878,357원 승률=63.3%
- **권고**: C등급+KellySkip 조합 누적 순손실 확정 — 진입 차단(사이징 0 또는 등급 강등) 단계 도입 검토 (§9 사전등록 원칙에 따라 적용은 수동 결정)

## [9] OPEN_VOLATILE 시가이격 counterfactual (§14, 354차)

- 이번 실행 resolve: 0건 / 누적 판정 29건 (미판정 0건)
- counterfactual 분포: STOP 10 / TP1 19 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-11.6572 pt** / 승률 65.5% (기준선 63.9%)
- 평균 gap_pt=26.55 / 평균 atr_at_block=3.22 (기준점 재설계 시 캘리브레이션 근거)

## [11] qty=1 손실1차(Loss Tier1) 조기청산 counterfactual (363차 / 425차 개정)

**0804 4-3 딥다이브에서 집행 축의 유일한 생존 처방으로 확정된 채널이다.**
급행 풀스톱 16건 중 **13건(-2,319,612원, 81%)이 qty=1**이고, qty=1은
`is_loss_tier1_hit()`가 "물리적 분할 불가"로 원천 제외해 전액이 풀스톱까지
노출된다. 같은 딥다이브에서 다른 후보는 전부 떨어졌다 —
손절 유예·스톱 확대는 **반증**(급행 16건 중 14건이 청산 후 더 나빠짐),
체결 슬리피지는 **대상 아님**(FAST 평균 -0.0157pt), 지정가 진입은 **미지지**
(최선 변형도 일자단위 p=0.45·델타의 59%가 단일일), 진입 판별자는 421차
Phase A가 245피처 **BH FDR 통과 0개**. "스톱이 옳았다"면 남는 레버는
**더 일찍 끊는 것**이고 그게 이 채널이다.

- 이번 실행 resolve: 0건 / 누적 판정 43건 (미판정 0건)
- 누적 hyp_pnl_pts(tier1가 조기청산 vs 실제 실현 pt 차이): **5.8248 pt** / 승률 67.4%
- 판정 조건 **2겹**: ① 누적 hyp > 왕복비용×2 → **충족** / ② 일자단위 부호검정 p<0.05 → **미충족** (6/8일, p=0.2891)
- 판정 제외: 실적용 이후 0건 · tier1 잔여계약 1건 (전자는 반사실이 실제와 같아지고, 후자는 이미 한 번 보호받은 다른 모집단이라 [14]가 맡는다)
- **권고**: 누적 +5.82pt는 비용 기준을 넘지만 **일자단위로 재현되지 않는다** (6/8일, p=0.2891) — 채택 보류. 누적 수치만으로 움직이지 말 것(313차)
- [제안3 편입, 참고용] edge_ratio(=|기대엣지|/불확실성, n=44, 평균=0.0313) vs 실현 pt 스피어만 상관: **0.2103** (게이트 아님 — 등급/사이징 강화 여부는 표본이 더 쌓인 뒤 별도 검토)

> **거래일이 병목이지 건수가 아니다.** 일자단위 양측 부호검정에서 얻을 수
> 있는 최소 p는 n=5일 때 0.0625로, α=0.05를 **원리적으로** 통과할 수 없다
> (n=6부터 0.03125로 기각 가능). 그래서 `min_days=6`을 걸었다 —
> 425차 등록 시점에 이미 5거래일 전부 양수였고 그 바닥에 닿아 있었다.
> 
> **FAIL이어도 자동 전환 금지.** 적용은 `LOSS_TIER1_QTY1_ENABLED = True` +
> `LOSS_TIER1_QTY1_EFFECTIVE_DATE` 기입이고 주간회의 수동 결정이다(§9).
> qty=1은 쪼갤 수 없으므로 이 정책은 부분 축소가 아니라 **qty=1 한정
> 손절폭 절반**이다 — 회복했을 포지션을 조기 손절하는 비용이 따르며,
> 그 비용은 위 hyp_pnl_pts에 이미 차감돼 있다(음수 표본이 그것이다).
> 
> ⚠ **전환하면 이 채널의 판정은 얼어붙는다** — 실제로 자르게 되므로
> 반사실이 실제와 같아진다. 그래서 전환 후 기록은 `live_active=1`로
> 태깅해 판정에서 빼고, 회귀 감시는 [15]·[13]이 맡는다.

## [12] qty=1 TP1 이후 트레일 폭 counterfactual (363차 후속, 0721 제안4 편입)

- 이번 실행 resolve: 0건 / 누적 판정 72건 (미판정 0건)
- counterfactual 분포: TRAIL_STOP 72 / FORCE_EXIT 0
- 누적 hyp_pnl_pts(4단계 트레일링 지속 vs 실제 static lock 실현 pt 차이): **-16.3033 pt** / 승률 58.3%

## [13] 등급별 순EV 역전 감시 (366차, 0722 정기점검 딥다이브)

| 등급 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| A | 102 | -1,397 | -142,489 | 62.7% | -638,449 | 206,698 |
| C | 55 | 5,456 | 300,074 | 67.3% | -248,467 | 142,558 |

> [367차, 제안4 편입] 최대손실·표준편차 보강 — 평균만으로는 "등급 전체가
> 고르게 나쁨"과 "소수 초대형 손실(fat-tail)이 평균을 끌어내림"을 구분할
> 수 없다. 0722 딥다이브: A등급 4주 누적손실의 84%가 [15]에서 관찰하는
> "TP1 도달 전 급행 풀스톱" 9건에 집중돼 있었음 — 표준편차가 크고
> 최대손실이 평균의 여러 배면 이 fat-tail 구조를 의심할 것.

**등급 × 계약수 분해** — 이 채널이 "등급별" 역전으로 부르는 현상이
계약수 축으로 더 잘 설명되는지 본다:

| 등급 | qty≤2 n / 누적(원) / 평균(원) | qty≥3 n(승) / 누적(원) / 평균(원) |
|---|---|---|
| A | 101 / -155,829 / -1,543 | 1(승1) / 13,340 / 13,340 |
| C | 55 / 300,074 / 5,456 | — |

> qty≤2로 한정해도 A/C 역전이 유지된다 — 계약수만으로는 설명되지 않는다.
> ⚠ **qty≥3 표본이 얇다**(313차: 이걸로 확정 결론 금지). 또 이 표는 캠페인
> 구간 한정이라, 전체 기간을 본 `CLAUDE.md` 전환기준 ⑧의 §9-3
> "3계약 이상 16전 1승"과 모집단이 다르다 — 두 수치를 같은 것으로 읽지 말 것.
> **판정식은 무변경**(A 평균 순EV < 0 → FAIL). 계약수 축 판정은
> [28] `sizing_inversion_watch`가 맡는다 — 함께 볼 것.
- **권고**: A등급 누적 순EV 음수 확정(C등급은 양수) — GradeEVGuard (config.settings.GRADE_EV_GUARD_ENABLED) 활성화를 주간회의에서 검토 (§9 사전등록 원칙에 따라 적용은 수동 결정)

## [14] Tier1 잔여계약 2단계 조기청산 counterfactual (367차)

- 이번 실행 resolve: 0건 / 누적 판정 1건 (미판정 0건)
- 누적 hyp_pnl_pts(tier2가 조기청산 vs 실제 잔여계약 실현 pt 차이): **0.5212 pt** / 승률 100.0%
- tier2 터치 표본 부족 (1 < 20) — 판정 보류

## [15] 급행 풀스톱(TP1 미도달) 관찰 (367차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: 하드스톱 청산 + 보유시간 ≤ 150초 + 진입~청산 구간에 TP1 관련 로그 없음
- 급행 하드스톱 76건 중 TP1 미도달 28건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 20 | -2,748,079 | 18 |
| C | 8 | -1,198,972 | 8 |
- 이 채널은 PASS/FAIL을 판정하지 않는다 — 이 패턴 자체를 차단할 정책이
  아직 없어 판정이 무의미하다. GradeEVGuard·loss_tier1_qty1_shadow·
  loss_tier2_remainder_shadow가 다루는 문제의 선행지표로만 참고할 것.

## [16] chase+foreign 조합 관찰 (368차, 관찰 전용 — 정책 게이트 아님)

- 관찰 기준: [진입체크] 로그에서 `10_chase`·`6_foreign` 두 항목만 동시 실패 (나머지 항목 무관)
- 로그-DB 매칭 160건 중 동시실패 30건

| 등급 | n | 누적 순PnL(원) | 손실건수 |
|---|---|---|---|
| A | 25 | 2,099,082 | 7 |
| C | 5 | 20,403 | 2 |
- CHASE_FOREIGN_COMBO_GUARD_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용. P4(CVD+OFI, 268차)와 동일 계열 논리이나 표본이
  작아(368차 등록 시점 n=5) 즉시 정책화하지 않는다 — §9 사전등록 원칙.

## [17] 청산 체결 슬리피지 관찰 (369차, 0723 정기점검, 관찰 전용 — 정책 게이트 아님)

- 관찰 대상: 모든 청산 주문의 의도가(price_hint) vs 실체결가(fill_price)
  (exit_fill_slippage 테이블, main.py::_ts_record_exit_fill_slippage())
- 표본 n=109, 평균 슬리피지 -0.1816 pt, 최대 0.6 pt (캠페인 가정 0.02 pt/편도)

| 청산사유 | n | 평균 슬리피지(pt) |
|---|---|---|
| 하드스톱(틱) | 78 | 0.0664 |
| 하드스톱 | 13 | -1.8854 |
| TP2(전량) | 11 | -0.02 |
| TP1 부분청산 33% | 6 | -0.04 |
| 손절1차 조기축소 | 1 | 0.0 |
- 계기: 0723 유일 거래에서 TP1 ATR보호전환(+0.35pt 확정 예정)이 체결
  슬리피지로 순손실(-0.02pt)로 뒤집힘. slippage_ticks_per_side(현재 1.0,
  0.02pt)는 캠페인 전 채널의 왕복비용 계산에 쓰이는 공통 가정이므로,
  이 채널의 실측치가 그 가정과 다르더라도 즉시 자동 재보정하지 않는다
  — 바꾸려면 §3 사전등록 원칙에 따라 검증 시계를 리셋해야 한다.

## [18] RegimeExhaustionGate 탈진 반전 counterfactual (379차, 관찰 전용 — 정책 게이트 아님)

- 발동 조건: hurst<0.45(평균회귀) AND 60분 느린 연장폭(price_extension_atr_60m) |값|>1.5ATR AND (10_chase 또는 11_countertrend 소프트 실패)
- 계기: 0723 정기점검 딥다이브 — 진입 직후 반복 반전 패턴 3항. 10_chase(10분 룩백)는 여러 다리에 걸친 느린 탈진을 놓친다는 게 핵심 발견(0723 11:41 SHORT — 직전 10분은 안정, 이전 90분간 -35pt).
- 해석: hyp_pnl_pts는 **신호 방향(추격 방향)대로 갔을 때의 결과** — 다른 섀도 채널과 부호 해석이 반대다. 음수 우세면 탈진 반전 가설 지지.
- 표본: 해결=69건 대기중=0건, 누적 hyp_pnl_pts=-23.1523pt (STOP=23 / TP1=46 / NEITHER=0)
- 평균 60분 연장폭=-2.068pt(ATR배수) 평균 hurst=0.394 (chase실패=69건 / countertrend실패=0건)
- **탈진 반전 가설 지지 — REGIME_EXHAUSTION_GATE_ENABLED 전환(등급 강등) 또는 반대방향 신규 진입 시그널(3-2 제안) 개발을 주간회의에서 검토 (§9 사전등록 원칙 — 즉시 자동 전환 금지)**
- REGIME_EXHAUSTION_GATE_ENABLED(config/settings.py, 섀도) 활성화 여부
  판단 근거 표본 축적용(목표 min_samples=20, hurst_gate_shadow·open_gap_shadow와 동일 기준) — §9 사전등록 원칙, 즉시 자동 전환 없음.

## [19] ToxicityGate block counterfactual (신설)

- 이번 실행 resolve: 0건 / 누적 판정 5건 (미판정 0건)
- counterfactual 분포: STOP 1 / TP1 4 / NEITHER 0
- 누적 hyp_pnl_pts(차단 안 했으면 얻었을 pt): **-0.8151 pt** / 승률 80.0% (기준선 63.9%)
- 평균 toxicity_score=0.3934 / 평균 toxicity_score_ma=0.4191 (block_threshold 재검토 시 캘리브레이션 근거)
- 차단 표본 부족 (5 < 20) — 판정 보류
- action="reduce"는 실제 축소 체결로 trades에 남으므로 이 채널 대상 아님 — action="block"만 계측(open_gap_shadow와 동일 원칙).

## [20] BAR_ONLY_RELAX 수용/롤백 감시 (402차 후속, 관찰 전용 — 자동 롤백 아님)

- 발효일 **2026-07-30** (401차 커밋이 2026-07-29 장 마감 후라 다음 세션부터 적용)
- 계측일: 완화 전 1일 / 완화 후 7일
- collapse 비율: 기준선 45.0% → 완화 후 21.2% (목표 20%±7%p)
- 효과 판정: **ON_TARGET**

| 일자 | 계측 분봉 | collapse% | 3m 적중 | 5m 적중 | 구분 |
|---|---|---|---|---|---|
| 2026-07-29 | 329 | 45.0% | 41.1% | 33.3% | 완화전 |
| 2026-07-30 | 370 | 21.1% | 30.2% | 27.4% | 완화후 |
| 2026-07-31 | 367 | 21.5% | 44.6% | 33.8% | 완화후 |
| 2026-08-03 | 370 | 21.1% | 32.2% | 32.9% | 완화후 |
| 2026-08-04 | 370 | 21.9% | 27.8% | 39.0% | 완화후 |
| 2026-08-05 | 370 | 21.6% | 36.1% | 31.5% | 완화후 |
| 2026-08-06 | 369 | 20.3% | 35.0% | 35.4% | 완화후 |
| 2026-08-07 | 369 | 20.9% | 33.2% | 31.7% | 완화후 |

- **권고**: 효과 목표 구간·부작용 없음 — 완화 존치 수용

> `weight_collapsed`는 398차(2026-07-28 저녁) 배포분부터 기록된다 — 그 이전
> 일자는 컬럼이 NULL이라 "collapse 0건"이 아니라 "미계측"이므로 집계에서
> 제외한다. 완화 전 기준선이 사실상 2026-07-29 단일일이라는 뜻이므로,
> min_days(기본 3거래일) 미만에서는 판정을 보류한다(313차 원칙).
> 롤백은 `config/settings.py:BAR_ONLY_RELAX_ENABLED = False` 1줄로 즉시 가역.
> 일 단위 확인은 `scripts/weight_collapse_monitor.py`.

## [21] 방향별 순EV 감시 (402차 후속5, [13]의 방향 축 미러)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 149건(원본 160행, 부분청산 병합)

| 방향 | n | 평균 순EV(원) | 누적(원) | 승률 | 최대손실(원) | 표준편차(원) |
|---|---|---|---|---|---|---|
| LONG | 25 | -33,958 | -848,955 | 60.0% | -473,373 | 156,077 |
| SHORT | 124 | 13,166 | 1,632,607 | 66.1% | -523,099 | 177,463 |

- **권고**: LONG 방향만 평균 순EV 음수(-33,958원, n=25, 최대손실 -473,373원, 표준편차 156,077원) — 해당 방향 min_conf 상향/사이징 축소를 섀도로 먼저 검증할지 주간회의에서 결정(즉시 적용 아님). 최대손실·표준편차로 단일건 지배 여부를 먼저 확인할 것.

> **[13]과 필터가 다르다(의도적)**. [13]은 `grade IN ('A','B','C')`이라
> 구버전 `entry_source=NULL`·`OPERATOR_MANUAL` 행이 포함되지만, 이 채널은
> `SYSTEM_AUTO` 한정이다 — 방향 편향은 시스템 판단의 문제이므로 수동·레거시
> 진입을 섞으면 안 된다. 두 채널의 표본 수가 다른 것은 결함이 아니다.
> 또한 부분청산 행 중복을 진입 1건 단위로 병합한다 — 그대로 세면 TP1/TP2
> 부분청산이 각각 '승리'로 집계돼 승률이 부풀려진다(402차 실제 오류 사례).

## [22] MFE 캡처율 관찰 (402차 후속5, 관찰 전용 — 판정 없음)

- 필터: `entry_source='SYSTEM_AUTO'` — 진입 149건(원본 160행 병합)
- 평균 실현 0.088 pt / 보유구간 MFE 2.583 pt / 15:10까지 MFE 12.37 pt
- **풀링 캡처율**(ΣRealized/ΣMFE) 보유구간 8.4% (n=144) / 15:10까지 0.7% (n=149)
- **승리 거래만** 15:10까지 풀링 캡처율 12.6% (n=97)
- **평균 미실현 잔여**(MFE−실현) 보유구간 2.448 pt / 15:10까지 12.282 pt

가장 많이 흘린 5건 (15:10 MFE − 실현):

| 진입 | 방향 | 실현pt | 보유MFE | 15:10MFE | 잔여pt |
|---|---|---|---|---|---|
| 2026-07-29 10:38:46 | SHORT | 9.36 | 12.34 | 120.72 | 111.36 |
| 2026-07-29 10:46:45 | SHORT | 12.18 | 12.96 | 98.46 | 86.28 |
| 2026-07-22 11:19:57 | SHORT | 0.24 | 1.64 | 54.86 | 54.62 |
| 2026-07-22 11:30:56 | SHORT | -2.78 | 1.62 | 51.78 | 54.56 |
| 2026-07-22 10:41:56 | SHORT | 0.0 | 3.2 | 51.56 | 51.56 |

> 이 채널은 **판정하지 않는다**(verdict 항상 OBSERVE). 여기서 나올 결정
> ("청산을 더 늦춰라")은 이미 [12] tp1_trail_shadow가 판정 중이므로, 이
> 수치는 그 판정을 해석할 맥락("캡처율이 이렇게 낮은데도 트레일링이 안
> 낫다"가 성립하는지)만 제공한다. 단일일 극단 사례로 결론 내지 말 것
> (2026-07-29 캡처율 7.7%는 -15.6% 폭락일 1건이다 — 313차 원칙).

## [23] EOD 모델가드 판정 괴리 감시 (404차 신설)

- 표본 36건 / 6거래일 (재측정 실패 0건 별도 제외)
- **missed_upgrade_rate** (공정비교=REPLACE인데 acc.txt 기준=HOLD였던 비율): **8.3%** (n=3/36)
- 평균 왜곡(acc.txt − 동일폴드 재측정) = -0.0662

| 호라이즌 | n | missed_upgrade |
|---|---|---|
| 10m | 6 | 1 |
| 15m | 6 | 0 |
| 1m | 6 | 0 |
| 30m | 6 | 0 |
| 3m | 6 | 1 |
| 5m | 6 | 1 |

> **판정 기준**(관측 전 고정, §9): missed_upgrade_rate ≥ 30% → FAIL(판정기준을 old_acc_live로 교체할지 주간회의 검토), 미만 → PASS(acc.txt 유지).
> 07-31 최초 라이브 관측(6개 호라이즌 중 3개 불일치)이 이 채널을 만든 계기이나,
> 임계값은 그 단일일 관측치에 맞추지 않고 독립적으로 고정했다 — 이 리포트가
> 그 계기가 된 날의 데이터를 포함하더라도 임계값 자체는 사후 조정이 아니다.
> (근거: `dev_memory/DECISION_LOG.md` 404차 항목, 313차·§9 원칙)

### [23-부속] intraday 계측 CV 관찰 (404차 후속, 관찰 전용 — 판정 없음)

- 표본 102건 / 6거래일

| 호라이즌 | n | 평균 cv_acc | σ(cv_acc) | 평균 왜곡 | fair_would_hold |
|---|---|---|---|---|---|
| 10m | 17 | 0.4162 | 0.0302 | -0.2476 | 100% |
| 15m | 17 | 0.4205 | 0.0376 | -0.3161 | 100% |
| 1m | 17 | 0.3526 | 0.0089 | -0.2586 | 100% |
| 30m | 17 | 0.5246 | 0.0331 | -0.3479 | 100% |
| 3m | 17 | 0.4193 | 0.0194 | -0.2136 | 100% |
| 5m | 17 | 0.3770 | 0.0203 | -0.2189 | 100% |

> **판정하지 않는다**(verdict 항상 OBSERVE). 실측(404차 후속 §1): 동일 데이터·
> 시드만 다른 재현 분산이 5m 기준 8.83%p로 EOD 가드 허용폭(2.5%p)의 3.5배 —
> 이 표의 σ(cv_acc)가 크게 나오는 것은 결함이 아니라 그 잡음이 실측되는 것이다.
> `fair_would_hold`가 높다고 즉시 intraday 가드를 도입하지 말 것 — 표본이
> 충분히(수 주) 쌓여 잡음이 아닌 추세인지 확인한 뒤 사람이 판단한다(§9).

## [23-B] TP1/손절 초기 기하 A/B (403차 P1-6, 404차 후속3 리포트 편입)

- 진입 149건 (ATR 결측 제외 0건) / 거래일 17일

| 변형 | n | TP1 | STOP | 승률 | 누적pt | 현행 대비 |
|---|---|---|---|---|---|---|
| current | 149 | 105 | 44 | 70.5% | -26.80 | +0.00 |
| stop_1.0 | 149 | 87 | 62 | 58.4% | -38.56 | -11.76 |
| tp1_x2 | 149 | 54 | 95 | 36.2% | -85.20 | -58.40 |
| sym_1.0_1.0 | 149 | 70 | 79 | 47.0% | -30.91 | -4.11 |

- **판정: SUSPENDED** — 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `PASS`: 모든 대안이 현행 이하

### [23-B-OOS] 가설 수립 이후 신규분만 (2026-07-31~) — **판정 미반영**

| 변형 | n | 승률 | 누적pt | 현행 대비 |
|---|---|---|---|---|
| current | 91 | 69.2% | -28.78 | +0.00 |
| stop_1.0 | 91 | 54.9% | -41.07 | -12.29 |
| tp1_x2 | 91 | 34.1% | -66.60 | -37.82 |
| sym_1.0_1.0 | 91 | 42.9% | -31.81 | -3.03 |

> 가설 수립(2026-07-31) 이후 신규 발생분만 — **판정 미반영, 표시 전용**. 누적 verdict는 in-sample 포함 종전 기준 그대로다(§9-4).
> 누적 표(위)는 **가설을 세운 그 기간을 포함**한다(403차 P1-6이 55건/11일로
> 처음 실행하며 이 대안들을 정의했다). 이 절은 그 이후 신규분만 세어 같은
> 방향이 유지되는지를 본다 — 표본이 쌓이기 전에는 해석하지 말 것(313차).

> 종전에는 `scripts/tp1_geometry_shadow.py`를 따로 실행해야만 보여 주간회의에
> 노출되지 않았다(403차 신설 이후). 404차 후속3에서 계산부를 `compute()`/
> `summarize()`로 추출해 이 리포트가 직접 호출한다 — 판정 기준·로직 무변경.
> ⚠ `current`의 절대값은 실현손익이 아니다(qty=1 보호전환을 'TP1 전량청산'으로
> 단순화). **변형 간 상대비교 전용.**
> ⚠ 이 채널은 MW0601에서 `tp1_x2` **+32.78pt**(현행 초과=FAIL 방향)가 나왔으나
> MW0602에서는 **−19.04pt**(PASS 방향)로 **부호가 뒤집힌다.** 두 PC의 거래집합이
> 달라서이며(protect mode 무관 — 이 시뮬은 protect mode를 쓰지 않는다), n≈60·12일
> 로는 기하를 결정할 수 없다는 뜻이다(313차).

## [24] TP1 보호전환 반납 관찰 (404차 후속3, 관찰 전용 — 판정 없음)

- 보호전환 78건 / 13거래일 (모드 분포: atr_profit=76, breakeven=2)
- **반납 53건 / 더 달림 25건**
- TP1 장부이익 평균 1.5228 pt / 중앙값 1.24 pt   |   평균 보호폭 0.5408 pt
- **반납 중앙값 0.42 pt** (평균 -0.0418 pt) → 중앙값 기준 반납률 34%
- 보호폭 vs 반납 상관계수 **-0.234** (음수 = 좁은 보호폭일수록 더 반납)

**모드별 분리** (보호스톱 기준선이 모드마다 달라 섞어 읽으면 안 된다):

| 모드 | n | 거래일 | 반납/달림 | 반납 중앙값 | 반납 평균 | 평균 보호폭 | 보호폭↔반납 상관 |
|---|---|---|---|---|---|---|---|
| `atr_profit` | 76 | 13 | 52 / 24 | **0.42** pt | -0.035 pt | 0.5551 pt | -0.252 |
| `breakeven` | 2 | 1 | 1 / 1 | **-0.3** pt | -0.3 pt | 0.0 pt | — |

> ⚠ **모드가 혼재한다 — 위 풀링 수치를 인용하지 말 것.** 모드별 행만 쓸 것.

> **판정하지 않는다**(verdict 항상 OBSERVE). 처방(offset을 얼마로 할지)은 [25]가 맡는다.
> [MW0601 406차] **모드 라벨 없이 이 수치를 인용하지 말 것** — 보호스톱을 거는
> 자리가 모드마다 다르므로(breakeven=진입가 / atr_profit=ATR×0.25) "반납"의
> 기준선 자체가 다르다. 0802 PC간 대조에서 중앙값 반납이 breakeven −0.1pt vs
> atr_profit +1.0pt로 **부호가 반대**였다 — 섞으면 결론이 상쇄된다.
> **평균이 아니라 중앙값을 볼 것** — 0729 폭락일 2건이 평균을 5배 끌어올려
> 평균 반납은 무해해 보이는데 중앙값은 그 몇 배다. 두 수치가 정반대 인상을
> 주는 전형적 사례이므로 평균만 인용하지 말 것(372차 원칙).
> 소스(`synthetic_partial_exits`)는 339차부터 쌓였으나 404차 후속3까지 **캠페인
> 소비처가 없어 방치**돼 있었다 — 402차 후속3 `toxicity_block_shadow`와 같은 계열.

## [26] 거래불능(가격상한 고착) 구간 (404차 후속5, 관찰 전용 — 판정 없음)

- 고착 **29분봉** / 1일 (세션 분봉 8734개 중)

| 일자 | 방향 | 가격 | 고착분봉 | 구간 | 결측분봉 | 극단 유동터치 | 최대 유동vol |
|---|---|---|---|---|---|---|---|
| 2026-07-31 | UP | 1036.28 | 29 | 14:21~15:06 | 17 | **13** | 642 |

> **핵심 열은 '극단 유동터치'다.** 이 값이 0보다 크면 그 극단을 유동 분봉이
> 이미 만들었다는 뜻이고, 고착 분봉을 전부 지워도 **MFE는 변하지 않는다**
> (max 연산이라 중복 무해). 0731 리포트 §1-C 이상점 3이 제기한 "MFE·캡처율
> 오염" 가설은 이 지표로 **기각**된다 — 07-31 고착 29분봉이 있었지만 1036.28을
> 유동 분봉 13개(최대 vol 642)가 이미 터치했고, 리포트 전문 before/after diff에서
> 실제로 단 한 글자도 바뀌지 않았다.
>
> 이 값이 **0인 날이 나오면 그때는 진짜 오염**이다(갭 상한가 직행 등).
> 진짜 오염은 목표가 쪽이며 [27]이 계측한다.

## [27] counterfactual 도달불가 목표가 (404차 후속5, 관찰 전용 — 판정 없음)

- 해당 행 **5건** (hurst_gate_shadow=1, joint_gate_shadow=1, regime_exhaustion_shadow=3) · 합계 -13.3346 pt

| 테이블 | 시각 | 방향 | 진입가 | 목표가 | 그날 상한 | 결과 | hyp pnl |
|---|---|---|---|---|---|---|---|
| hurst_gate_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |
| joint_gate_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |
| regime_exhaustion_shadow | 10:05 | LONG | 1036.26 | 1037.4020175 | 1036.28 | STOP | -3.4261 |
| regime_exhaustion_shadow | 10:09 | LONG | 1035.98 | 1036.9168275 | 1036.28 | STOP | -2.8105 |
| regime_exhaustion_shadow | 14:17 | LONG | 1036.28 | 1037.0686725 | 1036.28 | STOP | -2.366 |

**민감도 — 이 행들을 뺐다면 (참고용, 실제 판정에는 미반영):**

| 채널 | n | 제외 | 현행 누적 hyp | 제외 시 | 차이 |
|---|---|---|---|---|---|
| hurst_gate_shadow | 286 | 1 | -1.8072 | 0.5588 | +2.3660 |
| joint_gate_shadow | 158 | 1 | -72.8463 | -70.4803 | +2.3660 |
| regime_exhaustion_shadow | 69 | 3 | -23.1523 | -14.5497 | +8.6026 |

> **이 채널은 판정을 바꾸지 않는다.** 초안에서는 "이길 수 없는 가상거래"로 보고
> 자동 제외하도록 짰다가 되돌렸다 — 전제가 틀렸다. 07-31 14:17 시장은 유동적이었고
> (vol 109) 실제로 진입했다면 체결됐을 것이며, TP1이 상한 밖이라 정말로 스톱만
> 맞았을 것이다. counterfactual은 모델링 결함이 아니라 **나쁜 거래를 충실히
> 시뮬레이션**한 것이고, 게이트의 손실 회피는 진짜다.
>
> 남는 질문은 측정 오류가 아니라 **공로의 출처**다 — 게이트가 자기 로직으로 막은
> 것인지, 신호가 우연히 가격상한에서 나와 구조적으로 질 수밖에 없었던 것인지.
> "옳았지만 이유는 달랐다"는 해석 문제라 판정을 조용히 바꾸지 않고 민감도만
> 병기해 주간회의에 올린다(§9).
>
> ⚠ **[18] RegimeExhaustionGate는 3건에 판정이 뒤집힌다**(SUPPORTS→REJECTS,
> 누적 hyp −1.75 → +6.85). 표본 3건이 권고를 뒤집는다는 사실 자체가 그 채널
> 결론의 근거가 얼마나 얇은지를 보여준다(372차 이상치 분해와 같은 교훈).

## [25] TP1 보호전환 offset A/B (404차 후속3 신설)

- 보호전환 76건 (제외 0건) / 거래일 13일

| 변형 | n | STOP | TP2 | 승률 | 누적pt | 중앙값 | 현행 대비 | 건별 우세 |
|---|---|---|---|---|---|---|---|---|
| current | 76 | 49 | 27 | 100.0% | +118.62 | +0.583 | +0.00 | 0/76 |
| breakeven | 76 | 46 | 30 | 39.5% | +102.10 | -0.070 | -16.52 | 3/76 |
| breakeven_plus | 76 | 47 | 29 | 100.0% | +107.41 | +0.131 | -11.22 | 2/76 |
| atr_lock_0.50 | 76 | 57 | 19 | 100.0% | +123.05 | +1.123 | +4.42 | 49/76 |
| atr_lock_0.75 | 76 | 58 | 18 | 100.0% | +128.58 | +1.191 | +9.95 | 49/76 |
| bar_range | 76 | 56 | 20 | 100.0% | +127.90 | +1.187 | +9.28 | 48/76 |

- **판정: SUSPENDED** — 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `FAIL`: 현행 초과 대안: atr_lock_0.50, atr_lock_0.75, bar_range

> ⚠ **사전등록 정직성 고지**: `breakeven` 변형은 이 채널 신설 **전에** 404차
> 후속3 조사에서 이미 1회 측정됐다(현행이 22/23 우세) — 재확인용이지 사전등록된
> 검증이 아니다. 사전등록 가치는 `atr_lock_0.50/0.75`·`bar_range`에 있다.
> ⚠ **FAIL이 떠도 즉시 적용 금지** — 단, **이유가 2026-08-05에 바뀌었다.**
> 0801의 제동(drop-max 부호역전·건별 우세 소수)은 표본이 23건/8일 →
> 49건/11일로 늘며 **전부 소멸했다**(drop-max +16.50 유지, 우세 28/49).
> 지금의 제동은 두 가지다 — ① **일자단위 t검정 p=0.255로 미유의**(313차),
> ② 판독규칙 (3): MW0601 표본이 아직 08-03 시작분뿐이라 단독 확정 불가.
> ⚠ **[432차] 2026-08-05 이전의 이 채널 수치는 전부 무효다** — offset이
> 보호전환 시점의 실제 유리이동을 넘어도 체결로 계상되던 결함이 있었다
> (atr_lock_0.75는 **57%가 체결 불가**). 클램프 후 Δ현행 +18.75 → **+8.04pt**.
> 이 채널에서 **일자단위로 유의한 것은 `breakeven`(p=0.021) 하나뿐이고**
> **방향은 음(−9.23pt)** 이다 — 즉 '본전 보호는 현행보다 나쁘다'만 확립됐다.
> ⚠ [12] tp1_trail_shadow가 기각한 "TP1 **이후** 트레일 폭"과 다른 질문이다
> — 이건 TP1 **시점**의 초기 보호 offset이다.
> ⚠ **TP2 거리 축은 아래 [25-B]에 따로 있다** — 위 표의 변형들은 전부 TP2를
> 현행(ATR×1.5)으로 고정한 상태에서 보호 offset만 바꾼 것이다.
> ⚠ **위 표는 MW0602 표본**이다(404차 후속3). MW0601은 당시
> `breakeven`이라 유효표본 0이었고, 406차 통일로 **MW0601 표본은 2026-08-03부터**
> 시작한다. 406차는 0801 결정을 무효화하지 않는다 — MW0601 독립 확인이
> 아직 없을 뿐이다. "모드 불일치 제외 N건"은 406차 투명성 기능이며 결함이 아니다.
>
> **두 PC 불일치 판독 규칙(사전등록, 관측 전 확정)**: (1) 같은 방향 + 둘 다
> drop-max 생존 → 승격 후보. (2) **부호 반대 → 기각 아닌 보류**, 두 값을 항상
> 병기(유리한 쪽만 인용 금지). (3) 한쪽만 표본 충족 → 단독 판정을 확정으로
> 쓰지 않고 "단일 PC 표본" 명시. (4) 어느 경우도 자동 적용 없음(§9).
> 근거: [23] tp1_geometry_shadow에서 이미 PC간 부호 역전 전례가 있다.

## [25-B] TP2 거리 A/B (MW0601 432차 신설)

- 보호전환 76건 / 거래일 13일 · 보호 offset은 현행(ATR×0.25) **고정**, TP2만 변형

| 변형 | n | STOP | TP2완주 | 승률 | 누적pt | 중앙값 | 최대손실 | 표준편차 | 현행 대비 | 건별 우세 | drop-max |
|---|---|---|---|---|---|---|---|---|---|---|---|
| current | 76 | 49 | 27 | 100.0% | +118.62 | +0.583 | +0.13 | 2.26 | +0.00 | 0/76 | +0.00 |
| tp2_0.75 | 76 | 41 | 35 | 100.0% | +78.85 | +0.716 | +0.13 | 1.09 | -39.77 | 8/76 | -42.02 |
| tp2_1.00 | 76 | 44 | 32 | 100.0% | +93.23 | +0.706 | +0.13 | 1.46 | -25.39 | 5/76 | -27.30 |
| tp2_1.25 | 76 | 47 | 29 | 100.0% | +106.55 | +0.614 | +0.13 | 1.86 | -12.07 | 2/76 | -14.46 |
| tp2_2.00 | 76 | 55 | 21 | 100.0% | +130.86 | +0.533 | +0.13 | 2.98 | +12.24 | 21/76 | +7.01 |

- **판정: FAIL** — 현행 초과 대안: tp2_2.00

> **왜 [23]이 아니라 여기인가**: [23]의 시뮬레이터는 TP1 도달 시 전량청산으로
> 종료해 TP2가 등장하지 않는다. 반면 이 채널은 이미 `보호스톱 vs TP2`를 재생한다.
> 더 중요한 건 **조건부 추정이 정확히 valid**하다는 점 — TP2를 바꿔도 stop·TP1은
> 불변이라 "TP1 도달 사건 집합"이 전 변형에서 동일하다. TP1 도달 건만 보는 것은
> 선택편향이 아니라 교란이 제거된 설계다.
>
> ⚠ **TP2 단축은 완주율↑ / 완주 1건당 이익↓의 교환이다.** 누적pt만 보고 판단하지
> 말 것 — `TP2완주` 건수와 `중앙값`·`표준편차`가 함께 움직이는지 확인해야 한다.
> ⚠ `tp2_2.00`은 **대조군**(넓히는 방향)이다. 결과가 거리에 대해 단조라면 진짜
> 거리 효과이고, 특정 값에서만 튀면 표본 우연이다 — 단조성을 먼저 볼 것.
> ⚠ **FAIL이 떠도 즉시 적용 금지**(§9). 사전등록 판정보조 ①drop-max ②건별우세
> ③MW0601×MW0602 교차를 전부 통과해야 주간회의 승격 후보다. [25] 본채널이
> 바로 ①에서 무너진 전례가 있다(atr_lock_0.75 +0.92→−1.33pt).
> ⚠ 이 판정은 [25] 본채널(offset 축) 판정과 **무관**하다 — 본채널 합격선 무변경(§9-4).

## [47] 시뮬레이터 재현충실도 게이트 (435차 신설 · 메타 채널)

- 판정: **⏸ SUSPEND(하위 정지)** — 재현 실패 — 총합 부호 불일치 (시뮬 -26.80 vs 실제 +27.86 pt) (n=149/17일) → 하위 채널 판정 정지
- 재현 편향(중앙) **+0.014R** / 평균 -0.069R · 총합 시뮬 -26.80 pt vs 실제 +27.86 pt · 부호일치=False

> 기하 A/B 채널들은 전부 같은 재생기 가정을 공유한다 — ① 1분봉 고저가만 본다
> ② TP2에서 종료한다 ③ TP3·4단계 트레일링·신호소멸청산을 모델링하지 않는다.
> 그 가정이 실제를 재현하지 못하면 `delta_vs_current`의 **부호까지 뒤집힌다**
> — 432차 후속2 실측: 러너 프리미엄 보정만으로 [25-B] `tp2_2.00`이
> **+14.76 → −12.13pt**(−61만원)로 역전됐고, 4채널 결론 격차 합계는
> **61.51pt = 307만원**이다.
> 
> ⏸ **아래 채널의 판정을 정지했다** — `quantile_tp_shadow`, `tp1_geometry_shadow`, `tp1_protect_offset_shadow`, `hurst_threshold_shadow`
> **삭제가 아니라 정지다**: 원 판정은 `verdict_raw`로, 수치는 그대로 보존된다.
> 소스 데이터도 `main.py`가 계속 기록하므로 소급 재실행이 가능하다.
> **해제 조건**: 재생기에 TP3·트레일링을 편입해 재현이 회복되면 **자동 PASS**
> — 사람이 "재검토하기로 했는데 안 함"으로 방치할 여지가 없다.
> ⚠ **사전등록 정직성**: 최초 SUSPEND는 432차 후속2에서 **이미 본 결과**의
> 코드화다([25]의 `breakeven`과 같은 취급). 사전등록 가치는 **회복 판정**에 있다.
> ⚠ 정본 재생기로 [23-B]를 쓴다(포지션 단위 조인이 되는 유일한 채널). 다른
> 채널은 같은 세 가정을 공유하므로 **간접 추론**이다.

## [48] 봉중 하드스톱 경로 건전성 (435차 신설 · 시뮬 무관)

| 경로 | n | 합계pt | 평균 | 유리비율 | 부호검정 p | 거래일 |
|---|---|---|---|---|---|---|
| 봉중 하드스톱 | 13 | -24.51 | -1.885 | 13/13 (100%) | 0.00024 | 3 |
| 틱 하드스톱 | 78 | +5.18 | +0.066 | 29/78 (37%) | 0.03079 | 9 |
| 목표(TP1/TP2/기타) | 18 | -0.46 | -0.026 | 10/18 (56%) | 0.81453 | 7 |

- 판정: **⏳ INSUFFICIENT** — 봉중 경로 표본 부족 (n=13<25 또는 거래일=3<8)
- (음수 = 유리) 미태깅 재분류 48건 — `hint_source`는 423차부터 기록된다

> **틱 경로는 대칭이고(정직) 봉중 경로만 편향된다.** 메커니즘은 두 겹이다 —
> ① `price_hint`가 `min(_prev_stop_price, bar_high)`라 **허구의 스톱가**이고
> (주문은 시장가라 손익은 무관, 슬리피지 지표만 오염) ② 유령 하드스톱은
> "봉의 극값이 스톱 조임보다 먼저 발생"할 때만 생기고 스톱 조임은 TP1이
> 전제라 **이익 중인 포지션에서만 발동**한다 — 편향이 결정론적이다.
> ⚠ **손익 영향은 작다** — 반사실 재생 기준 유령 순기여는 9건 통산 ≈+3.0pt고,
> 08-05 억제 5건은 **억제가 오히려 +0.38pt 유리**했다. 424차 억제는 옳다.
> ⚠ 사전등록 정직성: 첫 관측(13/13, p=0.00024)은 신설 전에 이미 봤다 —
> 재확인용이며, 가치는 **억제 후 회복 판정**에 있다(억제 후 표본 1건).

## [49] 페이오프 기하 상시 감시 (435차 신설 · 시뮬 무관)

| 기준 | n | 승률 | 평균승 | 평균패 | 손익비 | 손익분기승률 | edge_gap |
|---|---|---|---|---|---|---|---|
| 원화(pt) | 149 | 65.1% | +1.991 | -3.178 | 0.626 | 61.5% | **+3.62%p** |
| 위험조정(R) | 149 | 65.1% | +0.507 | -0.940 | 0.539 | 65.0% | **+0.12%p** |

- 판정: **✅ PASS** — edge_gap > 0 (원화 +3.62%p · 위험조정 +0.12%p) ⚠ 두 기준 격차 3.50%p > 3.0 — 결과가 소수 고변동일에 집중됐을 가능성
- 포지션 149건 / 레그 160건 (다중레그 포지션 11건) — ⚠ **417차: 포지션 단위로 병합**

> **현행 기하가 애초에 이길 수 있는 구조인가**를 묻는 유일한 채널이다
> ([24]는 반납만, [25]는 offset만, [23-B]는 대안 기하만 본다).
> 설정 직독: 하드스톱 `ATR×1.50` / 보호스톱(qty=1) `ATR×0.25`(호라이즌 무관 상수)
> → 보호전환에 걸린 승리만 놓고 보면 **손익분기 승률 85.7%**. 러너가 그 격차를 메운다.
> TP1은 374/387차에 호라이즌별로 분화됐는데(0.3/0.5/0.7) lock은 339차 상수라
> **유지율이 호라이즌에 반비례**한다(1m 83% / 3m 50% / 5m 36%).
> ⚠ 두 기준이 갈리면 **결과가 소수 고변동일에 집중**됐다는 신호다 — 그래서 둘 다 찍는다.

## [33] 급행풀스톱 판별자 발굴 — 재실행 게이지 (421차 후속10, 알림 전용)

- 마지막 Phase A 실행: **2026-08-03** (결과: BH FDR 10% 통과 0개)
- 현재 표본: 포지션 149 / FAST **32** / 거래일 17 (그중 **유효 12일**)

| 트리거 | FAST | 유효 거래일 | 도달 |
|---|---|---|---|
| 중간(재실행 검토) | 32 / 30 ✅ | 12 / 11 ✅ | 🔔 **도달** |
| 본(재실행 권고) | 32 / 40 … | 12 / 15 … | — |

> 🔔 **중간 트리거 도달 — 재실행 검토 시점이다.** 본 트리거까지
> 기다릴지 지금 한 번 돌려볼지 주간회의에서 판단할 것.

> **유효 거래일**이 병목이다 — 일자 내 순열검정은 FAST와 OK가 **둘 다 있는
> 날**만 정보를 내므로 전체 거래일이 아니라 그 교집합이 실질 표본이다
> (초판 12일 중 7일). 실측 속도도 FAST 7.0건/주 vs 유효거래일 2.4일/주였다.
> 판정 채널이 아니므로 verdict를 내지 않는다.

## [30] toxicity_score 재보정 후 밴드 분포 (MW0601 419차, P0)

- 재보정 배포일: **2026-08-03** / cancel_churn ceiling: **0.42** (구값 0.08)
- 집계 분봉: 1923 (백필 생성 행 제외 — 418차)

| 구간 | block | reduce | pass | cancel_stress 포화 | score p50 |
|---|---|---|---|---|---|
| 재보정 **전** 실측 (07-24~07-31, n=2,229) | 23.3% | 76.4% | **0.27%** | **100.0%** | 0.3475 |
| 380차 설계목표 | 0.7% | 11.8% | 87.5% | — | — |
| **이번 주 실측** | 1.1% | 58.1% | 40.7% | 0.3% | 0.241 |

- cancel_churn_ratio 실측: p50=0.2439 / p99=0.3749 (ceiling 0.42)
- **판정: PASS**

> **왜 이 채널이 생겼나**: 380차가 `cancel_churn_ratio` ceiling을 0.08로
> 잠정 설정하며 코드 주석에 "라이브 섀도 관찰 후 재보정 필요"라고 **스스로**
> **예고**했으나 실행되지 않았다. 라이브 실측 p50=0.2649로 ceiling의 3.3배 —
> **초과율 100%** 라 가중 0.20짜리 성분이 전 분봉에서 1.0으로 포화해 score에
> 상수 +0.20을 더하는 죽은 항이 됐다(중앙값 score 0.3475의 58%).
> 그 오프셋 때문에 게이트가 사실상 상시 발동(pass 0.27%) 상태였다.
> ⚠ **FAIL이어도 임계값을 자동으로 바꾸지 말 것** — block 0.45 / reduce 0.28은
> 전 채널 판정에 영향을 주므로 §3 원칙대로 주간회의 결정 + DECISION_LOG 기록이
> 선행돼야 한다. 또한 이 재보정은 **진입을 늘리는 방향**이라(시뮬레이션 기준
> block 23.3%→8.6%) CLAUDE.md 실전전환기준 ⑧과 함께 읽어야 한다.

## [31] ToxicityGate reduce 연속 배수 섀도 (MW0601 419차, P1)

- reduce 밴드 체결 진입: **39건**
- 섀도 배수 분포: min=0.4605 / p50=0.793 / max=0.9, **평균=0.7634** (실적용 상수 0.70)
  - 평균이 0.70에서 크게 벗어나면 **노출 중립 설계가 깨진 것**이다 —
    앵커(`TOXICITY_REDUCE_MULT_SHADOW_HI/LO`) 재도출 필요.
  - 현행 앵커 도출일: **2026-08-03** (421차 재도출, HI=0.81/LO=0.36). 이 날짜 이전 표본은 구 앵커(0.90/0.45)로 계산된 값이라 섞어 읽지 말 것.
  - ⚠ 이 평균은 **게이트 이벤트** 모집단이다. 앵커 도출에 쓴
    **봉** 모집단과 값이 다르다(08-03 실측 0.8205 vs 0.7894) —
    절대값 판정이 아니라 추세 감시용으로 읽을 것.
- tox 스테이지에서 수량이 달라진 진입: **3/39 (7.7%)** (기준 20%)
- **판정: PASS** — 수량 상이 7.7% < 20% — 양자화에 흡수돼 실적용 실익 없음(현행 상수 유지)

> **PASS가 "좋다"는 뜻이 아니다** — 이 채널의 PASS는 "연속화해도 수량이
> 안 바뀌니 현행 상수를 유지하라"는 뜻이다. 상수 0.7이 정보를 폐기하는 것은
> 실측으로 확정돼 있다(reduce 밴드 n=1,614에서 향후 15m 평균스프레드가 5분위
> 2.8→3.8틱 단조 증가, Spearman rho=+0.319 t=13.48). 다만 사이징 체인이 8단
> `max(1, round())`로 양자화하고 실체결이 1~2계약에 묶여 있어 그 정보를 살릴
> 여지 자체가 없을 수 있고, 그렇다면 복잡도만 늘리는 변경이므로 하지 않는 것이 맞다.
> ⚠ `qty_after_*`는 **tox 스테이지 국소값**이다 — 하류(L2·Hurst·Degraded·상한)를
> 재시뮬레이션하지 않는다. 두 값이 같으면 최종 수량도 같지만(입력 동일), 다르다고
> 최종 수량이 반드시 달라지는 것은 아니다.
> ⚠ 현행 앵커는 **재보정 전** 분포로 도출됐다 — [30]이 새 분포를 확정하면
> 재도출할 것. 그전 판정은 잠정이다.

---

## [34] meta "size 0" 무시 (MW0601 422차 후속)

**모델이 "베팅하지 마라"고 한 신호로 실제 진입한 건**의 손익이다.
`_make_result()`는 `conf < 0.5`에서 size를 **0.0**으로 내는데, 액션 밴드가 덮는다 —
`reduce`는 `or 0.5`(→0.5), `take`는 `max(0.9, …)`(→**0.9**, 거의 풀사이즈).

> **임계 0.5는 임의 상수가 아니다.** `conf`는 4급 품질레이블(Q0~Q3, 가중치 0/⅓/⅔/1)의
> 기대값이고 `conf = ⅓(1−a)(1−h) + ⅔a(1−h) + a·h` 이다. **a=0.5를 넣으면 고신뢰비중**
> **h와 무관하게 정확히 0.5** — 즉 `conf<0.5 ⟺ 적중률<50% 추정`이다.

- 계측 시작: `2026-08-04` 이후 결정만 (그 이전은 raw 복원 불가 → NULL)
- 미계측 0건 / 계측 68건 · 그중 raw==0 **29건** (42.6%)

| 밴드 | 왜곡 | raw0 진입 | 매칭 | 누적손익 | 평균 | 승률 | 거래일 | 음수일 |
|---|---|---|---|---|---|---|---|---|
| reduce | 0.0→0.5 | 14 | 14 | -212,729원 | -15,195원 | 64.3% | 4 | 2 |
| take | 0.0→**0.9** | 15 | 15 | -209,238원 | -13,949원 | 66.7% | 4 | 3 |
| _합계 | — | 29 | 29 | -421,967원 | -14,551원 | 65.5% | 4 | 2 |

> **밴드를 합산해 읽지 말 것.** `take`의 왜곡(0.0→0.9)이 `reduce`(0.0→0.5)보다
> 크다 — 한 숫자로 합치면 큰 왜곡이 작은 쪽에 희석된다. 합계 행은 판정용이지
> 해석용이 아니다.
> 
> **판정 시 교란 3종을 반드시 함께 읽을 것** (settings `[34]` 주석):
> (a) `recent_accuracy`가 meta 입력이라 conf는 **자기상관**을 갖는다 — "size 0
> 구간이 나빴다"가 사전 판별력인지 나쁜 구간의 뭉침인지 구분되지 않는다.
> (b) meta 학습 스트림에 **퇴역한 30m(20.8%)과 FLAT 예측(20~45%)이 혼입**된다
> — conf 기준선이 그날 검증된 호라이즌 구성에 따라 흔들린다.
> (c) LR이 `class_weight='balanced'`라 conf가 실제보다 **높게** 나올 수 있다
> — `conf<0.5`는 오히려 보수적 추정일 수 있다.
> 
> FAIL이어도 **자동 전환 금지** — "안 B"(raw==0 → action skip 강등)는 액션 축
> 변경이라 라이브 진입 동작이 바뀐다. §9 사전등록 원칙대로 주간회의 안건이다.

---

## [35] 유령 하드스톱 — 결함인가 알파인가 (MW0602 424차 후속)

423차 가드가 `qty>=2`의 TP1 손익분기 경로를 우회해 유령 청산이 났다.
**일부러 고치지 않고 재고 있다** — 손익 부호가 예상과 반대이기 때문이다.

> **[439차 정정] "계속 난다"는 더 이상 사실이 아니다.** 431차의 MAX_CONTRACTS
> 10→3 + 게이트 체인 재구성으로 `qty>=2` 진입이 사라져 유령 청산 모집단이
> 소멸했다(2026-08-05 이후 `live_suppressed=0` **0건**). 아래 근거표는
> **그 시절의 기록**이며 현행 상태가 아니다 — 현행은 [35-M] 미러를 볼 것.

| 근거일 | 건수 | 실현 | 반사실(정상 가드) |
|---|---|---|---|
| 2026-08-03 (423차 실측) | 8 | +1.42pt | 5건 유리 / 3건 불리 |
| 2026-08-04 (qty≥2) | 3 | **+8.76pt (+433,609원)** | **0pt** |

> 08-04의 +433,609원은 그날 순익 +752,561원의 **57.6%**다. 정상 동작이었다면
> 약 +316,000원이었다. 유령 판정은 *"봉 고가가 스톱을 스쳤으나 현재가는 유리하게
> 되돌아왔다"*에서만 성립해 **시장가가 스톱보다 좋은 국면만 고른다** — 스파이크-
> 되돌림 익절을 우연히 구현하고 있을 수 있다.

반사실 정의(관측 전 고정): 억제했다면 포지션은 유지되고 **판정에 실제로 쓰인**
**스톱(`stop_eval`)** 으로 계속 간다 → 이후 분봉에서 닿으면 그 가격, 15:10까지
안 닿으면 그날 마지막 종가. `delta_pt = 실현 − 반사실`, (+)면 유령이 유리.

- ⚠ **구조적 판정불가** — 유령 청산(`live_suppressed=0`) 0건 — 그러나 적재는 정상이다(계측 시작 이후 16행, 그중 억제 15행 / 3거래일). 원인은 배선이 아니라 **모집단 소멸**이다: 유령 청산은 423차 가드를 우회하던 qty>=2의 TP1 손익분기 경로에서만 났는데(main.py `tp1_breakeven`), 431차의 MAX_CONTRACTS 10→3 + 게이트 체인 재구성으로 qty>=2 진입 자체가 사라졌다. 남은 행은 전부 `arm_tp1_qty1_mode`(가드가 정상 배선된 경로)라 주판정 필터를 통과하는 행이 **기다린다고 생기지 않는다**. → 아래 **미러 서브표본**(억제된 쪽)이 같은 Δ를 반대 방향에서 재는 유일한 경로다.
  - 이것은 "표본이 모이는 중"이 **아니다**. 🔴 NO-DATA(배선 점검)와도 다르다 — 적재는 정상이고 주판정 **필터를 통과하는 모집단이 사라졌다**. [28] `sizing_inversion_watch`와 같은 유형이다(439차).

### [35-M] 미러 서브표본 — 억제된 쪽 (439차 신설, 관찰 병기)

주판정이 보는 `live_suppressed=0`(유령 청산 발생)이 431차 이후 사라졌으므로,
**같은 Δ를 `live_suppressed=1`(가드가 억제해 버틴 건)에서 반대 방향으로** 잰다.
반사실(관측 전 고정): 유령 청산은 시장가이므로 판정 시점 `cur_price` 체결로 본다.
**부호 규약은 주판정과 같다 — (+)면 유령이 유리.**

- 억제 **15건 / 3거래일** (계측 시작 이후 적재 16행, 다중레그 0건)
- 유령청산했다면 +24.78pt vs 버틴 실제 +29.08pt → **delta -4.30pt** (평균 -0.287 / 중앙값 +0.580, 유령 유리 9/15건)
- 유령청산 손익이 양수인 건: **15/15** — 스파이크-되돌림 익절 가설의 직접 지표
- 일자단위(313차): 1/3일 유령 우세, 평균 -0.191pt, **부호검정 p=1.0**
- 🔴 **평균과 중앙값의 부호가 다르다** (-0.287 vs +0.580) — 소수 관측이 평균을 끌고 있다는 뜻이다. **평균만 보고 결론 내지 말 것**(313차).

| 조이기 경로 | 건수 | delta 합 |
|---|---|---|
| `arm_tp1_qty1_mode` | 15 | -4.30pt |

> ⚠ **주판정과 합치지 않는다 — verdict도 내지 않는다.** 세 가지가 다르다:
> ① **반사실 비대칭** — 주판정의 반사실은 "`stop_eval`로 계속"이라는 단일
> 규칙이지만, 미러의 실제값은 억제 이후 **모든 청산 로직**(TP2·트레일·15:10
> 강제청산)의 합이라 그것들과 교락돼 있다. "억제의 순수 효과"가 아니다.
> ② **시점 교락** — 두 부분표본은 처치 시점이 갈린다(유령 발생기 vs 억제기).
> 436차가 `827bd04` 교락 때문에 [50]을 PRE/POST 비교로 등록하지 **않은** 것과
> 같은 함정이다.
> ③ **`cur_price` 근사 편향** — 실측 유령 청산의 체결 슬리피지는 평균
> −2.708pt(유리)였으므로 이 근사는 유령을 **과소평가**한다(보수적 방향).

> 판정으로의 승격은 §9 주간회의 안건이다 — 합격선을 여기서 만들지 않는다(313차).

> **판정 전에 가드를 켜지 말 것** — 켜는 순간 이 표본이 더 안 쌓인다.
> 라이브는 계측만 하도록 배선돼 있다(`main.py` tp1_breakeven →
> `mark_stop_tightened_shadow`). 전환은 그 한 줄을 `_mark_stop_tightened`로
> 바꾸는 것이고, **SUPPORTS_HYP면 전환이 아니라 정책 승격**이 처방이다.

---

## [36] 체크리스트 승격 경로별 우열 (MW0602 424차 후속)

0803 정기점검 P2의 *"앙상블 X를 A로 올리는 경로에 하한 조건 추가"* 제안을
검정한다. **0804 실측은 정반대였다** — 그래서 그 제안은 이 채널 판정까지 보류다.

| 경로 | 포지션 | 거래일 | 승률 | 평균 | 누적 |
|---|---|---|---|---|---|
| **X→A** | 9 | 4 | 88.9% | 82,646원 | 743,817원 |
| **C→A** | 47 | 7 | 63.8% | -18,262원 | -858,330원 |
| **C→C** | 36 | 6 | 63.9% | -23,376원 | -841,541원 |

> `raw_grade`가 NULL인 구버전 행은 경로 판별이 불가능해 **전량 제외**한다 —
> 승격/미승격을 섞으면 이 채널이 재려는 값을 못 잰다.

---

## [37] mean-revert 적자 — 일자단위 재검정 (MW0602 424차 후속)

⚠ **[29] mean_revert_size_watch와 모집단이 같다. 중복이 아니라 브레이크다.**
[29]는 포지션 단위 승률 격차로 판정하는데, 0804 실측에서 두 축이 갈렸다:

| 축 | 결과 |
|---|---|
| 포지션 누적 | mean-revert 54건 **-1,455,546원** (neutral +2,303,166 / trend +778,965) |
| 일자단위 짝지은 검정 | 7거래일, 평균차 -1.63pt, t=-1.13, 부호 2/7, **p=0.4531 (미유의)** |

누적 -145만원은 극적으로 보이지만 일자단위로는 재현되지 않는다 — 313차가
막으려던 바로 그 패턴이다(372차 PSI 재보정의 이상치 착시와 동형).

- mean-revert **89건** 누적 -2,284,103원 / 그 외 68건 누적 2,441,688원
- 짝지은 거래일 **10일** (단일버킷일 9일 제외 — 그날은 레짐 통제가 안 된다)
- 평균차 -1.27pt · MR 우세 3/10일 · **부호검정 p=0.3438** · t=-1.269

- **권고**: 일자단위로는 유의하지 않다 (평균차 -1.27pt, p=0.3438) — 누적 -2,284,103원이 커 보여도 **조치 금지**. [29]가 FAIL을 내더라도 이 채널이 PASS인 동안은 보류가 사전등록된 판독 규칙이다

> **판독 규칙 (관측 전 고정 — settings 채널 주석과 동일)**
> 
> | [29] | [37] | 조치 |
> |---|---|---|
> | FAIL | PASS | **보류.** 누적 수치만으로 움직이지 말 것 |
> | FAIL | SUPPORTS_HYP | 두 축 합치 — 주간회의 안건 승격 가능 |
> | PASS | SUPPORTS_HYP | 승률은 같은데 손익 크기가 갈림 — 재조사 |
> 
> 처방 축은 [29]와 동일하다 — qty=1에서 사이즈 축소는 no-op이므로
> **등급 강등/임계값 이동** 축으로 설계할 것(`sizing_prescription_axis` 참조).

---

## [38] ProfitGuard-L1 피크 트레일링 (MW0602 426차)

**희귀사건 채널이다.** 0804 점검이 L1을 "오늘 최대 공로자"로 적었으나
검증에서 **과장으로 확인**됐다 — 캠페인 전체에서 구속력 있는 발동은 1회뿐이고,
그 하루의 차단 40건 반사실은 TP1 24 / STOP 16, 누적 **-1.87pt(-93,492원)** 로
박빙이었다. 판정을 서두르지 않도록 min_activations를 걸어 둔다.

> 🔴 **운영 파라미터가 코드에 없다.** 라이브 값은 `data/profit_guard_prefs.json`에서 오며
> 대시보드에서 **장중 변경이 가능**하다 — 판정 기준선이 코드 리뷰로
> 보이지 않고 세션 중에 바뀔 수도 있다는 뜻이다.
> 
> | | 발동금액 | 비율 |
> |---|---|---|
> | **운영(prefs)** | **700,000원** | **20%** |
> | 코드 기본값 | 2,000,000원 | 35% |
> 
> prefs 최종수정: 2026-08-05 10:32:43 · **아래 수치는 전부 운영값 기준**이다.

- 발동 2회 (그중 **구속 1회 / 1거래일**) · 전체 19거래일

| 거래일 | 피크 | 발동 | 발동후 진입 | 그 손익 | 구속? |
|---|---|---|---|---|---|
| 2026-07-20 | 1,458,543원 | 14:56 | 0건 | 0원 | 아니오 |
| 2026-08-04 | 1,067,916원 | 13:07 | 0건 | 0원 | **예** |

> **발동했다고 다 같은 발동이 아니다.** 발동 시각 뒤에 진입 기회가
> 없었으면(장 마감·14:50 신규금지) 무해무익이다 — 실제로 07-20이 그랬다
> (14:56 발동, 마지막 진입 14:33). 그래서 표본 단위는 **구속 발동**이다.

- 차단 신호 반사실(30분 창): **40건** · TP1 24 / STOP 16 / 무결정 0
- 누적 **-1.87pt** (건당 -0.047pt) — **(+)면 차단이 손해, (-)면 이득**
- 일자단위(313차): 0/1일, p=1.0

**(d) 재개 조건 — 현재는 재개가 없다.** `_TrailingGuard.is_halted`가
`reset_daily()`까지 유지돼 발동일은 장 마감까지 신규진입이 막힌다.
아래는 "발동 N분 뒤 재개했다면 그 뒤 차단분이 얼마였나"이다.

| 재개 지연 | 차단 유지분 | 그 손익 | 재개 후 진입분 | 그 손익 |
|---|---|---|---|---|
| **0분** (현행) | 0건 | +0.00pt | 40건 | -1.87pt |
| **15분** | 11건 | -22.25pt | 29건 | +20.38pt |
| **30분** | 18건 | -19.68pt | 22건 | +17.81pt |
| **60분** | 33건 | -8.69pt | 7건 | +6.82pt |

> **두 열을 함께 읽어야 한다.** "차단 유지분 손익"이 (-)면 그 구간을
> 막은 것이 이득이고, "재개 후 진입분 손익"이 (+)면 재개가 이득이다.
> 즉 **(-, +) 조합이 나오는 지연이 최적**이다 — 나쁜 구간은 막고 좋은
> 구간은 되찾는다.
> 
> ⚠ **신호 수 ≠ 진입 수다.** 연속 분봉의 같은 방향 신호가 그대로 세어져
> 있고, 실제로는 포지션 보유·쿨다운·14:50 신규금지가 걸린다. 그래서 위
> pt 합계는 **상한**이지 기대손익이 아니다([6]·[7]과 같은 한계).
> 반사실 자체도 상방은 TP1에서 자르고 하방은 스톱까지 세는 비대칭이 있다.

**(c) 임계 스윕 — 전 거래일 소급 재현.** 이 축은 반사실이 아니다:
발동하지 않았던 날은 그 뒤 진입이 실제로 체결돼 **실현손익이 남아 있다.**

| 발동금액 | 비율 | 발동 | 구속 | 차단될 포지션 | 지킨 금액 |
|---|---|---|---|---|---|
| 500,000 | 20% | 2 | 0 | 0 | 0원 |
| 500,000 | 30% | 1 | 0 | 0 | 0원 |
| 500,000 | 35% | 1 | 0 | 0 | 0원 |
| 500,000 | 50% | 0 | 0 | 0 | 0원 |
| 1,000,000 | 20% | 2 | 0 | 0 | 0원 |
| 1,000,000 | 30% | 1 | 0 | 0 | 0원 |
| 1,000,000 | 35% | 1 | 0 | 0 | 0원 |
| 1,000,000 | 50% | 0 | 0 | 0 | 0원 |
| 1,500,000 | 20% | 0 | 0 | 0 | 0원 |
| 1,500,000 | 30% | 0 | 0 | 0 | 0원 |
| 1,500,000 | 35% | 0 | 0 | 0 | 0원 |
| 1,500,000 | 50% | 0 | 0 | 0 | 0원 |
| 2,000,000 | 20% | 0 | 0 | 0 | 0원 |
| 2,000,000 | 30% | 0 | 0 | 0 | 0원 |
| 2,000,000 | 35% | 0 | 0 | 0 | 0원 |
| 2,000,000 | 50% | 0 | 0 | 0 | 0원 |

> "지킨 금액"이 (+)면 차단이 손실을 막은 것, (-)면 이익을 놓친 것이다.
> **전 격자에서 0이면 L1은 사실상 무발동**이라는 뜻이다 — 임계를 조이는
> 논의보다 "이 레이어가 지금 무엇을 하고 있는가"가 먼저다.

- 구속 발동 1건 / 1거래일 (필요 5건 / 5일) — 관찰 단계. 실측 발동빈도로는 약 4개월 스케일이다

> **판정을 서두르지 말 것.** 실측 발동빈도(16거래일에 구속 1회)로는
> `min_activations=5`가 약 **4개월** 스케일이다([8] KellySkip과 같은 계열).
> 그 사이에 판정을 흉내내면 단일일 관측이 정책이 된다 — 0804에 실제로
> 그럴 뻔했고, 이 채널은 그 재발을 막으려고 만들었다.

---

## [39] confidence 판별력 (MW0602 427차)

**min_conf 자체가 아니라 그 선행조건을 잰다.** 0804 §P2는 "동적 min_conf가
랜덤 기준선(0.33)까지 내려앉아 무력화됐다"를 문제로 제기했는데, 조사 결과
**문제 제기의 방향이 틀렸다** — 게이트는 정보 없는 신호를 걸러낼 수 없다.

| 0804 조사 실측 | 결과 |
|---|---|
| min_conf 0.40 상향 | 손익 **−407,558원** |
| min_conf 0.45 상향 | 손익 **−749,942원** |
| 잘려나간 진입 승률 | **62~63%** = 전체 승률 **63.0%** |
| 설계값 0.54 복원 시 | 진입 81건 → **1건** (진입 conf 최댓값 0.579) |

> 잘려나가는 진입의 승률이 전체와 같다는 것이 직접 증거다 — 게이트가 품질
> 필터가 아니라 **무작위 샘플러**로 작동한다. 그래서 질문을 바꿨다:
> "min_conf를 얼마로 할까"가 아니라 **"conf가 정보를 갖기 시작했는가"**.

**(B) 모델축** — `predictions.confidence` vs `correct` (두꺼운 축)

- n=**17,394**건 / 24거래일 · 퇴역 호라이즌 ['30m'] 제외 7,879건
- 하위절반 33.6% vs 상위절반 34.0% → **격차 +0.45%p** (임계 3.1%p)
- 일자 층화(같은 날 안에서 상/하위 분할): 15/24일 양수, **부호검정 p=0.3075**

> ⚠ **30m을 제외한다.** 296차가 앙상블·게이트에서 퇴역시킨 호라이즌인데
> `predictions`에는 계속 쌓인다. 실측으로 `conf≥0.60` 구간의 **88%가 30m**
> 이라, 포함하면 퇴역 모델이 판정을 끌고 간다.

**(A) 앙상블축** — min_conf가 **실제로 게이트하는 값** (얇은 축)

- 승 101건 평균 conf **0.4065** / 패 56건 **0.3969** → **격차 +0.0096** (임계 0.025 · Cohen d=0.16)
- 진입 conf 표준편차 0.0601 — 임계 0.025은 약 0.42 sd에 해당한다
- 일자단위(승·패가 둘 다 있는 날): 6/15일, **p=0.6072**

> ⚠ **conf 스케일 불연속 — 2026-07-31 (앙상블 보정기 미적용(passthrough) 전환)**
> 이 창은 경계를 걸친다. `ensemble_decisions.confidence`의 **산출 경로가 달라졌으므로 경계를 넘는 수준 비교는 무효**다.
> 원인: 403차 축퇴 가드·도달불가 폴백 배포(827bd04·e594cee, 2026-07-31)
> 실측: 보정 미적용률 07-29 0.9% / 07-30 2.7% / 07-31 30.8% / 08-03 92.2% / 08-04 98.6%  ·  평균 conf 0.316→0.491(+55%)  ·  confidence_raw는 0.491→0.515로 거의 무변화
> raw conf의 1m 적중 순위 AUC=0.489(<0.5, 역방향)이므로 상승은 정보량 증가가 아니다. 427차 [39] REJECTS_HYP와 모순되지 않는다.
> 일자단위·층화 지표는 이 수준 이동에 면역이다 — **그쪽을 보라.**
> **이 채널에 미치는 영향**: 위 `격차`·`표준편차`는 경계 양쪽의 서로
> 다른 스케일을 한 통에 넣은 값이라 **수준·분산이 오염**된다. 반면
> 바로 아래 **일자단위(같은 날 안에서 승/패 비교)는 면역**이다 —
> 하루 안에서는 스케일이 하나이기 때문이다. **판정은 일자단위를 볼 것.**
> 
> **모델축(`predictions.confidence`)은 이 경계에서 계단 변화가 없다**
> — 430차 실측 1m/3m/5m 07-27~08-04 전 구간 0.36~0.41로 연속.
> 호라이즌 보정기도 **같은 축퇴 가드를 쓰지만**(같은 클래스다) 영향이
> 작은 이유는 입력 분포가 다르기 때문이다: 앙상블축에는 가중치 붕괴가
> 만드는 인위적 `raw≈1.0` 행이 21%나 있어 적용/미적용 차이가 0.33↔0.85로
> 벌어지지만, 호라이즌 raw는 기저율 근처(~0.33~0.40)라 보정을 걸든 말든
> 출력이 비슷하다. **"가드를 안 쓴다"가 아니라 "입력이 극단이 아니다"** —
> 붕괴 구조가 바뀌면 모델축도 영향권에 들어올 수 있으므로 재확인할 것.
- 진입↔결정 매칭 **157/157 (100.0%)** · 오프셋 분포 -1분 34건 / 0분 123건

> **`-1분` 오프셋은 결함이 아니라 정상이다.** 파이프라인이 `T:52` 근방에
> 주문을 내고 체결 확인이 `T+1:00~:09`에 도착하면 `trades.entry_ts`(체결
> 시각)가 결정 분보다 1분 뒤가 된다. 427차 초판은 분 단위 정확 조인이라
> **이 19건을 통째로 잃고 매칭률 81%로 보고했다** — 데이터가 없는 게
> 아니라 키가 어긋난 것이었다(방향은 100/100 일치).
> 
> **`-1분` 비중이 갑자기 늘면 체결 확인 지연이 커진 것이다** — 집행 품질
> 신호로 함께 볼 것.

- **권고**: 판별력 없음 — 모델축 격차 +0.45%p(임계 3.1) / 앙상블축 +0.0096(임계 0.025). **min_conf 조정은 무의미하다**: 정보 없는 신호를 조이면 무작위로 덜어낼 뿐이다(0804 스윕 실측 — 잘려나간 진입 승률 62~63% = 전체 63.0%). 선행조건은 §P1(방향모델 랜덤) 해소이며, 새 정보원이 들어오면 이 채널이 먼저 반응한다

> **임계는 검출력에서 유도했다**(관측 전 고정). 모델축은 n≈14,770 절반분할의
> 격차 SE가 0.78%p라 검출하한(1.96SE)이 1.52%p이고, 임계 3.1%p는 그 **2배(3.04%p) 이상**이다 —
> 매주 들여다보는 채널이라 경계선 값이 우연히 넘는 것을 막을 여유가 필요하다.
> 앙상블축 0.025은 진입 conf sd 0.0556 기준 **Cohen d≈0.45**로, 이보다 작으면
> 승/패 conf 분포가 거의 완전히 겹쳐 어떤 임계도 둘을 가르지 못한다.
> 
> **두 축 모두 효과크기 AND 일자단위 검정을 함께 요구한다.** 0804에
> pooled z=−4.95가 일자단위로는 p=0.42였던 전례를 그대로 겪었다
> (표본의 56%가 하루, 88%가 퇴역 30m).
> 
> **SUPPORTS_HYP로 바뀌는 날이 min_conf를 다시 논할 시점이다.** 그때도
> 설계값 0.54~0.67을 그대로 쓰면 안 된다 — 구 conf 분포 기준이라 진입이
> 사라진다. 그 시점의 분포로 새로 잡을 것.

---

## [40] 방향 선택의 가치 (MW0602 428차)

**같은 진입 시각·같은 청산 기하**에서 시스템의 실제 방향과 **동전던지기**를
비교한다. 두 팔이 같은 시뮬을 통과하므로 차이는 오직 **방향 선택의 기여분**이다.
구현: `scripts/random_entry_control.py` (오프라인·읽기 전용).

- 표본: 진입 **157건** 중 157건 시뮬 가능 / **19거래일**

| | 손익 | 승률 |
|---|---|---|
| **실제 방향** | **-30.41pt** | 56.7% |
| 무작위 400회 (중앙) | +16.89pt | 61.9% |
| 무작위 5~95% 구간 | -49.17 ~ +78.78pt | — |

- 실제가 무작위를 상회한 비율 **13.0%** → **단측 p = 0.8703**
- 일자단위(313차): **10/19일**에서 그날 무작위 중앙값 상회 (임계 70%)

- **권고**: 방향 선택이 동전던지기와 구분되지 않는다 (단측 p=0.8703, 일자 10/19일=53%). **방향 피처 재배치(이월 D·E·G)보다 청산 축([41])과 새 정보원 도입이 우선이다** — `FEATURE_SET_DECISIONS`의 `opt_trade_flow_realtime` 재검토 트리거 (3)이 이 상태의 지속을 조건으로 걸려 있다

> ⚠ **절대 수준 인용 금지.** 시뮬은 단순화돼 있다 — TP1(33% 부분익절) +
> 본전이동 + TP2 + 하드스톱 + 종가청산이 전부이고, **트레일링 계단·틱 청산·
> 손절계단화·ProfitGuard·수수료/슬리피지가 없다.** 실제 손익을 재현하지
> 못하며 **유효한 것은 두 팔의 비교뿐**이다(같은 시뮬이라 그 비교는 공정).
> 비용을 빼지 않은 것도 의도적이다 — 양쪽에 동일해 비교에서 상쇄된다.
> 
> **따라서 이 채널은 "시스템 전체의 엣지"를 재지 않는다. 방향 축 하나만**
> **잰다.** 실제 손익이 양수인데 여기서 음수가 나오는 것은 모순이 아니다 —
> 라이브 기하가 이 시뮬보다 정교하기 때문이다.
> 
> **이 채널이 연구 우선순위를 좌우한다.** `docs/미륵이고도화3` 로드맵의
> 이월 D·E·G는 전부 **방향 피처 재배치**이고, [40]이 REJECTS로 굳어 있는
> 동안 그것들은 소수점 싸움이다. 계획서 §5-1이 지적한 *"3단계에서 성공의
> 정의가 비어 있다"* 는 공백을 이 채널이 메운다 — **[40]의 전환이 곧**
> **성공의 정의다.**

---

## [41] 청산 측 학습기 게이지 (MW0602 428차)

**판정 채널이 아니라 게이지다** ([33]과 같은 부류). "언제 학습을 시작할 수
있는가"를 매주 찍는다. 학습기가 **전부 진입 측**이라는 것이 계기다 —
GBM/RF·SGD·`meta_confidence`·`meta_labeling`이 모두 **방향 적중**을 학습하고,
**청산은 전부 규칙**(ATR 고정배수·트레일링·손절계단화)이다. 그런데 425차는
스톱이 16건 중 14건 옳았음을, [40]은 방향이 동전던지기와 구분되지 않음을
보였다 — **돈은 청산에서 온다.**

- 라벨 표본: **531행** / 150포지션 / 19거래일 (포지션당 3.54행)
- 양성률: `y_hold_better` 33.0% · `y_tp1_first` 31.8%

| 게이지 | 현재 | 요건 |
|---|---|---|
| EPV (events per variable) | **3.531** | ≥ 10.0 |
| 포지션 | **150** | ≥ 425 (**275건 부족**) |
| 거래일 | 19 | ≥ 20 |
| 피처 수 | 14 | — |

- 실측 진입속도 **7.89건/거래일** 기준 잔여 약 **35거래일**

> **왜 스스로 학습을 거부하는가.** 395행처럼 보이지만 행은 같은 포지션 안에서
> 강하게 상관돼 있어(포지션당 4.03행) **유효표본은 포지션 수**다. 피처 14개·
> 양성률 32%에서 EPV는 2.25로 통상 기준 10의 **1/5**이다. 이 상태로 학습하면
> 학습이 아니라 암기다 — 그래서 `exit_classifier`가 **학습 자체를 거부**하고
> 얼마나 더 필요한지만 돌려준다.
> 
> 학습이 열리면 **`GroupKFold(groups=entry_ts)`** 를 쓴다. 같은 포지션의 행이
> 학습/검증에 갈라져 들어가면 누출이라 행 단위 KFold는 쓰지 않는다.
> 
> **이 축의 구조적 이점**: 회전율을 **늘리지 않는다**(진입 수 그대로, 청산
> 시점만 변경) → 189회 검정을 전멸시킨 왕복비용 0.133pt를 추가 지불하지
> 않는다. 그리고 **방향 예측이 필요 없다**(이미 진입한 포지션의 조건부 문제).
> 
> ⚠ **라이브 청산에 배선하지 않는다.** `exit_model_shadow`에 기록만 한다.
> 배선은 판정 후 주간회의 결정이며(§9), 계획서 2장이 경고한 "기준선을
> 흔드는 변경"이므로 **D-day(08-14) 스냅샷 이후**에 논의할 것.

---

## [42] 타점(진입 시각)의 가치 (MW0602 429차)

**[40]의 빠진 축이다.** [40]은 진입 시각을 고정한 채 방향만 뒤집어
방향 축만 격리했다. 여기는 **타점 축**을 격리한다 — 3팔 비교에서
**`B − C`가 체크리스트/게이트가 고른 분(minute)의 기여분**이다.

| 팔 | 손익 | 5~95% |
|---|---|---|
| A) 실제시각 + **실제방향** | -30.41pt | — |
| B) 실제시각 + 무작위방향 | +20.68pt | -42.50 ~ +88.64 |
| C) **무작위시각** + 무작위방향 | +6.99pt | -63.54 ~ +84.76 |

- **타점 기여 (B−C) = +13.69pt** · B가 C를 이긴 시행 233/400 (**58.2%**)
- **짝지은 부호검정 p = 0.001128** (타점에 정보가 없으면 50%)
- 후보 분봉 6484개 (09:05~14:49, 거래일별 건수는 실제와 일치)

- **권고**: **타점 선택에 가치가 있다** (기여 +13.69pt, B>C 58.2%, p=0.0011) — 체크리스트/게이트가 고른 분이 무작위보다 낫다. 진입 축 개선의 근거가 생겼고, 그 위에 변동성·미시구조 피처를 얹는 것이 정당해진다

> **짝지은 검정을 쓴다.** 같은 시행에서 B·C를 뽑아 부호를 센다 — 두 팔이
> 같은 시장 데이터를 공유해 양의 상관을 가지므로, 독립 표본으로 다루면
> p가 낙관적으로 나온다.
> 
> C의 후보 분봉은 **09:05~14:49**로 제한한다 — 라이브도 14:50부터 신규진입
> 금지(345차)라 그 밖은 애초에 진입할 수 없다. 거래일별 건수도 실제와 맞춰
> 일중 진입 빈도를 보존한다.
> 
> ⚠ [40]과 **같은 시뮬 한계**를 그대로 물려받는다 — 절대 수준 인용 금지,
> 유효한 것은 팔 사이의 비교뿐이다.
> 
> **[40]과 함께 읽을 것.** 둘 다 REJECTS면 진입 축(방향·타점)이 **둘 다**
> 무작위와 구분되지 않는다는 뜻이고, 그 위에 새 진입 피처를 얹는 것은
> *가치가 검증되지 않은 필터에 검증되지 않은 피처를 더하는* 일이 된다.

---

## [43] 변동성 추정량 교체 가치 (MW0602 429차)

**사이저는 이미 ATR로 변동성 스케일링을 하고 있다**
(`stop_risk = atr × 1.5 × pt_value`). 그러니 질문은 "변동성을 넣자"가
아니라 **"분위 불확실성(선행 예측)이 ATR(후행 실현) 위에 추가 정보를
갖는가"** 다. 판정은 **ATR을 통제한 뒤의 부분상관**으로 한다.

| 지표 | 값 |
|---|---|
| 표본 | 125건 / 14거래일 |
| corr(ATR×1.5, 30분 실현레인지) | **+0.6667** |
| corr(q90−q10, 실현레인지) | +0.6452 |
| 두 추정량 공선성 | **0.9543** |
| **부분상관** (ATR 통제 후) | **+0.0403 (t=0.445)** |
| qty 경계 통과 | 75건 / 125 (60.0%) |

> 🟡 **공선성 0.954 ≥ 0.90 — 두 추정량이 사실상 같은 변수다.**
> 그래도 판정은 부분상관으로 한다(잔차에 정보가 있을 수 있으므로).


- **권고**: ATR 위에 추가 정보가 없다 (부분상관 +0.0403, t=+0.45 < 2.0, 공선성 0.954). **사이징 추정량 교체는 무의미하다** — 사이저는 이미 ATR로 변동성 스케일링을 하고 있고(`stop_risk = atr × 1.5 × pt_value`), ATR 자체가 실현 레인지와 r=+0.667로 이미 좋은 예측자다. 그리고 교체하면 **아무것도 안 바뀌는 것이 아니라** `int()` 절단 때문에 계약수가 **60%(75/125건)에서 갈린다** — 근거 없는 사이즈 변동을 그만큼 주입한다는 뜻이라 무해가 아니라 유해다(CLAUDE.md ⑧·425차의 qty 1↔2 경계 참조).

> **왜 사이징 섀도를 돌리지 않는가.** 측정할 것이 없는 섀도는 잡음만
> 만든다 — [41]이 EPV 미달에서 학습을 거부하는 것과 같은 취지다.
> 이 채널이 SUPPORTS로 바뀌면 그때 섀도를 연다.
> 
> **SUPPORTS일 때도 "교체"가 아니라 "잔차를 더하는" 형태로 설계할 것** —
> 공선성이 높은 두 변수를 맞바꾸면 얻는 것 없이 기준선만 흔든다.
> 
> qty 경계 통과 건수를 함께 재는 이유: 상관이 높아도 `int()`·`min_qty`·
> `MAX_CONTRACTS` 클램프 때문에 경계에서 계약수가 갈릴 수 있다. 그 수가
> 0이면 **교체가 실무적으로도 무효**라는 뜻이다(CLAUDE.md ⑧·425차가
> qty 1↔2 경계의 중요성을 문서화했다).

---

## [44] DynMC 붕괴행 잠식 (MW0602 430차)

`weight_collapsed=1`은 **실질 가중합 0 = 판단 불가**다. 07-31 보정 미적용
전환 이후 이 행들의 conf가 클리핑 상한 0.85로 나가 **분포 최상단을 점유**하고,
DynMC가 그 분포의 p65를 `min_conf`로 쓰기 때문에 정상 신호 행의 통과율이
설계 의도(1−p65≈35%)보다 낮아진다.

| 지표 | 값 |
|---|---|
| 표본 | 2,215행 / 6거래일 (2026-07-31 이후) |
| 붕괴행 비중 | **21.2%** (470행) |
| base_mc — 현행(붕괴 포함) | **0.4211** |
| base_mc — 붕괴 제외 | 0.3957 (차 +0.0254) |
| 비붕괴 통과율 — 현행 | **21.5%** |
| 비붕괴 통과율 — 붕괴 제외 | 35.0% |
| 설계 의도 통과율 | 35.0% → **이탈 +13.51%p** |
| ConstOut 필터 여유 | 최빈값 0.85가 13.1% (임계 15% · 여유 **+1.95%p**) |
| 일자단위 | 6/6일 양수, 부호검정 p=0.0312 |
| 붕괴행 진입 리프트 | **0.05x** (진입 91건 중 붕괴 1건 = 1.1% vs 전체 붕괴율 21.2%) |
| 진입률 추이 | 07-31 0.5% → 08-03 5.7% → 08-04 3.0% → 08-05 4.6% → 08-06 6.2% → 08-07 4.6% |

> **⚠ 판정 = 조치가 아니다.** 붕괴행을 피드에서 빼면 진입이 늘어나는데,
> 427차 [39]가 확정한 대로 `min_conf`는 품질 필터가 아니라 **무작위**
> **샘플러**다 — 늘어난 진입은 무작위 표본 확대이고 기대값의 부호가
> 보장되지 않는다. CLAUDE.md ⑧(사이징·`MAX_CONTRACTS`) 미해제 상태에서는
> **진입 증가 = 노출 증가**이므로, 배선 변경은 주간회의 결정 사항이다.
> 
> **⚠ 판정 창.** `base_mc`는 10일 롤링이라 07-31 전환분이 다 채워지기
> 전(2026-08-11경) 수치로 판정하면 **과도구간을 정상으로 오인한다.**
> `min_days`가 그 방어선이다.
> 
> **[436차] 판정 시 반드시 함께 읽을 것 — 두 관측이 430차 §5와 어긋난다.**
> ① **붕괴행 진입 리프트가 1보다 한참 작다**(위 표의 실측값 — 436차
> 최초 관측 시 채널창 0.06x / 08-03~08-06만 보면 0.07x). 430차 §5는
> 붕괴행이 "진입 예산을 잠식"한다고 했으나, base_mc를 밀어올리는 것과
> 붕괴행이 **실제로 진입하는 것**은 다른 이야기다. 리프트가 계속 1을 크게
> 밑돌면 붕괴행 제외는 "판단 불가 행에 진입을 준다"가 아니라 **"정상 행의
> 통과율을 복원한다"**로 읽어야 하며, 그러면 위 ⚠(노출 증가)의 무게가 달라진다.
> ② **자기소멸이 아직 관측되지 않았다.** 430차 §5는 base_mc 수렴과 함께
> 진입 급증이 되돌아간다고 투영했는데(~08-11), 0806까지 base_mc는 투영대로
> 올랐고(0.3971→0.4151, 투영 0.418) **진입률은 되돌기는커녕 신고점**이었다
> (5.7%→3.0%→4.6%→**6.2%**). 위 "진입률 추이" 행이 그 후속이다 —
> 판정 시점에도 되돌지 않았으면 **투영 자체를 안건화할 것**.
> 
> **ConstOut 여유폭을 왜 같이 재는가.** `main.py:_recalibrate_mc`에
> "동일 반올림값 15% 초과 시 제외" 필터가 있다. 430차 실측에서 0.85가
> **12.6%**로 2.4%p 차이로 빠져나갔다 — 붕괴율이 오르는 날(07-29는 45%)엔
> 필터가 걸리고 안 걸리고가 뒤바뀌어 `base_mc`가 불연속으로 튄다.
> 임계는 손대지 않는다(낮추면 정상 conf 최빈값까지 걸린다) — **여유폭만**
> **노출**해 그 순간을 사후에 설명할 수 있게 한다.

---

## [45] 축퇴 가드 플래핑 (MW0602 430차 · 게이지)

**판정 채널이 아니다**([33]·[41]과 같은 게이지). 앙상블 보정기의
적용/미적용이 하루 중 몇 번 뒤집히는지, 그 전환이 conf에 만드는 점프폭이
얼마인지만 잰다. 행 단위 복원 규칙: `confidence == min(confidence_raw, 0.85)`
이면 **미적용**(raw 통과)이다.

| 지표 | 값 |
|---|---|
| 표본 | 2,215행 / 6거래일 |
| 보정 미적용 비율 | **76.1%** |
| 전환 횟수 | 총 79회 · **13.17회/일** 🟡 |
| 전환 시 conf 점프 | 중앙값 **0.3392** / 최대 0.5150 🟡 |

| 일자 | 행 | 미적용% | 전환 |
|---|---|---|---|
| 2026-07-31 | 367 | 30.8% | 18 |
| 2026-08-03 | 370 | 92.2% | 6 |
| 2026-08-04 | 370 | 98.7% | 4 |
| 2026-08-05 | 370 | 84.0% | 20 |
| 2026-08-06 | 369 | 74.8% | 20 |
| 2026-08-07 | 369 | 75.9% | 11 |

- **권고**: 히스테리시스(또는 EOD 1회 고정) 도입을 주간회의 안건으로. ⚠ **AUC 임계·보정 함수형은 건드리지 말 것** — 근본 문제는 임계가 아니라 정보 부재이고(raw conf 순위 AUC 0.489 < 0.5, 427차 [39]와 일치), 임계를 손대면 conf 스케일에 세 번째 불연속이 생긴다.

> **왜 게이지인가.** 축퇴 판정은 `auc < 0.53` **단독**으로 내려진다 —
> AND의 span 조건은 사문이다(로그 845건 전수 최대 0.01321, 임계 0.02
> 도달 0건. `learning/calibration.py` 430차 정정 주석 참조). n=200에서
> AUC의 SE≈0.041이라 이 통계량이 0.53을 수시로 넘나든다.
> 
> **⚠ 이 채널은 임계 튜닝을 정당화하지 않는다.** 근본 문제는 임계가 아니라
> **정보 부재**다 — raw conf의 1m 적중 순위 AUC=**0.489**(<0.5, 역방향)로
> 어떤 단조 보정도 붙일 신호가 없다(427차 [39] REJECTS_HYP와 일치).
> 개선 여지는 "정보 없음을 **안정적으로 표시**하는 것"(히스테리시스 또는
> EOD 1회 고정)뿐이고, **AUC 임계·보정 함수형은 건드리지 않는다** —
> 건드리면 conf 스케일에 **세 번째 불연속**이 생긴다.

---

## [46] HurstGate 임계 위치 A/B (MW0601 434차 신설)

현행 임계 `HURST_RANGE_THRESHOLD = 0.45`가 이 추정량의 **판별 경계로**
**적절한 위치인가**를 묻는다. 지표는 **계약당 pt의 분리도**
(= 통과구간 평균 − 차단구간 평균)로, 계약당 정규화라 **사이징과 무관**하다.

- 진입 159건 중 hurst 매칭 159건 / 19거래일 · 분위 룩백 10거래일(당일 제외)

**전체표본 — ⚠ in-sample, 판정 근거 아님**

| 후보 | 차단n | 발동률 | 차단평균pt | 통과평균pt | 분리도 | drop-worst | 차단승률 | 통과승률 |
|---|---|---|---|---|---|---|---|---|
| abs_0.30 | 16 | 10.1% | -0.343 | +0.227 | **+0.569** | +0.287 | 68.8% | 63.6% |
| abs_0.36 | 46 | 28.9% | -0.691 | +0.520 | **+1.211** | +1.018 | 58.7% | 66.4% |
| abs_0.39 | 57 | 35.9% | -0.549 | +0.571 | **+1.119** | +0.962 | 61.4% | 65.7% |
| abs_0.42 | 75 | 47.2% | -0.416 | +0.692 | **+1.108** | +0.987 | 60.0% | 67.9% |
| abs_0.45 ← 현행 | 90 | 56.6% | -0.402 | +0.914 | **+1.316** | +1.215 | 60.0% | 69.6% |
| q10 | 19 | 11.9% | -0.136 | +0.211 | **+0.347** | +0.122 | 79.0% | 62.1% |
| q20 | 37 | 23.3% | -0.720 | +0.439 | **+1.159** | +1.052 | 62.2% | 64.8% |
| q30 | 57 | 35.9% | -0.684 | +0.646 | **+1.331** | +1.234 | 57.9% | 67.7% |

**OOS (2026-08-06 이후) — 판정 대상**

| 후보 | 차단n | 발동률 | 차단평균pt | 통과평균pt | 분리도 | drop-worst | 차단승률 | 통과승률 |
|---|---|---|---|---|---|---|---|---|
| abs_0.30 | 11 | 27.5% | -0.116 | -0.210 | **-0.094** | -0.400 | 72.7% | 69.0% |
| abs_0.36 | 17 | 42.5% | -0.338 | -0.071 | **+0.266** | +0.019 | 70.6% | 69.6% |
| abs_0.39 | 19 | 47.5% | -0.424 | +0.032 | **+0.457** | +0.241 | 68.4% | 71.4% |
| abs_0.42 | 22 | 55.0% | -0.336 | +0.000 | **+0.336** | +0.147 | 68.2% | 72.2% |
| abs_0.45 ← 현행 | 25 | 62.5% | -0.358 | +0.105 | **+0.464** | +0.299 | 68.0% | 73.3% |
| q10 | 14 | 35.0% | +0.023 | -0.296 | **-0.319** | -0.565 | 78.6% | 65.4% |
| q20 | 18 | 45.0% | -0.468 | +0.047 | **+0.515** | +0.290 | 66.7% | 72.7% |
| q30 | 20 | 50.0% | -0.390 | +0.021 | **+0.411** | +0.205 | 70.0% | 70.0% |

- **판정: SUSPENDED** — 판정 정지 — 재생기가 실제를 재현하지 못한다(§47). 원 판정 `INSUFFICIENT`: OOS 표본 부족 (n=40<40 또는 거래일=2<10). 전체표본 결과는 가설 수립 기간의 in-sample이라 판정 근거가 아니다

**판정보조 ② 일자단위 (313차)** — 저hurst(<0.45) 진입 비중 vs 그날 계약당 합pt

| 일자 | 진입n | 저hurst 비중 | 합pt |
|---|---|---|---|
| 2026-07-27 | 3 | 100% | -2.64 |
| 2026-07-28 | 4 | 50% | +6.06 |
| 2026-07-29 | 2 | 0% | +21.54 |
| 2026-07-30 | 1 | 0% | -9.44 |
| 2026-07-31 | 2 | 0% | +0.69 |
| 2026-08-03 | 21 | 100% | -8.04 |
| 2026-08-04 | 11 | 18% | +9.48 |
| 2026-08-05 | 17 | 65% | -8.32 |
| 2026-08-06 | 23 | 87% | -6.34 |
| 2026-08-07 | 17 | 29% | -1.04 |

> **⚠ 사전등록 정직성 고지**: 후보 목록은 2026-08-05 점검에서 **이미 1회**
> **스윕한 뒤에** 골랐다. 따라서 전체표본은 **가설을 세운 그 기간의 in-sample**
> 이며 그 자체로는 판정 근거가 아니다 — 사전등록 가치는 OOS에 있다([23]과 동일).
> 
> **⚠ 이미 반증된 방향 — 재시도 금지**: 추정량 **편향보정**(상수이동·선형
> de-shrinkage)은 317차가 60거래일 실측에서 **FalsePass 14.4%→30~33% 악화**로
> 폐기했다(`HURST_DESHRINK_TABLE`은 REFERENCE ONLY). 이 채널은 추정량을 고치지
> 않고 **임계 위치만** 묻는다. 317차가 손댄 N/max_lag와도 질문이 다르다 —
> 26주 WFA 재검증 항목을 앞당길 이유가 아니다.
> 
> **⚠ 372차 함정**: PSI 임계 재보정 시도가 이상치 2건이 만든 값으로 확인돼
> **기존값 유지**로 끝났다. 여기도 표본이 얇다 — `drop-worst`(차단구간 최악
> 1건 제거)와 위 일자단위를 **반드시 함께** 읽을 것. 분리도만 보면 같은 함정이다.
> 
> **⚠ 임계를 낮추면 노출이 는다.** 발동률이 줄어 사이징 축소가 덜 걸린다.
> CLAUDE.md ⑧ 미해제 상태에서는 그 자체가 리스크이므로 승격 시 총노출 병기 필수.
> 
> **⚠ [3-6] `hurst_gate_shadow`와 다른 질문이다** — 그건 "차단된 신호가
> 벌었을까"(모집단: 차단분), 이건 "임계가 좋은/나쁜 신호를 가르는가"
> (모집단: 실제 진입분)다. 두 verdict는 서로 무관하다(§9-4).

---

## A/B 채널 기준선 PC 대조 (표시 전용 — 판정 미반영)

`[3-B]`·`[23-B]`·`[25]`의 FAIL 판정은 전부 `delta_vs_current`(대안 − 현행)로
내린다. 따라서 **기준선 `current` 자체의 부호가 PC간 반대면 같은 대안이 한 PC에서만**
**"현행 초과"로 등재된다** — 그 목록을 단일 PC 근거로 채택하면 안 된다.

| 채널 | MW0602 | MW0601 (20260801) |
|---|---|---|
| [3-B] 분위회귀 TP1 거리 A/B | **-24.403** | **-16.9406** |
| [23-B] TP1/손절 초기 기하 A/B | **-26.7976** | **-17.1783** |
| [25] TP1 보호전환 offset A/B | **118.6232** | — |

*단위 pt — 각 채널 `per_variant.current.total_pt`(현행 전략의 재생 손익).*

> 기준선 부호가 모든 PC에서 일치한다 — A/B 결과를 그대로 읽어도 된다.
> 상대 PC 날짜가 이번 주가 아니면 그 PC가 아직 리포트를 생성/커밋하지
> 않은 것이다. **날짜가 다른 두 리포트를 같은 주로 취급하지 말 것.**

---

## 확정 결정 레지스트리 (주간회의 수동 결정 이력)

### `grade_ev_inversion` — 부결 — GradeEVGuard 활성화하지 않음 *(2026-08-01)*

A등급 누적 −488,009원에서 [15] 급행 풀스톱(TP1 미도달·보유 ≤150초) 11건 −1,060,617원을 제외하면 나머지 42건은 +572,608원(평균 +13,633원)이다. 부분집합 관계는 [15] C등급 1건 −210,640원이 [13] C등급 최대손실과 정확히 일치하는 것으로 확인된다. 즉 등급 문제가 아니라 급행 풀스톱이라는 별개 실패 모드이며, A등급 전체를 강등하는 GradeEVGuard는 대상 오조준이다.

### `hurst_gate_shadow` — 추가 조치 없음 — 권고는 2026-07-15에 이미 이행됨 *(2026-08-01)*

리포트가 찍는 '하드차단 → 사이징 ×0.5 완화' 권고는 333차 후속(2026-07-15)에 이미 배포돼 라이브 중이다(HURST_SOFT_BLOCK_ENABLED=True, main.py:7298). FAIL이 유지되는 것은 미조치가 아니라, 완화가 MINI_MIN_CONTRACTS=1 하한에서 실측 91%(45건 중 41건) no-op이기 때문이다. 사이징 축 처방은 더 추구하지 않고 청산 '거리' 축([3-A]·[3-B])으로 선회했다.

### `meta_gate` — 탈락 확정 — 승격 포기 *(2026-08-01)*

상위분위 순EV −0.0499pt < 하위분위 +0.031pt로 분리도 −0.0809(필요 +0.1457). 부호가 반대이고 분위당 n=402로 표본 핑계가 불가하다. 감사 §5 활성화 순서 2순위(Meta-gate 사이징)를 공식 삭제하고 entry_quality_prob 재설계로 이관한다.

### `quantile_tp_shadow` — FAIL이지만 미적용 — MW0601 교차확인 선행 *(2026-08-01)*

q_raw는 drop-max를 견딘 첫 대안이다(+9.36 → +7.76, 건별우세 25/36). 그러나 결과가 단조롭지 않다 — q_x0.7이 현행보다도 나쁘다. 폭 자체가 아니라 '몇 건이 TP1↔STOP으로 뒤집히나'가 결과를 지배하며 n=36에서 그 2건은 얇다. [23-B]의 PC간 부호 역전 전례가 있어 MW0601 교차확인 전에는 판단 보류.

### `tp1_geometry_shadow` — FAIL이지만 미적용 — 현행 유지 *(2026-08-01)*

MW0601에서 tp1_x2가 +32.78pt(현행 초과), MW0602에서 −19.04pt로 **PC간 부호가 역전**된다. 같은 코드·같은 기간인데 거래집합만 달라 결론이 뒤집히므로 n≈60·12일로는 기하를 결정할 수 없다(313차). ▪ **[MW0601 421차 후속4·5, 2026-08-03] OOS 신호 — 단, 판정 근거는 아니다.** 405차가 넣은 `oos_start=2026-07-31`(403차 배포 다음 거래일) 이후 신규분에서 tp1_x2가 현행 대비 **−8.79pt로 열위**다(current −14.14 vs tp1_x2 −22.93, 승률 66.7%→37.5%, n=24·MW0601). 전체표본 우위(+22.13pt, n=77)와 부호가 반대이며, 403차 결과가 **가설을 세운 그 기간의 in-sample**이라는 405차 우려와 방향이 맞다. ⚠ **그러나 이 OOS 표본은 24건 전부가 2026-08-03 하루다**(07-31 시스템 진입 0건). `min_days=3` 미달이고 **313차 '단일일 판정 금지'에 정면으로 걸린다.** 게다가 그날은 일중 레인지 3.24%의 극단 휩소 세션이다 — 기하 대안의 성능은 변동성 체제에 민감하므로 단일 이상일의 결과를 일반화할 수 없다. **따라서 이것은 '두 번째 반증'이 아니라 관찰 신호다.** 결정을 지탱하는 근거는 여전히 위 PC간 부호 역전 하나이며, OOS는 거래일이 3일 이상 쌓인 뒤 재확인할 것. (OOS는 표시 전용이며 verdict/합격선 무변경 — §9-4 시계 리셋 없음)

### `direction_ev_watch` — 판정보류 — LONG 방향만 PC간 부호 역전 *(2026-08-02)*

SHORT는 양쪽 양수로 일치하나(+12,690 / +53,745원) LONG이 MW0601 +16,138원(n=25) vs MW0602 −52,786원(n=18)로 **부호가 반대**다. MW0602는 LONG n=18로 min_samples_per_direction=20 미달이라 verdict 자체는 INSUFFICIENT지만, 역전 사실은 표본과 무관하게 남는다. 두 PC의 방향 분포가 애초에 다르다는 것도 미분해 이슈다(LONG 25/18 · SHORT 30/42). MW0602 §1-5 '방향 편향은 레짐 효과와 구분 불가'와 일관 — **방향 축 처방(LONG 차단·축소 등)을 지금 설계하지 말 것.**

### `signal_decay` — 판정보류 — PC간 부호 역전 (어느 쪽도 단일 근거 불가) *(2026-08-02)*

누적 saved가 MW0601 −2.0516pt(n=10, FAIL) vs MW0602 +12.9656pt(n=13, PASS)로 **부호가 반대**다. 양쪽 다 사전등록 min_samples=10을 충족했으므로 표본 부족 핑계가 불가하다 — 0802 대조 §2-C의 가장 강한 사례. 두 PC는 같은 코드지만 각자 EOD 재학습으로 **다른 모델**을 돌리므로(v9-dev↔dev 매매로직 동일 확인) 이 역전이 모델 인스턴스 발산인지 표본 노이즈인지 분해되지 않았다. n이 양쪽 20을 넘고 부호가 한쪽으로 수렴할 때까지 채택·폐기 모두 보류.

### `faststop_discovery` — 잠정 음성 — 진입측 판별 시도 중단, 표본 축적 후 재실행 *(2026-08-03)*

**[MW0601 421차 후속9·10 / Phase A]** 급행 풀스톱(FAST: TP1 미도달 ∧ 보유 ≤150초) 20건 −369만원이 지배적 실패 모드인데, 이를 **진입 시점 정보로 가려낼 수 있는가**를 245개 피처로 훑었다(일자 내 라벨 순열 20,000회로 날짜 교란 제거, 유효표본 69건·7일). **BH FDR 10% 통과 0개** — 최강 후보 p=0.0039가 검정 245개의 노이즈 최소p 기대치(1/245=0.0041)와 구별되지 않는다. 진입측 판별 불가는 이것이 **네 번째 확인**이다(가격기반 4지표 |t|<1.3 → InstabilityGate 승1/패2 발동·패2 미발동 → 동일 체크리스트가 승·패로 갈린 쌍 conf 34.7 vs 34.8% → 245개 그물). ⚠ **'확정'이 아니라 '잠정'이다** — 발굴 단계이고 확증창을 거치지 않았으며 유효표본이 7일뿐이라 중간 크기 효과를 놓쳤을 수 있다. **결정((a)+(c) 병행, 2026-08-03 사용자)**: ① 신규 진입 차단 게이트 개발을 중단하고 자원을 청산기하·집행 축으로 재배치한다 ② 하네스는 남기고 표본이 쌓이면 재실행한다 — 재실행 시점은 [33] `faststop_rerun_watch`가 매주 게이지로 알린다(interim ≈ 2026-08-14 / full ≈ 2026-08-25 실측 ETA). ③ Phase D(틱 그물)는 재실행도 전멸일 때만 착수 — 구현이 무겁고 되돌리기 어렵다. 재배치 대상 우선순위: [23] 기하 재론(OOS 거래일 3일+ 축적 후) > 지정가 집행 검증(4지표·중단기준 사전등록분) > [17] 하드스톱 체결 방식. 근거: `docs/정기점검/금요일점검/0803_급행풀스톱_처방_종합개선계획.md`, `0803_faststop_discovery_후보표.md`, `dev_memory/DECISION_LOG.md` 421차 후속9.

### `sizing_prescription_axis` — **재개(reopened)** — 2026-08-01 '(b) 처방 축 전환 확정'의 근거가 417차에 무효화됨. 431차가 사이징 축을 다시 연다(상한 3 + 체인 재구성) *(2026-08-05)*

**[MW0601 431차, 2026-08-05 사용자 지시]** 이 항목의 2026-08-01 결정은 '(a) 기본 계약수 상향은 MW0601 §9-3 실측으로 반증됐다'를 유일한 근거로 삼았는데, 그 §9-3 수치가 **다음 날 417차에 무효화**됐다(행=청산레그 단위 집계 → 포지션 단위로 재계산 시 p=5.07e-07이 p=0.93으로 소멸, 카운터팩추얼 단조도 붕괴). 근거가 사라졌으므로 결정도 유지될 수 없다. 417차는 CLAUDE.md ⑧과 리포트 생성기만 정정하고 이 레지스트리를 갱신하지 않아, 무효 수치가 3일간 사이징 축을 계속 봉쇄했다(431차 발견). **431차 재확인(160포지션, 06-10~08-04, entry_qty 기준)**: qty=1 승률 50.5%로 1~3 구간 최저, 계약당손익도 최저(+3,101원 vs qty=2 +74,082원/qty=3 +16,928원), 진입계약수 vs 계약당손익 rho=+0.026(p=0.74). 손실은 qty>=6 9포지션 -1,609만원 집중. ⚠ **역방향도 미확정** — qty=1 vs 2~3 승률차 z=+1.34 p=0.18, 07-14 이후 qty>=2 n=7. 따라서 '2~3이 낫다'가 아니라 **'1계약 고정을 정당화하는 근거가 없다'**까지만 주장하며, 조치는 총노출 중립으로 설계했다(진입 91건 시뮬: 137 → 135계약). **431차 조치 3건**: ① MAX_CONTRACTS 10→3 ② 품질군 게이트(exec/meta/tox/hurst) min() 합성 + 단일 반올림 ③ MetaGate reduce 폴백 0.5 → 중립 1.0. **MINI_MIN_CONTRACTS=1은 그대로**(하한 상향은 여전히 근거 없음). 안전군 게이트(Degraded·VolBurst·L2)는 **곱셈 유지** — 서로 독립 위험이라 중복 계상이 아니다. 근거: dev_memory/DECISION_LOG.md 431차. ▪ **[MW0601 433차, 2026-08-05] 근거 정정 + 조치 1건 추가.** 431차가 안전군에 넣었던 `pre_retrain`을 **품질군으로 이동**했다(`PRE_RETRAIN_SIZE_QUALITY_GROUP`). 431차 주석의 '최근 20거래일 안전군 발동 0건'은 **사실이 아니다** — 실측상 pre_retrain ×0.6은 160사이클/15거래일 발동했고 그중 24건이 실제 진입이다. 그래서 431차 시뮬(2계약+ 37%)과 08-05 실측(16%)이 갈렸다(사이저 3 → 3×0.6=2 → ×min(quality)0.50 → 1로 **이중 축소·이중 반올림**). 나머지 안전군 3종의 '발동 0건'은 맞으므로 그 부분은 유효하다. ⚠ **이 이동은 노출을 늘린다** — 재시뮬 24건 중 10건(42%)이 +1계약, 해당 구간 총노출 24→34계약(+41.7%). 손익 근거는 없다(n=23 승률 52.2% 이항 p=1.000, 일자단위 8일 중 5일 음수 — 소수 대박일). **근거는 분류 타당성 하나뿐**이며 손익 악화 시 플래그를 False로 되돌린다.

### `tp1_protect_offset_shadow` — FAIL이지만 미적용 — 현행 유지 (근거 교체됨: drop-max 제동 소멸 → 계측 결함 + 일자단위 미유의로 대체) *(2026-08-05)*

**[MW0602 432차, 2026-08-05]** 결론(현행 유지)은 0801과 같지만 **이유가 완전히 바뀌었다.** 0801 근거를 그대로 인용하면 안 된다.
① **0801의 제동이 전부 소멸했다** — 표본이 23건/8일 → 49건/11일로 늘며 drop-max가 −1.33 역전 → **+16.50 유지**, leave-one-day-out 최악 **+10.00**, 건별 우세 8/23(소수) → **28/49(과반)**. 즉 0801 결정문의 3개 근거가 다 사라졌다.
② **그런데 변형 정의에 계측 결함이 있었다** — `_offset_for()`에 상한이 없어 보호전환 시점의 실제 유리이동을 넘는 offset이 허용됐고, `_simulate()`가 다음 봉에서 무조건 체결로 읽어 **시장이 제시한 적 없는 가격을 계상**했다. 실측 49건 전수: atr_lock_0.75 **28건(57%)이 체결 불가**, bar_range 14건(29%), atr_lock_0.50 5건(10%). current/breakeven/breakeven_plus는 0건(영향 없음).
③ **클램프 후 진짜 값**: atr_lock_0.75 +18.75 → **+8.04pt**(허수 57%), bar_range +8.50 → +4.96, atr_lock_0.50 +3.81 → +2.23. 그리고 **일자단위 t검정 p=0.255로 확립되지 않는다**(11거래일, 4일은 Δ=0.00). → 313차 원칙상 적용 근거 미달.
④ **이 채널에서 일자단위로 유의한 것은 `breakeven` 하나뿐이고 방향은 음이다** (−9.23pt, p=0.021). 즉 확립된 사실은 '보호를 본전으로 놓으면 현행보다 나쁘다' 이며 404차 후속3 최초 관측(23건 중 현행 22/23 우세)과 일치한다.
⑤ **판독규칙 (3) 여전히 유효** — MW0601 표본은 08-03 시작분뿐이라 MW0602 단독 판정을 확정으로 쓰지 않는다. 다만 MW0601 08-03 스냅샷(atr_lock_0.75 +7.76pt· 우세 10/14)은 **같은 방향**이므로, MW0601 표본이 차면 규칙 (1) 승격 후보가 된다 — 그때는 **반드시 클램프 적용본으로 대조할 것**.
⚠ 클램프 도입은 자기유리 편향이 아니다 — 대안의 우위를 3배 **줄이는** 방향이다.
⚠ **2026-08-05 이전의 모든 [25] 수치는 클램프 이전 값**이다(0801 리포트, 0803 채널설명서 §5·§6 포함). 인용 금지.
⚠ 함께 조치: `TP1_PROTECT_ATR_LOCK_MULT`가 main.py·main_dashboard.py·이 스크립트에 3중 리터럴로 박혀 있고 settings.py에는 없던 것을 단일화했다 (432차). 한 곳만 고치면 섀도 `current` 기준선이 라이브와 어긋나 이 채널의 모든 A/B 판정이 무효가 되는 구조였다.
근거: dev_memory/DECISION_LOG.md 2026-08-05(MW0602 432차), docs/정기점검/매일점검/MW0602-20260805-점검리포트.md §5.
───── 이하 2026-08-01 원 결정문 (보존, 위 ①로 무효화됨) ─────
**[MW0602 표본 23건 기준]** 현행 초과 대안들이 **최대 기여 1건만 빼면 부호가 역전**된다(atr_lock_0.75 +0.92→−1.33pt, bar_range +0.81→−0.29pt). 건별 우세도 8/23·7/23으로 소수이고 중앙값 차이는 0.000pt다(372차 이상치 분해). ⚠ **PC 출처 주의(421차 후속2 추가)** — 이 23건은 MW0602의 `atr_profit` 행이다(404차 후속3: "MW0602는 atr_profit … DB 23건 세 소스 일치"). MW0601은 당시 `breakeven`이라 유효표본 0이었고, 406차(08-02)가 MW0601을 atr_profit으로 통일하면서 **MW0601 표본이 08-03부터 새로 시작**했다. 즉 406차는 이 결정을 무효화하지 않는다 — MW0601의 독립 확인이 아직 없을 뿐이다. (0803 점검에서 이 note에 PC가 없어 "근거가 무효화됐다"고 오독한 사고가 실제로 발생해 출처를 명기한다. CLAUDE.md feedback_devmemory_pc_provenance)

> **판정(verdict)과 결정은 별개다.** 판정은 사전등록 기준으로 매주 자동
> 재계산되므로, 사람이 "보고 나서 일부러 적용하지 않기로" 한 채널도 FAIL이
> 계속 뜬다. 그 FAIL을 미조치로 오독하지 말 것 — 위 표에 결정이 있으면 이미
> 검토가 끝난 것이고, 뒤집으려면 새 근거가 필요하다.
> 반대 방향의 사고도 실제로 있었다: [6] Hurst 완화 권고는 2026-07-15에 이미
> 배포됐는데 리포트가 3주째 같은 권고를 찍어, 0801 결산 초안이 그것을 신규
> 승인 안건으로 잘못 올렸다(코드 확인 후 철회). 이 레지스트리가 그 재발 방지책이다.
> 출처: `config/settings.py:VALIDATION_CAMPAIGN_DECISIONS`. 결정 변경 시
> 그쪽을 갱신하고 `dev_memory/DECISION_LOG.md`에도 기록할 것(§9).

---

> 이 리포트는 권고만 출력한다. 정책 적용/롤백은 주간 회의에서 수동 결정하고
> `dev_memory/DECISION_LOG.md`에 기록할 것 (§2 사전등록 원칙, §9 계엄령).